### ISSUE TITLE
Blaze Datasource

### ISSUE THREAD

**Issue by femtotrader** [mementum/backtrader#10]
Hello,

it will be nice to provide some example to use a database as data source.
Blaze could help http://blaze.pydata.org/en/latest/
as it rely on SQLAlchemy, many databases could be used.
odo could also help http://odo.readthedocs.org/

Kind regards

**Comment by mementum** [comment]
Creating a data feed from any kind of source data (which is a documentation + example topic) is something I wish to tackle in the upcoming days

**Comment by mementum** [comment]
Given I don't have any data in databases documentation on creating a Data Feed from a binary source has been created using the available means (available to the author)

The same steps are applicable to a database or online data source

http://www.backtrader.com/posts/2015-08-11/datafeed-development/

To be added to the general documentation asap.

**Comment by mementum** [comment]
Following up, Pandas Dataframes are supported directly now

**Comment by xingjianpan** [comment]
Nice!

**Comment by femtotrader** [comment]
With Pandas DataFrame, whole data need to be in memory...
it can be very long to get data from database to put in memory before starting a backtest.

that's not the case with Blaze.
see http://blaze.pydata.org/en/latest/rosetta-pandas.html

you can iterate over a database table by chunk using

    from odo import odo
    table_uri = 'dialect+driver://user:password@host:port/database::table'
    for i, chunk in enumerate(odo(table_uri, chunks(pd.DataFrame), chunksize=chunksize)):
        print("="*5 + " chunk %d " % (i + 1) + "="*5)
        for j, row in chunk.iterrows():
            print(row)

that's why I think Blaze support is an interesting idea.

**Comment by femtotrader** [comment]
I also noticed that you talk about Pandas DataFrame support but not about Pandas Panel.

Maybe you should also support Pandas Panel

see https://github.com/pydata/pandas-datareader

    $ pip install pandas_datareader

and now you can do

    from pandas_datareader.data import DataReader
    panel = DataReader(["MSFT", "YHOO", "GOOG", "IBM"], "google")
    df_ibm = panel.loc[:,:,"IBM"]

**Comment by mementum** [comment]
With regards to "panel"

  - It seems that df_ibm is a regular Pandas DataFrame and as such can be passed to backtrader following the conventions laid out in: http://www.backtrader.com/posts/2015-08-21/pandas-datafeed/

  - The issue here as already noted in the pandas-datareader documentation with regards to remote data access is that "not all sources implement the same methods and the data elements returned might also differ"

The "yahoo-online" case (which is already directly supported by backtrader) has a non-standard industry field "adj close" which is meant to account for splits/dividends/counter-splits et al.

This field is not sent back by Google. And hence the point is not supporting the "panel" from pandas-datareader, but having a specialized class which knows about the presence of "Adj Close" and uses it or not following the indications of the end user.

With regards to blaze:

  - As with Pandas DataFrames, backtrader may support the a "Data" object passed to it and iterate over the rows, but will not invoke the database and/or online connection code.

  - And some assumptions have to be made such as: the time has already been parsed to the native type supported

  - I have loaded the sample '2006-day-001.txt' file from backtrader with blaze using data = Data('./2006-day-001.txt' and the result is that everything was parsed as "str" (very weak)

  - The same file with the same "txt" extension passed directly to Pandas is nicely parsed (and blaze claims to use pandas.read_csv for the parsing)

  - Changing the extension of the file to "csv" renders a parsin in which the datetime type is a native Python datetime.datetime object.

Is this always True with regards to for any database source in blaze that the datetime will be a native datetime.datetime Python object?

**Comment by mementum** [comment]
Additionally ... your major concern (seeing your other requests for blaze support for PyAlgoTrade, zipline, ...) seems to be loading the entire dataset in memory.

Actually a decision design in backtrader is to keep the entire dataset in memory (and as default ... actually to preload it)

Not only the dataset but all derived calculations (indicators and observers)

**Comment by femtotrader** [comment]
Yes that's something important in my mind.

**Comment by mementum** [comment]
You may try the followind code for data feed provided by a "Data" from blaze.

According to the blaze documents chunking is automatically activated if the data source is large, so there should be no need to pass the chunks to a Pandas DataFrame.

To use the data feed below:

````python

blaze_data = Data('mycsv.csv')  # or a database uri
data = BlazeData(dataname=blaze_data)

cerebro = backtrader.Cerebro()
cerebro.adddata(data)

cerebro.addstrategy(MyStrategy)

cerebro.run()
````

In any case: the entire dataset will be loaded in memory) and the code is untested and may still contain typos

````python
class BlazeData(feed.DataBase):
    '''
    The ``dataname`` parameter inherited from ``feed.DataBase`` is the blaze
    Data
    '''

    params = (
        # datetime must be present
        ('datetime', 0),
        # pass -1 for any of the following to indicate absence
        ('open', 1),
        ('high', 2),
        ('low', 3),
        ('close', 4),
        ('volume', 5),
        ('openinterest', 6),
    )

    datafields = [
        'datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest'
    ]

    def start(self):
        # reset the iterator on each start
        self._rows = iter(self.p.dataname)

    def _load(self):
        try:
            row = next(self._rows)
        except StopIteration:
            return False

        # Set the standard datafields - except for datetime
        for datafield in self.datafields[1:]:
            # get the column index
            colidx = getattr(self.params, datafield)

            if colidx < 0:
                # column not present -- skip
                continue

            # get the line to be set
            line = getattr(self.lines, datafield)
            line[0] = row[colidx]

        # datetime - assumed blaze always serves a native datetime.datetime
        colidx = getattr(self.params, self.datafields[0])
        dt = row[colidx]
        dtnum = date2num(dt)

        # get the line to be set
        line = getattr(self.lines, self.datafields[0])
        line[0] = dtnum

        # Done ... return
        return True
````

**Comment by femtotrader** [comment]
Thanks I will try this

**Comment by mementum** [comment]
Added two import  before the class definition ... in case they were not obvious

**Comment by mementum** [comment]
As of 1.1.6.88 backtrader implements an "exactbars" approach which will allocate exactly as many needed positions per data/indicator/observer to complete the analysis. This reduces the memory consumption to the minimum possible expression.

The drawback is that this method is not compatible (and therefore deactivates it) with:

  - runonce (calculation of indicators in vectorized mode)
  - preload (preloading of data sources)
  - plotting (only the last n bar per object are available and each object may have a different number of bars)

It can be activated by creating the cerebro instance as follows:

    cerebro = bt.Cerebro(exactbars=True)
