### ISSUE TITLE
Any Plan to Implement OANDA Forex Data Feed and Live trading 

### ISSUE THREAD

**Issue by developeralgo8888** [mementum/backtrader#106]
Any Plans to implement OANDA Forex Data Feed and Live Trading would very ideal and helpful

**Comment by mementum** [comment]
`Oanda` has Python bindings and may get implemented in a future release. Right now something else is getting integrated.

**Comment by mementum** [comment]
Summary:

  - The Python bindings are for the REST API (v1)
  - The new REST v20 (or v2) API is half-cooked, lacking documentation, functionality and with only half of the endpoints available (the others are "Coming Soon")

  - Demo accounts are opened as v20 and the access tokens aren't valid for the v1 API because the account is v20 ... obviously.

  - If using Chrome to access the site it is 100% unclear whether you are logged in or out and authentication has to be performed 1000 and 1 times.

This is for sure not going to happen any time soon.

**Comment by 4ever911** [comment]
I agree! I just applied a demo account, and found little resource and document on the REST API 2.0
