### ISSUE TITLE
Order Filling Strategy

### ISSUE THREAD

**Issue by dafyddd** [mementum/backtrader#107]
First of all, thanks a lot for your work on this software. I'm making the switch from pyalgotrade to backtrader because it's nicer and cleaner, in my opinion. 

However, I read that you don't take into account volume when filling orders. This is a problem for me since I trade in some fairly illiquid markets. Am I mistaken? Is there actually a way to specify how much of my order will be filled as a function of the volume?

If not, I am willing to write a class that adds that functionality. It will be modeled off of the FillStrategy class in pyalgotrade. Here is a reference to the docs for that class:
http://gbeced.github.io/pyalgotrade/docs/v0.17/html/broker.html#pyalgotrade.broker.fillstrategy.FillStrategy

Let me know!

**Comment by mementum** [comment]
> However, I read that you don't take into account volume when filling orders. This is a problem for me since I trade in some fairly illiquid markets. Am I mistaken? Is there actually a way to specify how much of my order will be filled as a function of the volume?

Yes. *Volume* is not considered for order filling. This is a design decision. Let's consider for example a `Fill or Kill` order. To avoid writing something up, let me quote *Interactive Brokers*

  - https://www.interactivebrokers.com/en/index.php?f=586

> Setting FOK as the time in force dictates that the entire order must execute immediately or be canceled. A trader might see a short-lived opportunity to buy or sell a stock or option that would suit a strategy or fit within a portfolio. However, the time opportunity might be subject to buying or selling a minimum number of shares or options. The fill-or-kill order type is designed to ensure that the investor does not receive a partial fill that would not suit his current appetite. Failure to fill the entire order upon immediate submission to the market causes the system to cancel the order in its entirety.

*backtrader* tries to offer a realistic approach. The statement above can only be filled if you are operating with **tick data**, because that would be the only possible way to ensure that a `Fill or Kill` order is either *filled* or immediately *killed* if a *partial match* would be received.

Corollary: *Real volume matching does only make sense when working with tick data*

Taking that into account, the following was added to the decision:

  - *Do not trade markets which are not liquid enough to immediately fully absorb an order*

With all that in mind, the % based approach to limit volume usage of a bar for order matching wouldn't hurt and as such I think it can get a try.

> If not, I am willing to write a class that adds that functionality.

This wouldn't be a class but part of the existing matching logic of the *broker*. The *broker* can (and does with live feeds) report partial executions and this would simply be the case: *a partial execution*

**Comment by dafyddd** [comment]
My trading strategy is a liquidity adding trading strategy, and it requires that I trade in some low liquidity markets. I use only limit orders and sometimes hit the high/low of the next bar. 

I was able to modify the execution logic in the Broker class to set partial fill size to be a function of my limit price, volume weighted average price, high and low price. I did not create a proper subclass to do this, because that would require me to modify more of the internal working of Backtrader. I don't think my modification will be of much use to anyone.

But if anybody's interested, my new broker class 
[custom_broker.txt](https://github.com/mementum/backtrader/files/362097/custom_broker.txt)

**Comment by mementum** [comment]
Support is being added in a generic manner

**Comment by mementum** [comment]
Added to the documentation and with sample runs in this post:

  - http://www.backtrader.com/posts/2016-07-14-volume-filling/volume-filling/

**Comment by mementum** [comment]
Small update to consider the order side for the value returned by a volume filler (which has to be >= 0) for the internal of backtrader.

Pushed as release 1.5.3.93
