### ISSUE TITLE
Plotting Documentation Missing

### ISSUE THREAD

**Issue by dafyddd** [mementum/backtrader#109]
I've looked everywhere and can't find the documentation for the plotting feature that you have. It's empty on the documentation website: http://backtrader.readthedocs.io/en/latest/plotting.html

I am specifically wondering which files I should go to to modify the plotting behavior. If there is any partial execution of an order, the profit and loss array stops updating and I get the graph pictured below. I can fix this issue, but it's somewhat confusing going through the plot() function inside Cerebro to find each component graph.

![figure_0](https://cloud.githubusercontent.com/assets/17482744/16818802/94be53b6-4917-11e6-9c1c-9467b9e2bb3b.png)

**Comment by mementum** [comment]
Yes indeed. The documentation for plotting is the major absence (a couple other things are either missing or poorly documented, but this is the major)

The "plotting" objects don't actually exist. The `lines` of the objects are plotted. So if something is broken is not the plotting but rather in what the `Trades` observer is observing.

Up until now *partial executions* were supported in the broker but were not happening, because volume was not being taken into account. With the new volume fillers, partial executions can actually happen.

The `Observers` in the default plotting were made without considering the existence of *partial execution* and may need adjustment.

To be looked into.

**Comment by mementum** [comment]
Even with partial executions implemented the standard `observers` work. A small correction to the new partial execution was needed to consider the order side for the value returned by a volume filler.

The sample for it has been update with a chart which shows the observers working.

  - http://www.backtrader.com/posts/2016-07-14-volume-filling/volume-filling/

The failure may have been in your own implementation of partial executions. The chart is below

![](http://www.backtrader.com/_images/volumefilling1.png)

**Comment by mementum** [comment]
Documented in 1.6.1.93
