### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#115]
Hello DRo,

Quick question, I have now a better picture on how I can use bt.

Can you confirm what is the best to trade LIVE with the same strategy on multiple preselected symbols  ?

Shall I create my list of symbols and run the strategy on each one and depending on the timeframe the strategy will handle orders ?

Is it possible to run the script 5 minutes before LIVE and it will start when data.LIVE is received ?

Thanks for your help.

Kind regards,
Remi

**Comment by mementum** [comment]
> Can you confirm what is the best to trade LIVE with the same strategy on multiple preselected symbols ?

Although the code in the 2 live data feeds is theoretically prepared for that, it has only been tested with a single symbol. It may even break with more than one.

Having *many symbols* and scanning for signals and choosing one seems to be a topic for many, but it is not really the focus of *backtrader*.

Rather than having an internal loop which kicks in every *x period-seconds* to synchronize the data received by feeds, *backtrader* features a *master data* and *slaves datas*.

The system blocks on the the *master* data until it receives something from it. The other datas are then queried for data. In the case of pre-canned data this is a perfect way to synchronize data from different sources.

This *master-slave* approach makes the system inherently biased to single data unless the *slave-datas* can produce data in the background, before being queried. This is theoretically the approach of the live datas, but it would need to be tested.

Until then it wouldn't be recommended to try it with more than 1 data.

**Comment by mementum** [comment]
> Is it possible to run the script 5 minutes before LIVE and it will start when data.LIVE is received ?

No, unless you happen to synchronize the start of your script with the time of the market start minus 5 minutes.

*data.LIVE* is a signal that the data being fed to the strategy is actually real-time and not the product of backfilling or delayed because the server has suffered a disconnection/reconnection cycle.  It is not an indication that the orders will be executed *LIVE*.

If the previous 5 minutes are needed to generate signals from indicators, backfilling is available.

**Comment by mementum** [comment]
Tested with the IB data feed and it was actually breaking with 2 datas due to how the data loading was kickstarted.  Reordering the kickstarting has not proven to be a real challenge and things work.

But the *master* vs *slave* issue kicks in. Due to the blocking part if a data has low liquidity and the timeframe is small, the slave data may become out of sync with the main data. This is because the two datas will produce data that will be resampled into different periods.

Example:
  - The *master* data produces a "1 second" bar after 3 seconds.
  - The *slave* data produces 3 "1 second" bars after 3 seconds

The system asks the *master* to return a data and if available, asks the *slave* to return a data. But this data is the 1st of the 3 bars it has generated. And this is already behind the *master* which due to the low liquidity has taken 3 seconds to generate the 1st 1 second bar.

See the following quick example:

```
$ ./ibtest.py --port 7497 --data0 TWTR --data1 AAPL-STK-SMART-USD --resample --timeframe Seconds --compression 1 --no-backfill_start
Server Version: 76
TWS Time at connection:20160801 22:20:30 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Timezone from ContractDetails: EST5EDT
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:ibdemo>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:demohmds>
***** DATA NOTIF: CONNECTED
***** DATA NOTIF: DELAYED
***** DATA NOTIF: CONNECTED
***** DATA NOTIF: DELAYED
***** DATA NOTIF: LIVE
***** DATA NOTIF: LIVE
Data0, 0001, 2016-08-01T16:20:31.000000, 16.6, 16.6, 16.6, 16.6, 353.0, 0, nan
Data1, 0001, 2016-08-01T16:20:31.000000, 104.54, 104.54, 104.54, 104.54, 85.0, 0, nan
Data0, 0002, 2016-08-01T16:20:32.000000, 16.6, 16.6, 16.6, 16.6, 15.0, 0, nan
Data1, 0002, 2016-08-01T16:20:32.000000, 104.56, 104.56, 104.56, 104.56, 1.0, 0, nan
Data0, 0003, 2016-08-01T16:20:33.000000, 16.61, 16.61, 16.61, 16.61, 3.0, 0, nan
Data1, 0002, 2016-08-01T16:20:32.000000, 104.56, 104.56, 104.56, 104.56, 1.0, 0, nan
Data0, 0004, 2016-08-01T16:20:34.000000, 16.6, 16.6, 16.6, 16.6, 2.0, 0, nan
Data1, 0003, 2016-08-01T16:20:34.000000, 104.55, 104.55, 104.55, 104.55, 9.0, 0, nan
```

Already at `16:20:33` sync is lost. In this case the *slave* has also undergone a period of low liquidity and it re-syncs 1 second later. But it could have remained out of sync forever, even increasing the difference.

But this is a false sync. Notice how the "length" of the datas is different in the las 2 line:

  - `0004` vs `0003`

If the loss of sync happened because the slave were always producing more bars, the problem could be solved by merging all available bars into a single one. But the problem when the slave produces too few bars cannot be solved, because there is no data.

The sample run above uses a small timeframe of `Seconds 1`. In larger timeframes, but still small in absolute terms, like 30 seconds, 1 minutes is unlikely to be seen unless the assets really have a very low low liquidity.

With the changes in place and testing against the "demo" of IB, which has low liquidity for everything, no out-of-sync sequences have been seen. But here you rmileage may vary always depending on your target timeframe and asset liquidty.

The changes will be tested a bit longer and most probably be pushed tomorrow

**Comment by mementum** [comment]
Tested and pushed the changes as 1.8.1.93. Extra workarounds were needed to make sure that if different timeframes are used the larger timeframes are not pulled too early (subday timeframes), because the *master* data is delivering and requesting the other datas to deliver.

As expected and with the *IB Demo* as reference, which is already a low liquidity provider, tests below `Seconds 15` as the timeframe have a tendency to de-synchronize the data (the 2nd data being the one with lower liquidity). Tests with `Seconds 30` and above have kept the data well synchronized in minutes long runs. `Seconds 15` seems to be the limit which sometimes runs well and sometimes doesn't, using `TWR` (data0) and `APPL` (data1)

In any case the design which was used for *backtesting* allowing easy synchronization of data has probably already been stretched beyond maximum and further modifications may be do more bad than good. Not a thought following this discussion, but an already existing one.

**NOTE**
You may use a trick to have the script running *5 minutes* and doing nothing even if the platform has already reported `data.LIVE`.

  - Add a simple moving average for control purposes.
  - Give it a period long enough to cover 5 minutes with the selected timeframe (example: period 10 for a timeframe of 30 seconds)
  - `next` in the strategy will be 1st called when the moving average produces meaningful data, in this case after 5 minutes.

**Comment by remroc** [comment]
Hello DRo,

Thanks for your answers and the push. 

I will give it a try today with the `Seconds 30` and 5 symbols :) 

I will let you know...

**Comment by mementum** [comment]
One of the things that went into the release, as mentioned above, is to make sure datas of different timeframes deliver at the same time. Data feeds are based on *ticks* and knowing if a *resampled* bar is over or not depends on the next incoming tick.

To overcome this the code already included a *time based* check that delivers a *resampled* bar when the time has gone over the boundary of what would be the resampled bar (*IB* notifies of the time difference with the server to allow for a correct calculation of where the boundary really is)

The code wakes up to make checks and deliver a resampled bar if the time boundary has been exceeded even if no tick for the new period has yet been seen. The "waking up" is controlled by Python/Operating System and the timings are good but can create an out of sync problem.

As such and to avoid it, *slave* datas are given a 2nd chance with an extra check if they have nothing to deliver yet, but the *master* is already delivering.

This is a sample run with the *IB Demo* with `TWTR` and `AAPL` working together with timeframes of `(Seconds, 15)` and `(Seconds 30)`

```
$ ./ibtest.py --port 7497 --data0 TWTR --data1 AAPL-STK-SMART-USD --resample --timeframe Seconds --compression 15 --no-backfill_start --timeframe1 Seconds --compression1 30
Server Version: 76
TWS Time at connection:20160802 09:33:14 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Timezone from ContractDetails: EST5EDT
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:ibdemo>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:demohmds>
***** DATA NOTIF: CONNECTED
***** DATA NOTIF: DELAYED
***** DATA NOTIF: CONNECTED
***** DATA NOTIF: DELAYED
***** DATA NOTIF: LIVE
***** DATA NOTIF: LIVE
Data0, 0001, 2016-08-02T03:33:30.000000, 16.7, 16.71, 16.69, 16.7, 39.0, 0, nan
Data1, 0001, 2016-08-02T03:33:30.000000, 103.89, 103.93, 103.88, 103.93, 12.0, 0, nan
Data0, 0002, 2016-08-02T03:33:45.000000, 16.69, 16.72, 16.69, 16.7, 25.0, 0, nan
Data1, 0001, 2016-08-02T03:33:30.000000, 103.89, 103.93, 103.88, 103.93, 12.0, 0, nan
Data0, 0003, 2016-08-02T03:34:00.000000, 16.7, 16.71, 16.69, 16.69, 19.0, 0, nan
Data1, 0002, 2016-08-02T03:34:00.000000, 103.93, 103.94, 103.91, 103.93, 31.0, 0, nan
Data0, 0004, 2016-08-02T03:34:15.000000, 16.7, 16.71, 16.67, 16.68, 26.0, 0, nan
Data1, 0002, 2016-08-02T03:34:00.000000, 103.93, 103.94, 103.91, 103.93, 31.0, 0, nan
Data0, 0005, 2016-08-02T03:34:30.000000, 16.69, 16.7, 16.67, 16.68, 27.0, 0, 16.69
Data1, 0003, 2016-08-02T03:34:30.000000, 103.94, 103.96, 103.93, 103.93, 24.0, 0, nan
```

You can even do the same by passing `TWTR` twice and it will still run, once with `15` seconds resampling and once with `30 Seconds` resampling as in:

```
$ ./ibtest.py --port 7497 --data0 TWTR --data1 TWTR --resample --timeframe Seconds --compression 15 --no-backfill_start --timeframe1 Seconds --compression1 30
Server Version: 76
TWS Time at connection:20160802 09:48:34 CET
--------------------------------------------------
Strategy Created
--------------------------------------------------
Timezone from ContractDetails: EST5EDT
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=2104, errorMsg=Market data farm connection is OK:ibdemo>
***** STORE NOTIF: <error id=-1, errorCode=2106, errorMsg=HMDS data farm connection is OK:demohmds>
***** DATA NOTIF: CONNECTED
***** DATA NOTIF: DELAYED
***** DATA NOTIF: LIVE
Data0, 0001, 2016-08-02T03:48:45.000000, 16.61, 16.63, 16.61, 16.62, 10.0, 0, nan
Data0, 0002, 2016-08-02T03:49:00.000000, 16.61, 16.62, 16.6, 16.62, 104.0, 0, nan
Data1, 0001, 2016-08-02T07:49:00.000000, 16.61, 16.63, 16.61, 16.62, 10.0, 0, nan
Data0, 0003, 2016-08-02T03:49:15.000000, 16.62, 16.63, 16.61, 16.62, 87.0, 0, nan
Data1, 0001, 2016-08-02T07:49:00.000000, 16.61, 16.63, 16.61, 16.62, 10.0, 0, nan
Data0, 0004, 2016-08-02T03:49:30.000000, 16.63, 16.64, 16.61, 16.63, 92.0, 0, nan
Data1, 0002, 2016-08-02T07:49:30.000000, 16.62, 16.63, 16.61, 16.62, 174.0, 0, nan
Data0, 0005, 2016-08-02T03:49:45.000000, 16.64, 16.67, 16.63, 16.64, 91.0, 0, 16.626
Data1, 0002, 2016-08-02T07:49:30.000000, 16.62, 16.63, 16.61, 16.62, 174.0, 0, nan
```

This allows operating on the same asset considering 2 different timeframes.

**NOTE**: In the case of different timeframes, and unlike in the out-sync-case from above, the different length of the datas is not only expected: *IT MUST BE*, because they have different clock speeds and the indicators that operate on these *datas* operate on the exact amount of available data.

**Comment by remroc** [comment]
Hello DRo,

Thanks a bunch for your answer.

Here are my results so far : 
 1/ I have tested the provided ibtest sample and it worked well with resample above Seconds 15.
2/ Then, I have added a panda dataframe with my list of symbol to trade. This list_of_symbols is then added to the strategy.
3/ Next step was to change the next function of the strategy. Goal is to read each symbol of list_of_symbol and perform the bracket order on it. 
3.1/ As I want to follow each symbol individually, I am trying to have an orderid list dedicated to each symbol
3.2/ Same for datastatus and the position

Work is in progress, it seems a little bit complicated to handle all those symbols without doing the if data1 is not None, data2 is not None, data3 is not None.

I think I might reach goal by end of week if keep the pace...

Your suggestions are more than welcome.

Thanks,

Remi

**Comment by remroc** [comment]
Hello DRo,

How to get the symbol from data variable sent to notify_data() as I want to set datastatus to the correct symbol ?

```
    def notify_data(self, data, status, *args, **kwargs):
        print('*' * 5, 'DATA NOTIF:', data._getstatusname(status), *args)
        if status == data.LIVE:
            self.counttostop = self.p.stopafter
            self.datastatus = 1
```

Many thanks,

Remi

**Comment by mementum** [comment]
All `data` feeds have basic parameters. One of them is the `dataname` which is the actual symbol. This use was not yet taken into account ... and hence the fact that this parameter in the case of *resampling/replaying* is no longer the symbol but actually the `data` which is being *resampled/replayed*.

This really deserves a small patch. Meanwhile you could do something like

```python
dataname = data.p.dataname  # or the full version data.params.dataname
if not isinstance(dataname, backtrader.utils.py3.string_types):
    dataname = dataname.p.dataname
```

This undoes the implied recursion of *resampling/replying*

**Comment by mementum** [comment]
Synchronization has been reworked with release 1.9.0.99. The tests run with the IB data feed have far better than before and the datas have resynchronized (tested down to 5 seconds resampling) when one of the datas failed to negotiate during the next 5, 10 seconds
