### ISSUE TITLE
Pyfolio not providing same results as other Analyzers

### ISSUE THREAD

**Issue by ericbrown** [mementum/backtrader#116]
Using intraday data, I'm seeing the pyfolio analyzer deliver different analysis than the other analyzers (and different than my own manual calculations).

For example, I have an intraday strategy. The analyzers (and manual calculations) show the following results.
![screenshot 2016-08-05 15 24 39](https://cloud.githubusercontent.com/assets/449599/17449542/e056ae8e-5b20-11e6-9774-3711751838c2.png)

When I run the pyfolio analysis, I get completely different results.  

![screenshot 2016-08-05 15 27 29](https://cloud.githubusercontent.com/assets/449599/17449585/28610b0c-5b21-11e6-944f-729eb3809d07.png)

As you can see, the stats don't match up. Additionally, there are no short trades taken...this is a long-only strategy.

Using the pyfolio analysis on daily/weekly/month strats seems to work fine. Are there any special parameters / settings I need to pass into the pyfolio analyzer to get it to work correctly on intraday data?

I can share my data if you need to troubleshoot.

**Comment by mementum** [comment]
Given that the very naive assumption of the author was that *pyfolio* would be used on *daily* and larger timeframes, there was obviously no test run on intraday data.

Looking into it.

Only one question: which specific timeframe/compression have you used?

P.S. 3.64% per year is a nice figure after a 9 year backtesting run.

**Comment by ericbrown** [comment]
Thanks. I was assuming the issue was Pyfolio's assumption of daily and larger timeframes.

This is using 30 minute data.

**Comment by mementum** [comment]
It has been impossible to reproduce the scenario from above in which `pyfolio` believes that some trades are short in a long-only strategy.

But putting it to work with intraday data (30 min too) has shown that the sub-day implementation had several points with room for improvement.

The naive assumption from above, *daily data* was based on the fact that pyfolio seems to offer *daily* as the lowest level of resolution for the analysis output and anything below that is *resampled*. The latter not having been taken into account.

The major area of incompatibility here, due to the naive assumption, is that the output for the pyfolio specific analyzers considers the larger timeframe for data storage, without taking into account that it will be called several in the smaller timeframe, effectively losing most of the output and in some cases all.

In the case of *transactions*, the storage was being overwritten for each 30 minute bar and unless the last 30 minute bar of the day happened to be one with a transaction, then the amount of transactions for the given day would be empty.

In the test case (3 years of 3 minute data) the *Annual Return* provided by both *backtrader* and *pyfolio* (regardless of timeframe) has been a match and that's the puzzling thing with regards to the scenario depicted above.

In any case the changes to properly support the smaller timeframes giving *pyfiolio* the right will be polished along the day, re-tested and pushed, which I hope will also cure the problems from above.

**Comment by ericbrown** [comment]
Thank you. I'll keep an eye out for changes.  

Also, can you provide a sample setup call for pyfolio (showing timeframe and compression) included in the call for the analyzer (e.g., . cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio', timframe="" compress="")?  This would help me ensure I'm setting up the analyzer correctly on my end.

**Comment by mementum** [comment]
After having looked again at *pyfolio* today, the reports seem to focus on *daily* and larger timeframes for the analysis. And I say *seem* because I haven't looked into every possibility and it might be that one could get reports with intraday statistics.

*pyfolio* does internally *resample* anything you pass to it. It is, today, visible even without looking at the source code because there is a deprecation warning about the resampling method used inside the python notebook.  And because of this resampling it shouldn't matter it you pass intraday data to it, because it will be upsampled to at least daily.

In the test I ran earlier today, the modifications I made kept, for example, the *transactions* with the full *datetime* information, i.e: a 30 minute timestamp. The report generated later by *pyfolio* had *daily returns* and *annual returns*.

I did test using

  - `cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio', timeframe=bt.TimeFrame.Days)`

and

  - cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio', timframe=bt.TimeFrame.Years)`.

But the *daily* nature of the *pyfolio* report and the *resampling* suggest that the best approach would be:

  - `timeframe=bt.TimeFrame.Days`

  - Keep the timestamps as they are originally seen in the data stream and rely on the *resampling* performed by pyfolio itself.

**Comment by mementum** [comment]
And after much testing it seems a conundrum has been hit. For example: with a timeframe of 30 minutes, my market of choice has 28 bars. That gives plenty of room for being in and out of the market. *Gross Leverage* can be taken as a example.

*pyfolio* displays results for in daily terms but half of the day the strategy can have a non-null leverage (in the market) and the other half a null leverage (out of the market) The question here is what is actually the *gross leverage*. Because the strategy may enter/exit several times the market each day (with 28 bars available) and with different *leverages* each time.

The most obvious approach here seems to offer some kind of weighted moving average for the 28 bars. But this seems to defeat the purpose of the statistic, because the highest *leverage* gets diluted by the many bars, during which the strategy wasn't in the market.

In this case it would seem to take the *maximum* of the leverage of the day.

The same happens with another of the inputs to *pyfolio*: *Position Value*. Because an intraday strategy can open and close a position several times during the day. What is the info for *pyfolio* if a position is opened and closed within the same trading day?

**Comment by mementum** [comment]
And following this I found the following ticket in pyfolio: 

  - https://github.com/quantopian/pyfolio/issues/144

> @humdings David, yep, I think it's as simple to drop the cash as well. Since we don't really support any intraday analysis (yet) in pyfolio, I think its safe to just get it working at daily frequency for now

A good reason for some of the things not working at all when passing intraday statistics to *pyfolio*.

I will clean up the corrections I made to my own mistakes and try to cover as many use cases as possible, but *pyfolio* intraday support will be needed to fully support your scenario.

**Comment by ericbrown** [comment]
Thanks for looking into this. I'll just hold off on using pyfolio on intraday data.

Thanks again!

**Comment by mementum** [comment]
This has helped to bring pyfolio and associated children analyzers up to the right level. With the changes introduced in 1.8.3.93 the children analyzer *should* be ready for intraday support in pyfolio, because now a full datetime timestamp is used. *Positions* makes an exception in the code because the others don't break *pyfolio*, but it seems that providing a datetime, instead of a date, timestamp breaks something inside pyfolio. A check is made and if the timeframe is daily or greatet, *date* will simply be used.

The default in the *pyfolio* analyzer has also been set to (Days, 1) following the deeper look into the actual expectations/output which *pyfolio* makes/delivers. There should be no need in general to change that default.
