### ISSUE TITLE
reqmktdata or reqrealtimebar for a strategy based on 5 minutes

### ISSUE THREAD

**Issue by 4ever911** [mementum/backtrader#117]
I want to create a auto trading software, i wonder which data should i choose.

I can get more details by using tick data, however, since they are just snapshots, so we may lost some of the data in some certain conditions, say extreme sell off...etc. 

I guess maybe realtimebar may works better for me if my strategy is based on 5 minutes?

**Comment by mementum** [comment]
Bewar because your own mileage may vary, but following experimentation it seems that ``mktData`` and ``realTimeBar`` end up containing the same information. The IB documentation states that ``realTimeBar`` is actually exact historical data down to a 5 second bar.  Even if `mktData` does usually work fine it could actually fail to deliver as IB makes no explicit promise for it.

Given you are upsampling to *5 minutes*, the actual *tick data* delivered by `mktData` should play no role in chaning the outcome of the strategy's logic.
