### ISSUE TITLE
Quickstart/Let's Optimize example issue

### ISSUE THREAD

**Issue by cnimativ** [mementum/backtrader#118]
Hi all,

I am walking through your doc/Quickstart and get stuck on the Let's Optimize part of the tutorial. The console is frozen with the following error.  I am running 64bit Anaconda3 and Python 35 using Spyder for IDE on a Intel i7 Windows 10 64bit box. 

What might be the cause of this problem?

Thanks in advance for the help!

`runfile('C:/Python35/User/backtrader_example_sma.py', wdir='C:/Python35/User')
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 429, in _handle_results
    task = get()
  File "C:\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'TestStrategy' on <module '__main__' (<_frozen_importlib_external.SourceFileLoader object at 0x00000206BF350400>)>`

**Comment by mementum** [comment]
This is run executed right now:

```
xxx@aaa-bbbb ~/src/backtrader/docs/quickstart (winpy64-3.5/inno)
$ ./quickstart11.py
2000-12-29, (MA Period 13) Ending Value 893.90
2000-12-29, (MA Period 23) Ending Value 1023.00
2000-12-29, (MA Period 17) Ending Value 949.80
2000-12-29, (MA Period 25) Ending Value 1013.30
2000-12-29, (MA Period 16) Ending Value 959.40
2000-12-29, (MA Period 24) Ending Value 1020.10
2000-12-29, (MA Period 14) Ending Value 896.90
2000-12-29, (MA Period 18) Ending Value 1011.90
2000-12-29, (MA Period 26) Ending Value 998.30
2000-12-29, (MA Period 12) Ending Value 830.30
2000-12-29, (MA Period 19) Ending Value 1041.90
2000-12-29, (MA Period 27) Ending Value 982.20
2000-12-29, (MA Period 11) Ending Value 880.00
2000-12-29, (MA Period 20) Ending Value 1078.00
2000-12-29, (MA Period 28) Ending Value 975.70
2000-12-29, (MA Period 10) Ending Value 880.30
2000-12-29, (MA Period 21) Ending Value 1058.80
2000-12-29, (MA Period 29) Ending Value 983.30
2000-12-29, (MA Period 15) Ending Value 973.90
2000-12-29, (MA Period 22) Ending Value 1061.50
2000-12-29, (MA Period 30) Ending Value 979.80
```

Python 3.5 as you see in the shell prompt. The results (period-wise) are out of order because the runs were scheduled to different processors by the internals of `multiprocessing`

I don't know how your setup looks like, but the likely culprit is shown in the traces: `_frozen_importlib_external.SourceFileLoader`

It seems this is being run from a *frozen* application and an educated guess would be that things have not been properly frozen.

**Comment by cnimativ** [comment]
Got it.  Just tested with running execute 'python quickstart11.py' using Windows 10 command prompt and get the same result as you did.

But running the script in Spyder still gets me the same error.

Weird.

**Comment by mementum** [comment]
You may google for problems with the `notebook` (*jupyter* or by the old name *ipython*) and problems with `multiprocessing` under Windows.

The reason is here: https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support

It seems the `notebook` has been *frozen* in some other way, because even if you add `freeze_support`to the script it will fail.

**Comment by mementum** [comment]
Furthermore the exact reason of the failure is given in the docs:

> Note Functionality within this package requires that the __main__ module be importable by the children. This is covered in Programming guidelines however it is worth pointing out here. This means that some examples, such as the Pool examples will not work in the interactive interpreter.

(Also in the documentation for `multiprocessing`)

**Comment by cnimativ** [comment]
Yes, its interesting how quickstart11.py can be executed without any problem under Windows command prompt but freezes in Spyder/IPython console.  Adding freeze_support() does not help inside Spyder/IPython console.  Couldn't find any answer on Stackoverflow or IPython documentation. 

On another note, 
```
import threading
threading.activeCount()

```returns 5.

**Comment by mementum** [comment]
Sorry but it is **NOT** interesting. It will simply not work. In spite of the documentation bits I quoted from above you can see there are several reference around the Internet documenting the problems of *IPython/Jupyter* and *Spyder* with `multiprocessing`.  A very quick search:

  - https://github.com/spyder-ide/spyder/issues/1900
  - http://stackoverflow.com/questions/23641475/multiprocessing-working-in-python-but-not-in-ipython
  - https://groups.google.com/forum/#!topic/spyderlib/LP5d8QZTXd0

It is obvious the problem is in the aforementioned tools and the way the Python *kernel* (name used in *Jupyter*) is managed and how scripts are passed to it.

An educated guess would be that  `freeze_support` doesn't work because the *kernel* has been started interactively and it doesn't matter if you invoke `freeze_support`, because it has to be done before anything, but unfortunately the kernel has already been started and is doing things. This makes the *kernel* always be in *interpreted mode* which collides with the `multiprocessing` module.
