### ISSUE TITLE
Include credit trading fees

### ISSUE THREAD

**Issue by li-dp** [mementum/backtrader#125]
Hi @mementum,

When short stock, ie. credit trading, I will be charged by my broker.
The fees is calculated in this way:
If I short stock in Jun 1, buy back at Aug 1, and the credit interest is 10% per year.
For each day between Jun 1 and Aug 1, I have to pay:  stock price * volume * 10% / 365 in **cash**.

When do a pair trading, this part of cost is crucial to find out whether a trade is profitable.

**Comment by mementum** [comment]
As described it seems like a regular broker would operate:

  - You have a short position with the broker
  - The broker detracts money from your account

This would be doable with an open interface but the question is:

  - How does this help to identify if a `trade` is profitable?

Because the money is taken from the account and such deduction is not tied to *orders*.

**Comment by mementum** [comment]
http://www.backtrader.com/posts/2016-08-22-credit-interest/credit-interest/
