### ISSUE TITLE
running low?

### ISSUE THREAD

**Issue by 4ever911** [mementum/backtrader#135]
I am trying to test a large database ( 500,000 + records,IMO it's not that big)

It takes so much time, even if my strategy is empty, i.e, do nothing, just go through the data.

The program spends 1 hours on loading dataframe into backtrader feeds, yet another hour on  onbar() function, and the strategy never returns...

here is my database, it's a pandas hdf file
[Forex.hdf.zip](https://github.com/mementum/backtrader/files/444068/Forex.hdf.zip)

**Comment by mementum** [comment]
The problem is *preloading*, because the entire dataset is first loaded in memory. Execution doesn't take place until then.

In order to keep the project as *pure* Python as possible the internal memory storage buffer is `array.array`and the problem being experienced here is the continuous *reallocation*.

The options are:

  - Disable `preload` in `cerebro`

     `cerebro = bt.Cerebro(preload=False)` or `cerebro.run(preload=False)`

  - Use `exactbars` to decrease memory usage (and automatically disable `preload`)

     The docs: http://backtrader.readthedocs.io/en/latest/cerebro.html

     If you have no interest in *plotting* I would recommend `exactbars=0`

     This reduces all buffers to the bare minimum and removes any memory *reallocation* problems you may experience.

**Comment by mementum** [comment]
I updated the comment above to indicate that the proper value for `exactbars` when no interest in plotting is there is `exactbars=1`  (as clearly pointed out in the docs)

Not only code has typos

**Comment by GuyResh** [comment]
For folks with access to "beefy" hardware (e.g. multi-CPU/core with 32GB-256GB RAM), I can see a potential benefit for supporting pre-loading "once" into shared memory somehow and simply checking if it  was previously loaded thus reducing time for this step even further (it's on my TODO anyway :)).

**Comment by mementum** [comment]
Check release `1.8.12.99`. It optimized data preloading in the scenario described and has also added an optimization in what's returned.

http://www.backtrader.com/posts/2016-09-05-optimization-improvements/optimization-improvements/

**Comment by mementum** [comment]
In release 1.9.0.99 there is a very small code patch which removes a bug which for all intent and purposes was silent and invisible, because everything was working "fine".

Bars were being reprocessed once again after being loaded. This has no major impact (relative) with daily bars, but it has for sure a large CPU impact for large amounts of intraday bars.

Hoppefully the situation is better now.
