### ISSUE TITLE
How to extract results properly

### ISSUE THREAD

**Issue by drSeeS** [mementum/backtrader#139]
Please bear with me if I just overlooked it in the docs, couldn't find it though:
After running a backtest, how do you properly extract all the goodies from cerebro's result object (i.e., dates with respective positions, equity over time, draw down over time, open and closing dates for each of your positions, payed comission over time, etc.).  Thanks!

**Comment by mementum** [comment]
This was already stated in another ticket ... and is probably the weakest part, still, backtrader has.

The collection is meant to be done via *Analyzers* or *Observers*.

  - *Analyzers* make a summary of what they have seen (like for example after seeing returns, calculation of the *Sharpe Ratio*)

  - *Observers* write down a value for each bar. The `Broker` observer keeps track of `cash` and portfolio `value` reported by the broker at the beginning of each `next` cycle (effectively each bar)

    There is also a `DrawDown` observer which keeps the actual *drawdown* level and also the *maxdrawdown* ever reached.

A *cerebro* instance returns a list of the *strategies* that were run in the system. In most cases there will probably only be one.

This strategy has member attributes:

  - `observers`
  - `analyzers`

And even

  - `indicators` if you were in need of looking into the values

The `open` and `closing` dates for each of your positions is kept in `Trades`, which are notified over `notify_trade` to the strategy. There is also a member attribute in the *strategy* called `_trades`, because it was never expected someone would be accessing it.

The default configuration adds:

  - A `Broker` observer to keep `cash` and `value`
  - A `BuySell` observer to record `buy` and `sell` points
  - A `Trades` observer to show PnL for each closed trade

But the structure to recover statistics could probably be improved with the addition of other *Observers*/*Analyzers* more focused on specific tasks.

**Comment by drSeeS** [comment]
Thanks, perfect, will have a closer look!

**Comment by mementum** [comment]
Forgot to say that to integrate `pyfolio` 3 specific *Analyzers* were created. They are specifically tailored to match the requirements but offer some of the insights:

  - `GrossLeverate`
  - `Positions`
  - `Transactions`

The 4th analyzer used in the `pyfolio` analyzer is the already pre-existing `TimeReturn`
