### ISSUE TITLE
[Enhancement?] Empyrical library

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#147]
Hi,

I am reviewing the method to calculate drawdown and maybe it is a good idea to use the formula of empyrical library. Also others ratio could be added such as calmar ratio....

http://quantopian.github.io/empyrical/_modules/empyrical/stats.html

``` python
def max_drawdown(returns):
 if len(returns) < 1:
        return np.nan

    cumulative = cum_returns(returns, starting_value=100)
    max_return = cumulative.cummax()
    return cumulative.sub(max_return).div(max_return).min()

where cum_returns(returns):
Notes
    -----
    For increased numerical accuracy, convert input to log returns
    where it is possible to sum instead of multiplying.
    PI((1+r_i)) - 1 = exp(ln(PI(1+r_i)))     # x = exp(ln(x))
                    = exp(SIGMA(ln(1+r_i))   # ln(a*b) = ln(a) + ln(b)
df_cum = np.exp(np.log1p(returns).cumsum())
```

Rgds,
JJ

**Comment by mementum** [comment]
The `drawdown` and `maxdrawdown` values are accessible through the `DrawDown` observer. It could be made into an analyzer though.

  - http://backtrader.readthedocs.io/en/latest/observers-reference.html#drawdown

For cumulative returns you have the `Returns` analyzer

  - http://backtrader.readthedocs.io/en/latest/analyzers-reference.html#returns

Logarithmic calculation is already used, but there is no need to sum. Just the initial and end value are needed because most of the terms cancel each other out (divisions become substractions)
