### ISSUE TITLE
Indicator Buy on dips or Sell on rips

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#160]
Hi,

I am trying to program these rules:

```
Indicator->Stochastic(40,3,3,Simple)

BoD (Buy on dips)=CrossUp(Indicator,30) or CrossUp(Indicator,70)
SoR (Sell on rips)=CrossDown(Indicator,70) or CrossDown(Indicator,30)

TradePref=IF(BarsSince(BoD) < BarsSince(SoR),  1, BarsSince(BoD) > BarsSince(SoR), -1,0))
```
BarsSince is the number of bars since X is True, So i can know the status: Buy on dips or Sell on rips

I don´t know what is the best way to know the status, perhaps there is another way instead counting bars.

Rgds,

JJ

**Comment by junajo10** [comment]
could it be a good solution?

from . import Indicator


class BarsSince(Indicator):
    params = (('function', None),)

    lines = ('barsSince',)

    def __init__(self):        
        super(BarsSince, self).__init__()
        
    def next(self):
        print(self.params.function[0])
        if self.params.function[0]==1:
            self.lines.barsSince[0]=0
        else:
            self.lines.barsSince[0]=self.lines.barsSince[-1]+1

**Comment by mementum** [comment]
That's a possible approach. But it has an inherent problem: the initial value and the minimum period.

You look back with `[-1]` and that means `next` cannot be called until at least one other value has been put  there.

And you need to put some initial value there, because if not, the system fills the values automatically with `NaN` and `NaN + 1 = NaN`

Your best bets:

  - Subclass from `backtrader.indicators.PeriodN` which already carries a `period` parameter and knows how to pass this information to the system.

    Change the value of the parameter `period` (default is `1`) to at least `2`. Or larger if you need a larger warm-up for your function.

  - Fill the array with default values (probably `0`) in the `prenext` method

**Comment by junajo10** [comment]
Thanks a lot.

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from . import PeriodN

class BarsSince(PeriodN):

    lines = ('barsSince',)
    params = (('period', 2),)
     
    def init(self):
        super(BarsSince, self).init()
        
    def prenext(self):
        self.lines.barsSince[0]=0     
        
    def next(self):
        if self.data0[0]==1:
            self.lines.barsSince[0]=0
        else:
            self.lines.barsSince[0]=self.lines.barsSince[-1]+1

**Comment by mementum** [comment]
Of course the nature of the values in `self.data` is unknown (more `1s` than `0s` or vice versa) to understand which value would actually be output when `next` is called.

If `1s` is the odd one out, the code would start counting since the 1st call to `next` and this would lead to believe a *dip* (or a *rip* has happened)

**Comment by junajo10** [comment]
Thanks a lot, it is working well .

Rgds,

JJ
