### ISSUE TITLE
PnL observer gross/set does not include interest charge

### ISSUE THREAD

**Issue by xnox** [mementum/backtrader#163]
I have setup commission as: `cerebro.broker.setcommission(commission=0, margin=1020, mult=10.0, interest_long=True, interest=0.0275)`

And my pnl has gross & net are the same, however, the introduction of interest did lower my end value. My guess is that PnL observer does not count interest charged as a loss.

**Comment by mementum** [comment]
The observer is just observing. In this case the *trades*. And the trades are calculated by looking at the orders.

The *interest* is not part of any *order* and that's why it is not being taken into account for the calculation of the trades. Part of the reasoning is that trades with different *tradeid* may be made on the same asset and overlap. But the *interest* is charged on the global position of an asset.

If the broker emits an event, which could be kind of simulated order, for the interest charge on a position, the question here would be which strategy is bound to receive it. Because the system can support several strategies running at once and any of the strategies my operate simultaneously on the same asset. A *global* event would lead all strategies operating on the asset to believe that the entire *interest* has to apply to open trades launched from it, and the interest would actually be taken into account several times.

It is much more a conceptual topic to solve than a technical one.

**Comment by mementum** [comment]
will be in next release
