### ISSUE TITLE
AttributeException When Iterating Through Multiple Strategies

### ISSUE THREAD

**Issue by AppleII2** [mementum/backtrader#177]
I am using Backtrader to test large numbers of previously generated strategies that are stored in a postgresql database. The strategy is pulled from the database and tested by backtrader, then the TradeAnalyzer and Sharpe analyzers are applied, with their outputs being once again pushed to the database. I began to run into issues where the program would thrown an AtrributeError exception after running an arbitrary number of tests:

`Traceback (most recent call last):
  File "C:/Users/Nelson/PycharmProjects/blackbox_revival/executor.py", line 10, in <module>
    testspace.execute()
  File "C:\Users\Nelson\PycharmProjects\blackbox_revival\testspace.py", line 82, in execute
    runtime=cerebro.run()
  File "C:\Users\Nelson\Miniconda3\envs\py342\lib\site-packages\backtrader\cerebro.py", line 788, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Users\Nelson\Miniconda3\envs\py342\lib\site-packages\backtrader\cerebro.py", line 845, in runstrategies
    data.preload()
  File "C:\Users\Nelson\Miniconda3\envs\py342\lib\site-packages\backtrader\feed.py", line 626, in preload
    self.f.close()
AttributeError: 'NoneType' object has no attribute 'close'`

Attempting to diagnose the problem, I wrote a test file which follows the examples in the documentation as closely as possible. The 'executor'.py module contains a simple for loop which calls the execute function in the test file

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import datetime
import backtrader as bt
import backtrader.analyzers as btanalyzers

class RunBack(bt.Strategy):
    def __init__(self):
        self.dataclose = self.datas[0].close
        self.dataopen = self.datas[0].open
        self.datahigh = self.datas[0].high
        self.datalow = self.datas[0].low
        self.datavolume = self.datas[0].volume
        self.dataopeninterest = self.datas[0].openinterest
        self.openprice = 0
        self.maxprice = 0
        print('Testing Strategy')

    def next(self):
        #LONG CONDITIONS
        if not self.position:
            try:
                if self.dataclose[-3] == self.datahigh[-3]: self.buycontract()
            except:
                cerebro.runstop()
        #CLOSE CONDITIONS
        if self.position:
            if self.datahigh[0] > self.maxprice:
                self.maxprice = self.datahigh[0]

            if self.datalow[0] < (self.maxprice-2.5) or self.datalow[0] < self.openprice-2.5:
                self.maxprice = self.openprice=0
                RunBack.flatten(self)

    def buycontract(self):
        #print("BOUGHT 1 TO OPEN @ %.2f" % self.dataclose[0])
        self.openprice = self.maxprice = self.dataclose[0]
        self.buy()
    def flatten(self):
        #print("WENT FLAT @ %.2f" % self.dataclose[0])
        self.sell()

cerebro = bt.Cerebro()
cerebro.addstrategy(RunBack)

data = bt.feeds.YahooFinanceData(
    dataname = 'GLD',
    fromdate = datetime.datetime(2015, 1, 1),
    todate = datetime.datetime(2016, 10, 14))
cerebro.adddata(data)
cerebro.addanalyzer(btanalyzers.SharpeRatio, _name = 'sharperatio')
cerebro.addanalyzer(btanalyzers.TradeAnalyzer, _name = 'profittracking')

def execute():
    cerebro.broker.setcash(100000.0)
    runtime = cerebro.run()
    runtimeresult = runtime[0]
    #Number of Trades Made
    tradesmade= runtimeresult.analyzers.profittracking.get_analysis()['total']['total']
    print('SUCCESSFUL BACKTEST')

```
The issue does not appear after a consistent number of backtest have been performed, and appears irrespective of current cpu/memory load. My best guess is that the loop isn't giving Cerebro enough time to shut down before calling it for the next test, but the issue persists even when a delay is added between executions. I'm kind of at a loss here. Do you have any suggestions as to how to more reliably set up the iteration within Backtrader?

Thank you!

Nelson

**Comment by mementum** [comment]
The issue seems to kick in because a file has been *closed* and although the snippet doesn't show how `execute` is actually been used, a sensible guess would be:

  - The same `cerebro` is being used over and over again for the backtesting

Be it the case: it is wrong! (If not some extra clues would be needed)

A `Cerebro` instance is only meant to be used once and reusing it would lead to problems like that one.

Like pointed out above and if that's the case, a sensible setup would create a new cerebro instance for each run.

Ideally, there should be no need to recreate the *data feeds*, but they would unfortunately go through the preloading phase again, because of the fact that *cerebro is only meant to be used once*.

The use case is anyhow interesting and there could be a potential setup which would avoid the data feeds being reloaded over and over again:

  - Optimization

This may seem strange because *optimization* is meant for the optimization of a single strategy and your case indicates that different strategies are actually being tested. This could mix both approaches:

  - Create a generic strategy with a specific parameter which is the key to fetching the real strategy to optimize from your database

  - Add this generic strategy with `optstrategy` and an iterable with the keys to fetch the databases

  - Run *cerebro* (optionally with `cerebro.run(optreturn=False)` if not only the analyzers are wished)

    You may also run with `cerebro.run(maxcpus=1)` to mimic the current behavior (or else all cores will be used)

In this scenario the datas will be preloaded once and shared across the different iterations of the optimization.

Let me know if this may help

P.S.
It may be sensible to look into adding support for a reusable cerebro,

**Comment by mementum** [comment]
This post shows hot to cover the use case: http://blog.backtrader.com/posts/2016-10-29-strategy-selection/strategy-selection/
