### ISSUE TITLE
Creating a New Feed

### ISSUE THREAD

**Issue by kszynkar** [mementum/backtrader#178]
Hi Mementum,

I was wondering if you had any docs detailing how the feeds that can handle live and historical data work. I've read through your Oanda and IB feed code, but don't understand how the historical data is fed into the class when live data (historical parameter set to FALSE) is requested as well. To me it looks like there is a queue set up to receive live data that runs in a separate thread, but I can't see where the historical data is requested. Would you mind helping me?

FYI, I'm writing a new feed to be able to take in Bloomberg data. I'm happy to share it when it's complete.

Thanks!

**Comment by mementum** [comment]
Actually the `Oanda` data feed was the 1st attempt at making such a live feed a lot more generic, because the `Interactive Brokers` feed was the 1st one to be integrated and required some experimentation.

There will be, within the next few days, a blog post dedicated to the topic.

**Comment by mementum** [comment]
The blog post will not come. After having looked at all *live* data feeds and although a pattern is more or less there, the next provider would need specific development depending on how data and event are delivered.

But the raw summary is:

  - The `_load` function of the feed is a finite state machine

The following states play a role:

  - `_ST_OVER`: the feed can no longer deliver data. This may be due to a number of circumstances, like having specified the wrong contract or having actually exhausted the data after a historical-only download

  - `_ST_FROM`: an additional data feed is being used for the initial backfill. The feed will be pushed forward until exhausted and the data copied to `self` during each iteration

  - `_ST_HISTORBACK`: used for backfilling and historical only downloads (parameter `historical` is set to `True`)

  - `_ST_LIVE`: The state in which live data is being received. Of course here the detection of problems notified by the *store* plays a role

    There is an additional substate held in `_statelivereconn` to allow the feed to notify the strategy when the new data (after a reconnection) is `LIVE` (a buffer of 1 is pending processing)

In `_ST_LIVE` and `_ST_HISTORBACK` the received data is passed to auxiliary functions that load the data into the lines of the feed.

Connectivity is handled by the corresponding store (in this case `OandaStore`). The store is in charge managing the actual connection model and data reception to the provider.

The data feed sits on a `queue.Queue` object waiting for the *store* to push data into it and needs no thread management to listen to anything (for example a socket)

It is sensible to think that a generic live feed and live broker could define generic interfaces for a, as much as possible, streamlined integration from providers.

But connection to providers was added very late into *backtrader* and hence the lack of such an interface.

**Comment by kszynkar** [comment]
Thank you very much. Will share it when I finish it up.
