### ISSUE TITLE
Backtrader can't go short 

### ISSUE THREAD

**Issue by urtrial** [mementum/backtrader#186]
Hello! 
While developing trading system using backtrader I encountered a problem.
During backtesting when I try to go short (no matter manually in strategy or using FixedReverser) the position in instrument goes negative as expected (at least using self.getposition().size) but cash instead of increasing decreases (also correctly deducting commission), just as if I was going to buy the same amount.

On my machine the code below replicates such behaviour.
The difference can be seen by commenting/uncommenting the line with adding sizer.
```
# Create a Stratey
class TestStrategy(bt.Strategy):
    params = (
        ('maperiod', 15),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None
        self.base_stake = 1
        
        self.smaS = bt.indicators.MovAv.SMA(self.data, period=20)
        self.smaL = bt.indicators.MovAv.SMA(self.data, period=70)
        self.crossSMA = bt.indicators.crossover.CrossOver(self.smaS, self.smaL)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enougth cash
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            if order.isbuy():
                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            self.bar_executed = len(self)

        # Write down: no pending order
        self.order = None

    def next(self):
        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        if self.crossSMA[0] > 0:
            self.order = self.buy()

        elif self.crossSMA[0] < 0:
            self.order = self.sell()


# Create a cerebro entity
cerebro = bt.Cerebro()

# Add a strategy
cerebro.addstrategy(TestStrategy)

# Add the Data Feed to Cerebro
cerebro.adddata(data)

# Set our desired cash start
cerebro.broker.setcash(100000.0)

# Add a FixedSize sizer according to the stake
# cerebro.addsizer(bt.sizers.FixedReverser, stake=10)

# Set the commission
cerebro.broker.setcommission(commission=0.0)

# Print out the starting conditions
print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

# Run over everything
cerebro.run()

# Print out the final result
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

cerebro.plot()
```

My python version is 3.5.2.
Backtrader version is 1.9.11.99.

**Comment by mementum** [comment]
Sorry but I have to say the title is somehow a mis-statement. Saying that *backtrader can't go short* is wrong when you also confirm the position is being set as negative, which implies that it has effectively turned short.

There is also no output to back the claims.

But in any case: you say that cash decreases and this is so. The calculated value of the porftolio doesn't decrease. If you are really lucky and can go short for free, congratulations. Part of the rest of the world has to put guarantees in place (cash) but get the value in in the shorted asset.

The behavior can be changed by creating a custom commission information and overriding the appropriate methods. There are three sections in the documentation dedicated to this topic:

  - http://backtrader.readthedocs.io/en/latest/commission-schemes/commission-schemes.html
  - http://backtrader.readthedocs.io/en/latest/extending-commissions/commission-schemes-extended.html
  - http://backtrader.readthedocs.io/en/latest/user-defined-commissions/commission-schemes-subclassing.html

Because you are going short, you may also consider interest:

 - http://backtrader.readthedocs.io/en/latest/commission-credit.html

**Comment by urtrial** [comment]
Have you tried to run the code?
It is not an issue that cash do decreases because of commission or interest, that is obvious of course.
But it DO decreases when you DO sell. For example if you had $100k and 0 position and you sell 1 share for 6k with zero commission and interest. You will have $94k and -1 position, but you should have had 106k and -1 position so that your net assets would have remained $100k.
So you hurried to close the topic.

**Comment by urtrial** [comment]
This happens only if you sell more shares than you have. If you just decrease your position in instrument everything will be calculated correctly.

**Comment by mementum** [comment]
The following comments wer received via e-mail and github doesn't show them (manually deleted?)

> Have you tried to run the code?
> It is not an issue that cash do decreases because of commission or interest, that is obvious of course.
But it DO decreases when you DO sell. For example if you had $100k and 0 position and you sell 1 share for 6k with zero commission and interest. You will have $94k and -1 position, but you should have had 106k and -1 position so that your net assets would have remained $100k.
So you hurried to close the topic.

>This happens only if you sell more shares than you have. If you just decrease your position in instrument everything will be calculated correctly.

There was no hurry to close the topic amd this is not a service to run code for you. If you want an open topic, please:

  - Write a proper title
  - Run the code yourself (with and without your commented line)
  - Provide proper output
  - Say what's wrong with the output
  - Say how it should work

In the answer above it was stated

> But in any case: you say that cash decreases and this is so

Your insist on "commission" and nowhere there can one read "commission". The answer is 100% straightforward: *cash decreases* when you enter a short position. The answer also adds

>  The calculated value of the porftolio doesn't decrease.

If your output can proof otherwise, there will be a bug correction.

If the system doesn't actually match your *expectations* you can try to formulate what you think the system should do, because it may, according to your expectations, a better behavior
