### ISSUE TITLE
Misleading behavior when using multiple data feeds

### ISSUE THREAD

**Issue by kizzx2** [mementum/backtrader#190]
### Scenario

I have a 10 minute strategy that uses 1 minute indicators.

### Minimal Code to Illustrate the Problem

```python
import io, datetime

import backtrader as bt
import pandas as pd
import numpy as np

class DummyStrategy(bt.Strategy):
    def __init__(self):
        self.clock = False

    def notify_trade(self, trade):
        print("{} Trade opened at {}".format(trade.open_datetime(),  trade.price))

    def next(self):
        print(
            self.data0.datetime.time(),
            self.data0.open[0], self.data0.high[0], self.data0.low[0], self.data0.close[0],
            '/',
            self.data1.datetime.time(),
            self.data1.open[0], self.data1.high[0], self.data1.low[0], self.data1.close[0])

        if self.data0.datetime.time() == datetime.time(9, 30) and not self.bought:
            self.buy()
            self.bought = True

def getdata():
    data = io.StringIO(
"""time,open,high,low,close
2016-11-01 09:20:00,22959,22969,22954,22963
2016-11-01 09:21:00,22963,22965,22946,22959
2016-11-01 09:22:00,22959,22959,22948,22950
2016-11-01 09:23:00,22950,22961,22947,22959
2016-11-01 09:24:00,22959,22961,22950,22956
2016-11-01 09:25:00,22958,22994,22956,22992
2016-11-01 09:26:00,22992,23007,22987,22994
2016-11-01 09:27:00,22993,23024,22992,23024
2016-11-01 09:28:00,23024,23100,23024,23088
2016-11-01 09:29:00,23088,23095,23064,23072
2016-11-01 09:30:00,23074,23078,23047,23049
2016-11-01 09:31:00,23051,23083,23051,23061
2016-11-01 09:32:00,23061,23090,23060,23077
2016-11-01 09:33:00,23078,23085,23070,23074
2016-11-01 09:34:00,23074,23083,23063,23070
2016-11-01 09:35:00,23070,23071,23051,23052
2016-11-01 09:36:00,23051,23055,23039,23055
2016-11-01 09:37:00,23055,23068,23048,23065
2016-11-01 09:38:00,23067,23072,23048,23051
2016-11-01 09:39:00,23052,23081,23042,23081
2016-11-01 09:40:00,23081,23091,23044,23045
""")

    data.seek(0)
    return data

if __name__ == '__main__':
    c = bt.Cerebro(stdstats=False)

    df = pd.read_csv(getdata(), parse_dates=['time'], index_col='time')

    feed = bt.feeds.PandasData(dataname=df, openinterest=None, volume=None)
    c.resampledata(feed, timeframe=bt.TimeFrame.Minutes, compression=10)

    feed = bt.feeds.PandasData(dataname=df, openinterest=None, volume=None)
    c.adddata(feed)

    c.addstrategy(DummyStrategy)

    c.broker.setcash(1000000)
    c.run()
```

### The Output

```
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:20:00 22959.0 22969.0 22954.0 22963.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:21:00 22963.0 22965.0 22946.0 22959.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:22:00 22959.0 22959.0 22948.0 22950.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:23:00 22950.0 22961.0 22947.0 22959.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:24:00 22959.0 22961.0 22950.0 22956.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:25:00 22958.0 22994.0 22956.0 22992.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:26:00 22992.0 23007.0 22987.0 22994.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:27:00 22993.0 23024.0 22992.0 23024.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:28:00 23024.0 23100.0 23024.0 23088.0
09:20:00 22959.0 22969.0 22954.0 22963.0 / 09:29:00 23088.0 23095.0 23064.0 23072.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:30:00 23074.0 23078.0 23047.0 23049.0
2016-11-01 09:30:00 Trade opened at 22963.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:31:00 23051.0 23083.0 23051.0 23061.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:32:00 23061.0 23090.0 23060.0 23077.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:33:00 23078.0 23085.0 23070.0 23074.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:34:00 23074.0 23083.0 23063.0 23070.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:35:00 23070.0 23071.0 23051.0 23052.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:36:00 23051.0 23055.0 23039.0 23055.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:37:00 23055.0 23068.0 23048.0 23065.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:38:00 23067.0 23072.0 23048.0 23051.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:39:00 23052.0 23081.0 23042.0 23081.0
09:40:00 23051.0 23091.0 23039.0 23045.0 / 09:40:00 23081.0 23091.0 23044.0 23045.0
```

### The Problem

`backtrader` gives me the price of `22963`. However, looking at the 1-minute data (on the right), it's obvious that I'll never get filled at that good price in real life:

```
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:30:00 23074.0 23078.0 23047.0 23049.0
2016-11-01 09:30:00 Trade opened at 22963.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:31:00 23051.0 23083.0 23051.0 23061.0
09:30:00 22963.0 23100.0 22946.0 23049.0 / 09:32:00 23061.0 23090.0 23060.0 23077.0
```

So, after some debugging, the problem here is that I added the larger timeframe before the smaller timeframe, and `self.buy()` is buying into the bigger timeframe. For this particular purpose, the problem can be fixed by adding the smaller timerframe first according to the documentation.

However, the behavior here is totally counter-intuitive. I cannot think of any case where filling the order with `22963` ever makes sense. This seems to be completely a side effect rather than an intention. Even if I am buying the 10-minute timeframe, the correct behavior should be filling the order at `09:40` with price `23051`.

The existing behavior is actually very misleading and dangerous, because this basically allows the strategy to travel back through time and obtain a good price. The whole point of the negative indexing on data is to prevent accidental data-snooping. And I feel this does introduce it.

As a contrived example, what if I trade instrument A with 10 minute bar, using indicators of 1 minute data in instrument B? In that case, even if I add the smaller timeframe instrument B first, I'd still have to call `self.buy(data1)` and have no way to escape this bug except some heavy hacks.

### Proposed Solution

In `BackBroker.next`, maintain an internal clock for each data feed and disallow "travel back in time" in `_try_exec`

**Comment by mementum** [comment]
As you point the documentation says:

>The data with the smallest timeframe (and thus the larger number of bars) must be the 1st one to be added to the Cerebro instance

From: http://backtrader.readthedocs.io/en/latest/data-multitimeframe/data-multitimeframe.html#data-multiple-timeframes

And it is for a good reason (although the updated synchronization mechanism should be enough to remove this restriction)  The price is being matched with the `10 minutes` data feed which is a resampled version of the `1 minute` data feed.

That means that `data0` (the *resampled* data) is seeing things late, because it is waiting for a signal (the 1st `1 minute` bar out of the `10 minutes` period) to deliver itself.

In any case and if inserting the larger timeframe still works in your case, you should have issued:

```python
self.buy(data=self.data1)
```

or 

```python
self.buy(data=self.datas[1])
```

A default `self.buy` will buy into the 1st data. The system doesn't know that both belong to the same asset and will make no assumptions about it.

The execution of the order is not *travelling back in time*. The resampled data is delayed because it is resampling. You can see that in that the ´10 minutes` data is not updating whilst the `1 minute` data advances.

In any case I guess (and this is only a guess) that you may be looking for *replaying*. Replaying delivers always and up to date `10 minutes` bar. But you have to take into account that your `next` method will be called several times with the same `len`.

**Comment by kizzx2** [comment]
So, with the context in mind, let's further simplify this case. If we _just_ focus on the 10-minute part:

```
09:30:00 22963.0 23100.0 22946.0 23049.0
2016-11-01 09:30:00 Trade opened at 22963.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:40:00 23051.0 23091.0 23039.0 23045.0
```

How does this make sense? 

The main focus here is not about the strategy, its' about `BackBroker`.

The `Strategy` can be incomplete, confused, wrong, reference "incorrect" data due to messing up timeframe and contain any arbitrary logic that doesn't make any sense.

However, the main point here is that `BackBroker` should never allow the `Strategy` do this:

```
09:30:00 22963.0 23100.0 22946.0 23049.0
2016-11-01 09:30:00 Trade opened at 22963.0
09:30:00 22963.0 23100.0 22946.0 23049.0
```

Here is what happened:

- The `Strategy` is given a 10-minute bar _after_ the 10 minute has elapsed.
- The `Strategy` makes a decision to buy. Logically, looking at `09:40:00`, one would expect it to be filled at a price like `23051`
- However, as a side effect of calling `next` 10 times, `BackBroker` actually _filled_ the order after the first line, _the the opening price of the bar the strategy has just already seen_!

----

If we step out and think for a moment, shouldn't the expected behavior be like this?

```
09:30:00 22963.0 23100.0 22946.0 23049.0
    (Strategy makes a decision to buy)
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
09:30:00 22963.0 23100.0 22946.0 23049.0
2016-11-01 09:40:00 Trade opened at 23051.0
09:40:00 23051.0 23091.0 23039.0 23045.0
```

>But you have to take into account that your next method will be called several times with the same len. 

So if we _just focus on the `Strategy`_, how can the `Strategy` be modified to get the expected result?

**Comment by mementum** [comment]
You are trying to put too much intelligence where it simply doesn't belong.

The broker sees 2 data streams and doesn't make any assumption about them being related. Your problem is that you know they are related and you expect the world to also know about and act accordingly. But for the broker the streams are unrelated.

If you tell the broker to buy from `self.data0` (which is the default) it will buy from it at the available price. The broker is doing what it is meant to do.

The instruction to buy from `self.data0` has been given by the strategy and it is the responsible to issue orders: for which data. The strategy is the only relevant part in this behavior.

**Comment by kizzx2** [comment]
That's exactly my point -- don't try to put too much intelligence into it. My point is that under *all possible circumstances*, this shouldn't happen:

```
09:30:00 22963.0 23100.0 22946.0 23049.0
    (Strategy makes a decision to buy)
2016-11-01 09:30:00 Trade opened at 22963.0
09:30:00 22963.0 23100.0 22946.0 23049.0
```

The problem is that this behavior is happening _just because I added another data_.

Originally you said the problem is because my strategy didn't prepare for the fact that `next` could be called multiple time with the same data. Well -- nothing can be prepared than a one-time flag:

```python
        if self.data0.datetime.time() == datetime.time(9, 30) and not self.bought:
```

----

So to remove more intelligence from the discussion and make the point even simpler. The point is again -- the below situation should never happen in any configurations, but it is happening:

- After seeing bar A, Strategy sees an uptrend, buy
- _After that_, `BackBroker` gives the strategy the opening price of bar A

The question is, should the above scenario be allowed in any possible real world situation?

**Comment by drSeeS** [comment]
Hi guys, sorry for jumping in. Possibly you guys talk about slightly different issues?

Definately agreed that it is foremost a question of strategy design to think well into which data feed to buy and at what time. 

Mementum, you were very careful in your design to prevent any look ahead bias with using negative indexing (indeed an advantage over many other platforms). 
Now if I understand the point: in reality it is not possible to buy at the OPEN of a bar which has already started to 'happen' at the point in time when the buy signal is perceived (any buy signal to occur, say at 9:36h from the more granular data feed -1 min bars-, will in reality have no change to buy into the less granular time frame - 10 min bars - for the 10-min OPENING price which occured at or brefore 9:30h, at 9:30:01h it might be outdated already by the arrival of a new price which we do not know. At 9:36h the opening price is possibly history

In fact, to take it further, it would never even have a chance to buy into the opening price of any contemporaneous bar of any feed of any granularity, may they be related or not. This is since you can not even be sure that the opening price is indeed prevalent at 9:30h sharp. If at 9:30h no trading took place, the opening price reflects the price of the last trade. It could have already happened at 9:29h.
So, even when the decision to buy is taken at exactly 9:30h as in the first snippet above:
`        if self.data0.datetime.time() == datetime.time(9, 30) and not self.bought:
            self.buy()`
you cannot be sure to get a fill at the opening price.

So if I got the point correctly, I would agree that under some circumstances this could introduce a look ahead bias.

Your desing is well layed out overall, so along these lines to stay coherent, would allowing to trade only at the close of a concurrent bar (and possibly additionally test for bar volume>0 to be sure a very old last price is not just carried through time with no actual trading) remedy the issue?

**Comment by mementum** [comment]
I think there is some misreading here. Nobody said that:

> Originally you said the problem is because my strategy didn't prepare for the fact that next could be called multiple time with the same data. Well -- nothing can be more prepared for multiple invocations than a one-time flag:

what was said was:

> In any case I guess (and this is only a guess) that you may be looking for replaying. Replaying delivers always and up to date 10 minutes bar. But you have to take into account that your next method will be called several times with the same len.

But let's focus:

  - There isn't a lookahead bias here. There is a lookback bias in place

The order is being executed in the larger timeframe order which is ticking slower than the smaller timeframe. In every tick of the smaller timeframe, the same bar of the larger timeframe is seen and the broker executes it.

The broker doesn't know the larger timeframe data is slowed (frozen) by the slower timeframe data which is ticking faster.

A similar case is if you simply replay a data feed. The broker will be presented with a data feed which has *length* frozen in time for a while (the bar values change, but the *length* doesn't). To support such a case the broker uses the latest `tick_open` to execute.

One of the reasons why the smaller timeframe has to be inserted.

Can this be changed? Yes and no.

In a replay scenario, the datetime will not compulsory change with the delivery of each tick. Platforms tend to offer millisecond resolution and several ticks can for sure happen within a millisecond. The broker is then bound to execute with the next incoming tick without looking at the datetime.

This means that in the use case laid out above (smaller timeframe, larger timeframe, let's buy from the larger timeframe), the larger timeframe whose *length* is frozen will offer the wrong *tick* to the broker.

The only thing that could be added is a parameter to the broker, to activate a control check and only execute orders if the datetime has advanced.

**Comment by kizzx2** [comment]
Yes, I think that sums up the current issue quite well. It looks like the main crux of the issue here seems to be that the broker cannot distinguish between:

- Same datetime, different actual ticks (a real world phenomenon), vs.
- Same datetime, same "actual" tick (a by-product of the current way feeds of multiple timeframes are given to strategy)

With the exception of platform bugs, I believe `same datetime, same "actual" tick` is not a phenomenon that happens in the real world.

Wouldn't a more natural way to model the real world phenomenon to add a concept of "tick id" or something?

**Comment by mementum** [comment]
You see the broker almost as a real broker and it is not. The broker simulation in backtrader tries as much as possible to decouple itself from the data. It is not a data provider and data doesn't run in its blood.

This allows for example to use a live data feed (Interactive Brokers for example) and use the broker simulation (See the `ibtest` sample, or `oanda` or `visualchart`)

**Comment by kizzx2** [comment]
You are right, but what's the point of a broker implementation that doesn't try to be as close to a real broker as possible? Isn't the whole point of doing backtest trying to simulate what would happen in the real world and we're all _hopefully_ trying to find the Holy Grail in backtest that would work exactly the same in real world?

There are certain inaccuracies that cannot be avoided by a backtest broker, such as reflecting the impact of a big order / simulating performance during low volume. Those are things that cannot be worked around.

But philosophically on a high level, should the broker's behavior be dictated and deviated from a real broker's behavior, because adding a stream of characters from one `.py` file to another `.py` file would pollute the model?
