### ISSUE TITLE
enhancement: Bollinger Bands %B

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#191]
Could you include a new line in the bollinger band indicator?

```
%B = (Current Price - Lower Band) / (Upper Band - Lower Band)
```

Thanks!!!

**Comment by kizzx2** [comment]
You can quite easily implement this yourself:

```python
class MyBollingerBands(bt.indicators.BollingerBands):
    lines = ('mid', 'top', 'bot', 'pctb')

    def __init__(self):
        super(MyBollingerBands, self).__init__()
        self.l.pctb = (self.data - self.l.bot) / (self.l.top - self.l.bot)
```

**Comment by mementum** [comment]
When subclassing from an indicator with existing lines, there is no need to redeclared the lines. As such

```python
class MyBollingerBands(bt.indicators.BollingerBands):
    lines = ('pctb',)
    plotlines = dict(pctb=dict(_name='%B'))  # display the line as %B on chart

    def __init__(self):
        self.l.pctb = (self.data - self.l.bot) / (self.l.top - self.l.bot)
        super(MyBollingerBands, self).__init__()
```

Due to the way inheritance works in Python and how *backtrader* works, in most cases it is best to invoke the `__init__` method of the parent class after performing the needed actions. This would mostly be needed if further subclassing, which I guess in any case it is not needed.

**Note**: Creating a `contrib` subpackage/subproject is becoming an option, to for example add this things, without having to update *backtrader* itself.
