### ISSUE TITLE
Closing a position requires cash

### ISSUE THREAD

**Issue by heinzermch** [mementum/backtrader#194]
The error occurs when I have multiple positions open. I start with 1000 in cash, and open positions which cost around 100 each. Whenever my remaining cash is lower then the value of the position I try to close, the close is "executed" at price 0 and the asset remains in my portfolio.

Is there any reason for that behavior? Or is it simply a bug.

**Comment by kizzx2** [comment]
If you post a minimal sample code it'd be much easier for people to help you

**Comment by mementum** [comment]
Indeed a sample would help. There is no reason for the platform to use *price* with a value of `0` for a execution.

The broker simulation checks submitted orders to understand if they would push the cash level below `0` (ie: it doesn't admit leverage, because the cash must be in the account)

If you `close` a position, the pseudo-execution will say that you have enough cash after the fact and the order will be allowed in the system.

If the order is not allowed it will be rejected with status `Order.Margin`. Of course if you check `order.executed.price` after such a status notification, it will be `0.0` (`None` would have also been an option), because the order has *not* been executed.

**Comment by heinzermch** [comment]
There was indeed a problem, due to a wrong indention the `order.completed` test was omitted. And thereafter I tracked the assets wrongly.

On another note, is there an easy way to add cash to the account when short selling an asset (as this is was happens in reality)?

**Comment by heinzermch** [comment]
Nevermind, short cash question was already answered here: https://github.com/mementum/backtrader/issues/186
