### ISSUE TITLE
new version backtrader messup with ipython?

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#20]
Hello!

Thanks for the updates!

I just upgraded backtrader  from 1.1.5.88 to 1.10.88. It looks the new version of backtrader will mess up with ipython command line prompt. 

normally, ipython looks like this:
Ln[1]:
Ln[2]:
Ln[3]:

However, aftering upgrading to 1.10.88. my ipython will look likes this after importing backtrader:

strange characters:
strange characters:
strange characters:

I tested on two laptops and both have this issue.  I re-installed 1.1.5.88 and ipython looks fine. 

My python version:

```
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]
```

Appreciate for any comments.

**Comment by mementum** [comment]
Hi, This is possibly due because I added an automatic flush-on-write override to sys.stdout when running on Win32 platforms (where buffering is broken)

I imagine that ipython also plays with the buffering and my own fix renders this incompatible.

Therefore I will disable it and only add it manually to the tests.
