### ISSUE TITLE
multiprocess pool not closed

### ISSUE THREAD

**Issue by zhuoqiang** [mementum/backtrader#230]
multiprocess pool not closed after use, which leaves lots of python sub process running

See: https://github.com/mementum/backtrader/blob/master/backtrader/cerebro.py#L821-L825

**Comment by mementum** [comment]
Running after the main script which started the backtesting ceases to run?

**Comment by zhuoqiang** [comment]
I'm running it in jupyter notebook, after `cerebro.run()` finished, I notice there's a bunch of new python process.

If I run the `cerebro.run()` again, more python process will show up. and the old one won't exit.

I believe that is because `multiprocess.pool` not closed propertly

**Comment by mementum** [comment]
Running a regular script leaves this amount of processes hanging: `0`

`jupyter notebooks` (and `spyder for what's worth) manipulate how (and when) the Python kernel is started and exhibit problems with multiprocessing.

There is in any case nothing against closing the pool (will be done in the next version) rather than waiting for garbage collection (which even under `jupyter` should happen as soon as cerebro returns from run, because the object holding the pool no longer exists)

But it's definitely a bug somewhere else.

**Comment by zhuoqiang** [comment]
I just tested with the latest code which has the `pool.close()` added. The worker process is closed without leak even in Jupyter notebook environment.

Thanks for the fix
