### ISSUE TITLE
No way to access trade symbol from order, trade classes?

### ISSUE THREAD

**Issue by automaton82** [mementum/backtrader#237]
I'm using multiple data feeds from multiple stock symbols, and it appears that during order / trade in Strategy, there's no 'good' way to get the symbol name that you're going against. I've had to resort to order.data._name, which seems really weird.

Was this intentional? I plan to analyse stock A, but trade against stocks B,C from the analysis on A, and then plot all 3.

It would be nice if data objects had the Symbol on them and other info (exchange, etc) that can be tracked all the way through the Strategy / Orders / Trades.

**Comment by mementum** [comment]
Not an issue. From the README:

Note:

  > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com

**Comment by gminorcoles** [comment]
I came to ask similar questions about symbology and instrument metadata -- which seem to be missing from backtrader. mementum can you comment on how this is a non-issue? A significant part of our trading operations are devoted to tracking metadata about the instruments we trade, and these concepts are central to my homegrown simulator, which I am hoping to abandon.

**Comment by mementum** [comment]
Original on Jan 4th
> can you comment on how this is a non-issue?

No on May 23rd
> I came to ask similar questions 

Because the original was a question and now it's about *asking similar questions*.

It's not an *issue* if the library/platform/framework (choose the best description) doesn't match the expectations of the user because some functionality may be missing (it remains to be seen if something is missing)

It may be also be a formulated as a feature request, a comment about how something could be done in some other ways, how the users expect to make use of the platform and many other things. But it's definitely not an *issue*.

And for all those cases the community was set up. There is absolutely no obligation to use it or to register if you only want to read what others post/contribute. Registration is only needed if you want to write and is intended to avoid spam (so far it has worked)
