### ISSUE TITLE
bar is presented twice - 

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#256]
Test program and two data files - unzip and execute testgen.py.  I originally thought this was a bar filler issue.  But you resolved that.  I was still having issues - so here is a test file and data.
The data is sparse - but I can assure you - this is actual data - not synthetic or created for the bug.  Its just a product that has a sparse trading profile at some points in time.
v. 1.9.26.105 backtrader .

Output:
```
PS C:\> .\testgen.py
 OOPS: same bar presented again - current bar datetime:  2016-07-20 13:00:00
 Past Occurence(s) datetime :  2016-07-20 13:00:00
 OOPS: same bar presented again - current bar datetime:  2016-08-12 12:50:00
 Past Occurence(s) datetime :  2016-08-12 12:50:00
```
[repeated_bar_issue.zip](https://github.com/mementum/backtrader/files/752639/repeated_bar_issue.zip)

Thanks,

**Comment by mementum** [comment]
This is not an issue. The data around the 1st point is like this:

```
7/19/2016 11:40,0.367,0.367,0.367,0.367,79,2
7/20/2016 11:30,0.356,0.356,0.356,0.356,2,2
7/22/2016 8:40,0.365,0.365,0.365,0.365,5,5
```

There is no data point for `2016-07-21` in the `5-minutes` data. But there is a data for the daily feed

```
7/19/2016 0:00,0.39,0.39,0.365,0.373,79,0
7/20/2016 0:00,0.356,0.36,0.356,0.36,2,0
7/21/2016 0:00,0.361,0.361,0.361,0.361,0,0
```

A complete output of what's happening (rather than simply **OOPS**)

```
(1912, 'data0', 1912, datetime.datetime(2016, 7, 20, 13, 0))
(1912, 'data1', 12, datetime.datetime(2016, 7, 20, 0, 0))
(1913, 'data0', 1912, datetime.datetime(2016, 7, 20, 13, 0))
(1913, 'data1', 13, datetime.datetime(2016, 7, 21, 0, 0))
('OOPS: same bar presented again - current bar datetime: ', datetime.date(2016, 7, 20), datetime.time(13, 0))
('Past Occurence(s) datetime : ', datetime.datetime(2016, 7, 20, 13, 0))
(1914, 'data0', 1913, datetime.datetime(2016, 7, 22, 0, 0))
(1914, 'data1', 14, datetime.datetime(2016, 7, 22, 0, 0))
```

Because no data points, in the lower *timeframe*, are available for `2016-07-21`, but the daily feed wants to deliver data, the best possible data that can be presented at that time by the lower *timeframe* data feed is the latest available data.

The length of `data0` remains constant with a value of `1912`, whilst the strategy and `data1` increase their lengths.

The timestamp is **NOT** being repeated. Data synchronization pauses `data0` to deliver `data1` and then carries on.
