### ISSUE TITLE
optimization over float parameters

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#30]
When I was trying to run optimization on a parameter over a list of float numbers, I see an error message cerebro.py line 374 self.runstrats = list(pool.map(self, iterstrats)) 
====> pool.py line 251 return self.map_async(func, iterable, chunksize).get()
====> pool.py line 558 raise self._value 
TypeError: integer argument expected, got float

Is there a way to do optimization with float numbers?

**Comment by mementum** [comment]
There is nothing against optimizing a list of floats. backtrader's code doesn't care if a list contains int, float or objects. It must simply be an iterable.

I imagine the exception is being raised because "chunksize" has somehow been passed to pool as a float.

Do you have a minimal sample to see how the error is triggered?

**Comment by zhanjing** [comment]
Yes, I figured out what's wrong. There was a bug in my code. Sorry for the confusion.
