### ISSUE TITLE
trading basket of tickers

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#32]
Hi, if I create a basket of tickers in the data, how can I specify the ticker to buy or sell in the order? Can you add a sample of pair trade strategy? Thanks.

**Comment by mementum** [comment]
Hi.

"datas" inside a strategy in backtrader are referenced following the order in which they were inserted in the system (a cerebro entity)

"datas" can actually (and mostly do) carry a name which can be a "ticker", a "filename" or any other arbitrary things.

The rationale behind not "referencing" by name is that, imho, a strategy should be as generic as possible and based on sound ideas, rather than being optimized for very specific parameters and a specific "ticker".

Obviously there is no absolute truth and specific parameters and ticker-based strategies can of course be successful.

To indicate on which data you want to operate with the buy/sell/close methods included with the Strategy base class you do the following:

  - self.buy(data=self.data, price=price, ...)

This indicates the action has to be done for the 1st data (also available under the alias self.data0). This is the default and as such you can do:

  - self.buy(price=price, ...)

For data1 and subsequent it should be fairly obvious:

  - self.buy(data=self.data1, price=price, ...)

The following could be potentially added:

  - A function to get a data looking for its "name". Something like: self.getdatabyname(dataname)

  - buy/sell/close could check if the "data" kwarg is a string and if it is, use the self.getdatabyname(dataname) call internally before further proceeding.

The souce code contains several samples and many have gotten a post in www.backtrader.com

For multi-datas the following link shows the multi-datas example:
  - http://www.backtrader.com/posts/2015-09-03-multidata-strategy/multidata-strategy/

The sample is in the source code:
  - https://github.com/mementum/backtrader/blob/master/samples/multidata-strategy/multidata-strategy.py

**Comment by tomcpli** [comment]
Nice. Thanks for the detail explanation.
