### ISSUE TITLE
multiple tickers execution

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#35]
If I have a multiple buy/sell orders with different ticker e.g. self.buy(data=self.data0), self.buy(data=self.data1). Is it possible to retrieve the 'data name' / ticker from the order object after the notification ? Besides, I would like to know what are the holdings tickers in the existing positions? Is it useful to check if the ticker/instrument is exists in the holdings. Thanks.

**Comment by mementum** [comment]
Each "order" carries a "data" attribute which is obviously the data for which the order has been created.

  - data._name gives you access to the name

"_name" may be set by the end user when adding the data

  - cerebro.adddata(mydata, name="xxxx")

If not set some datas will try to set it using a reasonable default. For example:

  - CSV derived subclasses will use the filename (not the entire path, just the filename) as the data name

Positions do not have a "data" because you actually retrieve the position using "data" as the key from inside the strategy. The "getposition" method is defined as:

  - def getposition(self, data=None, broker=None)

If "data" is None then data0 (the 1st data added to the system) will be used as the key for the returned position (given most people only test with a single data, it seems a reasonable default)

**Comment by tomcpli** [comment]
Although most people only test with a single data, a lot of strategy (e.g. momentum strategy, factor model, etc.) requires testing with a universe. The momentum strategy ranks all stocks on momentum in the universe, buy top n stocks with higher momentum, rebalance the portfolio monthly...

Since the design takes care of multiple data multiple instruments, I think
1. it's more convenience if buy/sell orders takes name as one of the parameters.
2. it's nice if it's easy to retrieve the snapshot of the portfolio (e.g. self.positions) at any point of time. Users want to know what are the holding stocks and their quantity so that they can easily do the rebalance on the portfolio.

Thanks.

**Comment by mementum** [comment]
1. This was added with commit 1bc723c5b97f6bf51334a39d2c4456d3c47afb89 for version 1.1.20.88

2. Added getpositions (and property position) in upcoming commit
