### ISSUE TITLE
chronological order under multiple data source

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#39]
There are multiple data (e.g. orcl, nvda) and they have different start times or there are some gaps in the data. For each iteration on next(self) of bt.Strategy, the datetimes of the 2 data are not aligned. I understand the users have to make sure the data are aligned before adding to the cerebro, but I think the behavior is unexpected. 

Will it be a good idea to make sure that data have same datetime on each next(self) being called. If one of the data has gap, it should be None or automatically forward backfilled.

**Comment by mementum** [comment]
The logic:
  - 1st data inserted in the system is the master clock
  - 2nd and posterior datas will not deliver data if their current datetime is `>` (greater than) the datetime of the master

The system can neither know nor understand why a gap in the data is there. Example:
  - Datas with different timeframes like 60 minutes and days.

The "days" data doesn't have a gap. It is simply that the data is not yet ready, whist the "60 minutes" data keeps on producing bars. And the "days" data cannot/must not kick the strategy with an empty bar, because that would be an illusion and would actually break the calculation of the indicators.

Should the "Stochastic" also understand if an empty bar (once in which the values have been filled with "Nan") is such an empty bar and discard it or use the "NaN" (and disrupt the end result)? Indicators must remain simple and stupid and do a good job.

Your issue is one of "data filling". This is something I already started considering and the following classes are available in the source code:

  - `DataFiller` which was the 1st implementation. I should actually delete it, because it has been superseded by the "filter" concept.

  - `SessionFiller` which is the 2nd implementation and uses the "filter concept".
     It is only implemented for a session, because I consider unlikely that "daily" and larger timeframes have missing data. If a day is missing, it is because no trade happened that day, and that's not missing data, it is actually relevant.

To apply a filter to a data:

```python
data = btfees.MyDataFeed(.....)

data.addfilter(filter, *args, **kwargs)
```

The only 2 available "filters" so far are:
  - SessionFiller (fill missing intraday bars)
  - SessionFilter (cap the data to the given session times, which can for example filter out non-Regular Trading Hours data)

The docstring for `SessionFiller`

```python
class SessionFiller(with_metaclass(metabase.MetaParams, object)):
    '''
    Bar Filler for a Data Source inside the declared session start/end times.

    The fill bars are constructed using the declared Data Source ``timeframe``
    and ``compression`` (used to calculate the intervening missing times)

    Params:

      - fill_price (def: None):

        If None is passed, the closing price of the previous bar will be
        used. To end up with a bar which for example takes time but it is not
        displayed in a plot ... use float('Nan')

      - fill_vol (def: float('NaN')):

        Value to use to fill the missing volume

      - fill_oi (def: float('NaN')):

        Value to use to fill the missing Open Interest

      - skip_first_fill (def: True):

        Upon seeing the 1st valid bar do not fill from the sessionstart up to
        that bar
    '''
```

**Comment by tomcpli** [comment]
Thanks for the detail answers. It's a good work. Looking forward to see the documentation and example of data filling.

**Comment by mementum** [comment]
- http://www.backtrader.com/posts/2015-11-21-data-filters/data-filling-filtering/

Another example to implemente "Calendar Days" is my backlog

**Comment by mementum** [comment]
Synchronization has been reworked with release 1.9.0.99
