### ISSUE TITLE
get information from trade under notify_trade

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#42]
The order under notify_order can retrieve
- executed price, order.executed.price
- executed size, order.executed.size
- executed datetime, order.executed.dt
- ticker of the order, order.data._name

For the trade under notify_trade, I find there is no way to get the
- trade dateime or (trade open datetime / trade close datetime)

The trade.price is not right. If you have a buy order and then a sell order, the trade.price of the 2nd notify_trade is the buy price (not the sell price).

**Comment by mementum** [comment]
`trade.price` is not the "execution" price. Execution price is something which only orders can carry.

`trade.price` is the `current price` of the trade. If a trade is open and the position is increased, the price will change, because the overall position price has changed. But if the position is decreased the overall price does not change. The remaining assets in the trade still have that price tag, which will be used to calculate profit and loss.

Although not explicitly there, opening datetime and closing datetime can be retrieved, because trades keep a reference to the data. This will be implemented. In the meantime you may apply this code (untested ... typos may be there and the datetime may have a 1 unit offset)

```python
datalen = len(trade.data)

opendelta = trade.baropen - datalen
opendt = trade.data.datetime[opendelta]  # float coded datetime
opendatetime = trade.data.datetime.datetime(opendelta)  # python datetime.datetime.object

closedelta = trade.barclose - datalen
closedt = trade.data.datetime[closedelta]  # float coded datetime
closedatetime = trade.data.datetime.datetime(closedelta)  # python datetime.datetime.object
```

**Comment by mementum** [comment]
Trade has been extended:

```python
class Trade(object):
    '''
    Keeps track of the life of an trade: size, price,
    commission (and value?)

    An trade starts at 0 can be increased and reduced and can
    be considered closed if it goes back to 0.

    The trade can be long (positive size) or short (negative size)

    An trade is not meant to be reversed (no support in the logic for it)

    Member Attributes:
      - size (int): current size of the trade
      - price (float): current price of the trade
      - value (float): current value of the trade
      - commission (float): current accumulated commission
      - pnl (float): current profit and loss of the trade (gross pnl)
      - pnlcomm (float):
        current profit and loss of the trade minus commission (net pnl)
      - isclosed (bool):
        records if the last update closed (set size to null the trade
      - isopen (bool): records if any update has opened the trade
      - justopened (bool): if the trade was just opened
      - baropen (int): bar in which this trade was opened
      - dtopen (float): float coded datetime in which the trade was closed
        - Use method ``open_datetime`` to get a Python datetime.datetime
          or use the platform provided ``num2date`` method
      - barclose (int): bar in which this trade was closed
      - dtclose (float): float coded datetime in which the trade was closed
        - Use method ``close_datetime`` to get a Python datetime.datetime
          or use the platform provided ``num2date`` method
      - barlen (int): number of bars this trade was open
    '''
```

**Comment by tomcpli** [comment]
Thanks for the description. It's nice to have open_datetime and close_datetime.

The following error occurs if the trade is not a close trade and you try to access close_datetime,

    File "C:\Projects\Open Source\backtrader\branches\development\backtrader\utils\dateintern.py", line 70, in _num2date
    dt = datetime.datetime.fromordinal(ix)
    ValueError: ordinal must be >= 1

Will it be a good idea to return 0001-01-01 00:00:00 UTC or None if x is less than 1?

**Comment by mementum** [comment]
As long as trade isn't closed no value makes sense, because it isn't closed and therefore the most sensible value is a `null` value which is invalid. Any other value would produce the false sensation that a trade may be closed because the `closing datetime` can already be retrieved.

You should check before is `trade.isclosed`

**Comment by tomcpli** [comment]
OK. Thanks. I will check with trade.isclosed.

**Comment by mementum** [comment]
You may be even better off with:

```python
if trade.status == trade.Closed:
    # do something here
    pass
```

The original `isclosed` should be superseded by the existence of a status field
