### ISSUE TITLE
trade id and order id

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#43]
Every trade and order should have their unique id. If they are not inserted by user, they should automatically generated.

**Comment by mementum** [comment]
Hi,

  - Orders carry a unique identifier: ``Order.ref``

  - `tradeid` is not a unique identifier for the trades and that's why it can be passed along during order creation. `tradeid` to group orders under a `tradeid`. Value 0 indicates that no grouping has to happen and orders must be sequentially processed to open/update/close trades.

     You can issue an order with `tradeid 1`, then 8 orders with `tradeid 2`, and then 1 extra order with `tradeid 1` again. Than means that the 1st and 10th order will be grouped together for the purpose of opening/updating/closing a Trade. And the 2nd-9th orders will also be grouped together for a different trade.

  - Unlike Orders (which are cloned because they can be notified several times during the same `next` cycle and live in different parts of the platform), Trades are unique objects and belong exclusively to the Strategy. Trades are already unique and indexed according to creation.
