### ISSUE TITLE
percentage commission for futures 

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#45]
I found the percentage-based commission calculation for futures not very intuitive. Right now the commission is calculated as comm% * price * size. Note that here there is no multiplier for the futures. On the other hand, normally the percentage comm% is based on the total contract value, which means the user has to do the multiplication of comm% * multiplier manually and put into the framework. Ideally the commission for futures should be calculated as comm% * price * multiplier * size.

**Comment by mementum** [comment]
Unfortunately there is no magical one-fits-all solution and that's why the rework of Commission Schemes some weeks ago opened the door for easy subclassing.

Long due post has been published:

  - http://www.backtrader.com/posts/2015-11-20-commission-schemes-subclassing/commission-schemes-subclassing/

Which hopefully should answer the question.
