### ISSUE TITLE
KeyError on trade_analyzer

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#46]
If there is no trade, trying to access the trade statistics got "KeyError".

    trade_analysis = thestrat.analyzers.trade_analyzer.get_analysis()
    :
    print(trade_analysis['total']['total'])

print(trade_analysis['total']['total'])
File "C:\Anaconda\lib\site-packages\backtrader\utils\autodict.py", line 84, in __missing__
    raise KeyError
KeyError

**Comment by mementum** [comment]
The TradeAnalyzer uses the "auto"dict feature in which by subclassing a dict and overriding __missing__ (basis for collections.defaultdict) a key can be inserted in real time.

If no trades have been made the keys do obviously not exist.

When a backtesting run comes to an end, the "autodict" is "_closed" which prevents the creation of new keys and therefore avoids potential typing errors. For example for a run with some trades executed and if you had typed:

```python
print(trade_analysis['total']['totol'])
```
and the "autodict" were not yet "_closed" you would actually get an "AutoDict" instance automatically created.

This would be unwanted behaviour, imho, because the typing error is better detected with a "_closed" AutoDict generating an error.

A possible compromise would be to have exactly this value: ``['total']['total']`` filled with a default value of 0, to enable a check in user code.

Unless you have any other suggestion I will add it at once.

**Comment by tomcpli** [comment]
Thanks. I agree with you the value ['total']['total'] should fill with a default value of 0, and I think the same issue happened in other values e.g. ['won']['total']

**Comment by tomcpli** [comment]
['won']['total'] and ['lost']['total'] should be filled with a default value of 0.
If ['total']['total'] > 0 but the trade orders are not closed, It will raise KeyError from ['won']['total'] or ['lost']['total']

**Comment by mementum** [comment]
I understand your reasoning, but in that case one could argue that many other values could/should/must also be filled. For example: trades.long.total with a value of 0 if you have opened a long which is not yet closed.

The analyzer already offers you a value to check it. From tradenanalyzer.py:

```python
        if trade.justopened:
            # Trade just opened
            self.trades.total.total += 1
            self.trades.total.open += 1
```

In this case ``total.open`` (or ``['total']['open']``) contains the value of open but not yet closed trades (and therefore not accounted for in the other statistics)
