### ISSUE TITLE
bug in the resampler

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#47]
I just noticed a bug in the data resampler. Specifically, I have tick data from two different days and want to resample into minute data. I used the following parameters:

    data_resampled = bt.DataResampler(
            dataname=data,
            timeframe=TimeFrame.Minutes,
            adjtimelimits=False,
            compression=1)

the input tick data is shown below:
datetime,open,high,low,close,volume
28/08/2015 16:13:57.000,21529,21529,21529,21529,1
28/08/2015 16:13:59.001,21524,21524,21524,21524,3
28/08/2015 16:14:00.000,21522,21522,21522,21522,1
28/08/2015 16:14:57.003,21525,21525,21525,21525,1
28/08/2015 16:14:59.001,21536,21536,21536,21536,1
31/08/2015 09:15:00.000,21450,21450,21450,21450,4
31/08/2015 09:15:59.000,21455,21455,21455,21455,1
31/08/2015 09:16:00.000,21454,21454,21454,21454,1
31/08/2015 09:16:56.002,21479,21479,21479,21479,1

The results are:
28/08/2015 16:13:59.002003, 21529, 21529,21524,21527,5
31/08/2015 09:15:59.000000, 21522, 21536,21450,21455,8
31/08/2015 09:16:56.002002, 21454, 21479,21454,21479,2

The problem is that the 28/08/2015 16:14:59.001 bar is missing.

**Comment by zhanjing** [comment]
I think the bug is inside the function _barisover_minutes_sub(self, index), and can be fixed by adding a check with the date:

        date = self.lines.datetime.date(index)
        bardate = self.data.datetime.date(index)

        if (bardate > date) or (barpoint > point):

**Comment by mementum** [comment]
Hi, I have actually "deprecated" DataResampler and DataReplayer in favor of the "filter" technology and the resampler and replayer filters.

The "filters" are described here: http://www.backtrader.com/posts/2015-11-21-data-filters/data-filling-filtering/

The resampling post was updated: http://www.backtrader.com/posts/2015-09-25-tickdata-resample/resample-tickdata/

Ways to resample/replay data:

  - Over Cerebro

    ```python
    cerebro.resampledata(data, **kwargs)  # kwargs -> same as the existing ones for DataResampler
    cerebro.replaydata(data. **kwargs)  #  # kwargs -> same as the existing ones for DataReplayer
    ```

  - Over the data itself (this is what ``cerebro`` internally does)

    ```python
    data.resample(**kwargs)
    cerebro.add(data, name=xx)  # name=None is the default
    ```

  - If you for example resample a daily data to weekly and want to use both simultaneously

    ```python
    cerebro.adddata(data)
    cerebro.resampledata(data.clone(), **kwargs)
    ```
I will anyhow look into the code from above for the old resampler

**Comment by zhanjing** [comment]
The resampling implementation seems to have the exact same bug.

**Comment by mementum** [comment]
Adding that check is no issue, but I have looking into my code once again and I think the bug is located just a few lines before

```python
        # Put session end in context of current datetime
        sessend = self.data.datetime.tm2dtime(self.sessionend)

        if self.data.datetime[index] > sessend:
            # Next session is on (defaults to next day)
            return True
```

Your ``28/08/2015 16:14:59.001,21536,21536,21536,21536,1`` bar is obviously not past your end of session time. When this bar comes in a because it has crossed no resampling boundary, the method returns "False"

The next invocation puts ``sessend`` in the context time of the new bar (this "in the context" avoids precision errors with the coding/decoding to/from float/datetime), but the new bar is already in a new session/day. And the old bar is missed.

Actually the 1st output bar of the next day

```31/08/2015 09:15:59.000000, 21522, 21536,21450,21455,8```

has amongst others the open price of this other bar

```28/08/2015 16:14:00.000,21522,21522,21522,21522,1```

In this case the correction must apply to ``_barupdate`` which must only allow data within the defined session times (the default is the entire day) and then ``_barisover_minutes_sub`` checking if the next incoming data has surpassed the defined end of the session.

The beginning of ``_barupdate`` looks like:

```python
    def _barupdate(self, index=0, replaying=False):
        sstart = self.data.datetime.tm2dtime(self.sessionstart)
        send = self.data.datetime.tm2dtime(self.sessionend)
        if sstart > self.data.datetime[index] > sessend:
            # Not within session limits - skip the bar
            return

        if math.isnan(self.l.open[0]):
```

And ``_barisover_minutes_sub``

```python
    def _barisover_minutes_sub(self, index):
        # Put session end of cached internal bar in context of current time
        sessend = self.lines.datetime.tm2dtime(self.sessionend)

        if self.data.datetime[index] > sessend:
            return True

        tm = self.lines.datetime.time(index)
```

With those patches applied and testing your sample data with the exact same parameters given by you above the result is (quoting first the input data for reference):

```
28/08/2015 16:13:57.000,21529,21529,21529,21529,1
28/08/2015 16:13:59.001,21524,21524,21524,21524,3
28/08/2015 16:14:00.000,21522,21522,21522,21522,1
28/08/2015 16:14:57.003,21525,21525,21525,21525,1
28/08/2015 16:14:59.001,21536,21536,21536,21536,1
31/08/2015 09:15:00.000,21450,21450,21450,21450,4
31/08/2015 09:15:59.000,21455,21455,21455,21455,1
31/08/2015 09:16:00.000,21454,21454,21454,21454,1
31/08/2015 09:16:56.002,21479,21479,21479,21479,1
```

```
===============================================================================
Id,,len,datetime,open,high,low,close,volume,openinterest,Strategy,len
1,,1,2015-08-28 16:13:59.000998,21529.0,21529.0,21524.0,21524.0,4.0,,Strategy,1
2,,2,2015-08-28 16:14:59.001004,21522.0,21536.0,21522.0,21536.0,3.0,,Strategy,2
3,,3,2015-08-31 09:15:59,21450.0,21455.0,21450.0,21455.0,5.0,,Strategy,3
4,,4,2015-08-31 09:16:56.002002,21454.0,21479.0,21454.0,21479.0,2.0,,Strategy,4
===============================================================================
```

Which seems a lot more like the expected value. Row data number 2 has the last timestamp of the input of 28/08/2015 which is ``16:14:59.001`` (the printout does not restrict the decimals ... and hence the 001004)

And output row 3 has the correct opening price for 31/08/2015 at 09:15:00.000 which is 21450 (also the low price) and the highest from 9:15:59:000 which is incidentally also the closing price. And the volume is 5.

Path to be included in a few minutes for ``DataResampler``

**Comment by zhanjing** [comment]
This bug shows up (again? or it's been there) in cerebro.resampledata(). It missed the last minute bar at the end of the day.
datetime,close,open,high,low
2015-05-04 14:58:00.000,45780.000,45780.000,45780.000,45780.000
2015-05-04 14:58:59.500,45760.000,45760.000,45760.000,45760.000
2015-05-04 14:59:00.000,45750.000,45750.000,45750.000,45750.000
2015-05-04 14:59:59.500,45720.000,45720.000,45720.000,45720.000
2015-05-05 09:00:00.500,45740.000,45740.000,45740.000,45740.000
2015-05-05 09:00:59.500,45670.000,45670.000,45670.000,45670.000
2015-05-05 09:01:00.000,45670.000,45670.000,45670.000,45670.000
2015-05-05 09:01:59.500,45590.000,45590.000,45590.000,45590.000

Outputs:
04/05/2015 14:58:59.499996, 45780, 45780,45760,45760
05/05/2015 09:00:59.499999, 45750, 45750,45670,45670
05/05/2015 09:01:59.499995, 45670, 45670,45590,45590
