### ISSUE TITLE
request for api

### ISSUE THREAD

**Issue by hackerwei** [mementum/backtrader#53]
Advice: Is it possible to offer an api for integrated with Ta-lib, since talib offers many indicators for use. 
Best regards!

**Comment by mementum** [comment]
Looking at: http://mrjbq7.github.io/ta-lib/func.html

```python
upper, middle, lower = talib.BBANDS(close, matype=MA_Type.T3)
```

This simple line shows that an integrated "api" must not be that, but a wrapper around ta-lib. The reason being:

  - ta-lib indicators return 1 o more arrays
  - backtrader function return objects

There is an operational layer which can be overcome in that the objects returned by backtrader have not been evaluated yet and will not be until you "run", and the arrays returned by ta-lib are already value filled.

The major issue here is the "1 or more" and the need to define that as object. It cannot be done in real-time, because the object returned by backtrader must be lazily evaluated and must therefore delay the evaluation of ta-lib. This means that it is unknown how many arrays will be returned by the ta-lib call.

As such a wrapper for each function has to be defined. The best option would be to let the user do the declaration in real-time with something like:

```python
TA_BBBANDS = backtrader.talib.BBANDS('upper', 'middle', 'lower')
```

You would then have a properly usable object inside backtrader, You could do (just an example, not useful) a moving average on the "middle"

```python
  talib_bbands = TA_BBANDS(self.data.close, matype=backtrader.talib.MA_Type.T3)
  # Now 3 lines "upper", "middle", "lower" can be referenced using talib_bbands

  middle_sma = backtrader.indicators.SMA(talib_bbands.middle, period=15)
```

In the background backtrader would parse the self.data.close internal array and pass it to ta-lib as a numpy array (to check wether array.array can be passed directly saving one conversion along the way) and reconvert the returned numpy arrays back to internal backtrader objects (possibly by simply wrapping the array and avoiding a lengthy an expensive conversion)

It seems feasible, but there will be many quirks on the patch.

**Comment by hackerwei** [comment]
thanks, the backtrader is really great! I'm still reading the code.

**Comment by mementum** [comment]
After checking the code passing arrays to `talib` will be expensive, because `talib` is expecting `numpy` arrays. This makes this a very longterm task.

Are there any specific indicators that you miss from `backtrader`? It will be possibly a lot easier and faster to create them (probably creating a separate repository which holds the new indicators, repository which can be updated without having to update the `backtrader` version)

**Comment by fccoelho** [comment]
I haven't looked at the code, but one good reason for not re-implementing the indicators, would be to benefit from tested and actively maintained code from the ta-lib library.

**Comment by mementum** [comment]
I do fully understand your comment but one of the goals of this library/platform is to be pure Python.

**Comment by mementum** [comment]
The complexity would be too much. Won't get done

**Comment by mementum** [comment]
ta-lib (the version using the cython bindings and not the original using swig) added 9 days ago a "streaming" interface which allows calculating just the last value and not the entire batch each and every time.

This makes it compatible with the `next` approach used by *backtrader* when not operating in batch mode.

Adding support is now an option
