### ISSUE TITLE
question:metabase.py

### ISSUE THREAD

**Issue by hackerwei** [mementum/backtrader#54]
How does the function findowner() in metabase works, not quite understand this function and . 
Also in lineroot.py MetaLineRoot class, what's type of of _obj? I guess it's MetaParams,but "_obj._OwnerCls" seems not match the MetaParams class.
Hope there're docs about the class relations, reading the src is not quite easy, thx & Merry Christmas!

**Comment by mementum** [comment]
``findowner`` traverses the Python frame stack to find a specific class instance using either the Python convention of using ``self`` or the internal ``backtrader`` convention of using ``_obj`` in metaclasses

That's how, for example, any ``Indicator`` derived class knows in which ``Strategy`` instance it has bee instantiated and can register behind the scenes. That allows the strategy instance to later kick the indicators in order to perform its calculations.

This removes burden from the end users of the platform, because no "register to parent" calls are needed (which also implies having a ``parent`` argument passed during instantiation)

``_obj.__OwnerCls`` may be defined by the classes to restrict the type of instances to find. If no definition is made the first found instace of ``LineMultiple`` will be a match.

A definition of ``_OwnerCls`` can be seen in ``observer.py`` where it looks like: ``_OwnerCls = StrategyBase``

These classes and functions are not meant to be documented. They are the internals of the platform and have suffered several changes and reordering and may suffer more.

``LineRoot`` is a modern addition to unify all classes carrying lines, be it 1 or be it more, which aided in simplifying some other parts of the internals.
