### ISSUE TITLE
Know the length of data.lines.close?

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#57]
Hi,

I have this code:

```python
modpath = os.path.dirname(os.path.abspath(sys.argv[0]))
datapath = ('./datas/IBEALL.csv')

fromdate=datetime.date(2015, 4,1)
todate=datetime.date(2015,12, 31)   

data = bt.feeds.GenericCSV_TEST(
    dataname=datapath, fromdate=fromdate,
    todate=todate,)
```

HERE I WANT TO KNOW THE LEN OF THE LINES OF DATA

is it posible to get the length of data here?

**Comment by mementum** [comment]
Hi Juanjo,

The datasource doesn't know in advance how many lines it will have. Instantiating "data" has only created the object and set the parameters that will be used when the data feed fetches the data.

The reasoning behind this: *the data feed can be retrieving data from a live source and therefore ... the number of lines cannot be known in advance*

In any case and because you are only presumably backtesting with your `GenericCSV_TEST` you can know during the execution phase how many lines have been **preloaded** if you tell `cerebro` preload (at instantiation or when invoking `run`)

For example (not tested, it can have some syntax errors):

```python
class MyStrategy(bt.Strategy):
    def next(self):
        print('Total data lines: {}'.format(self.data.buflen()))
        print('Current data lines {}'.format(len(self.data)))

modpath = os.path.dirname(os.path.abspath(sys.argv[0]))
datapath = ('./datas/IBEALL.csv')

fromdate=datetime.date(2015, 4,1)
todate=datetime.date(2015,12, 31)   

data = bt.feeds.GenericCSV_TEST(
    dataname=datapath, fromdate=fromdate,
    todate=todate,)

cerebro = bt.Cerebro(preload=True)
cerebro.adddata(data)
cerebro.addstrategy(MyStrategy)

cerebro.run()
```

Having a look at the code, the *strategies* are instantiated before the data is *preloaded*. This could possibly (would need to check if it breaks any existing code or it has a side-effect) be turned around, so that the during the `__init__` phase of the strategy, the length of the preloaded data can be queried.

**Comment by junajo10** [comment]
Thanks, i have solved my problem, using cerebro = bt.Cerebro(preload=True) and  print('Total data lines: {}'.format(self.data.buflen())).
the idea is divide the total volume in several days, then i need to know the total days, so i can divide the total amount by the number of days ((self.data.buflen())
self.quantityFixed=self.totalQuantity/self.data.buflen()
self.sizer.setsizing(min(self.params.volumeRemain,int(self.quantityFixed)))

Congratulations on your library. i am using to backtest my strategies.
