### ISSUE TITLE
Cerebro.optstrategy

### ISSUE THREAD

**Issue by rgeos** [mementum/backtrader#58]
When using opstrategy, is there a way to extract for example the best portfolio value with its strategy parameters or the worst portfolio value with its parameters?

For example:
`cerebro.optstrategy(SomeStrategyName, par1=range(1,5), par2=range(1,5)`

I want to retrieve for instance the best `broker.getvalue()` and its equivalent `params.par1` & `params.par2`.

**Comment by mementum** [comment]
Indeed. When you add strategies via the `optstrategy` method and you run from a `cerebro.run` (example) you get something like:

```python
stragegy_runs = cerebro.run()
print(strategy_runs)
```
Which will print something like this (not actual Python output, but it will be similar)

```
[[MyStrategy object xx, OtherStrategy object yy], [MyStrategy object zz, OtherStrategy object zy], ...]
```

Which can of course be traversed with a nested for loop

```python
for strategy_run in in  strategy_runs:
    for strategy in strategy_run:
        pass  # do something here
```

This may seem complicated (strategies are returned in a list of lists) but it is because you can have 1 or more strategies per run. Each initial list represent an optimization pass, and the sublist represent the strategies active in that optimization pass.

For a simple case in which you have only 1 strategy (my case 99.9% of the times) or if you simply need a value which will be common to all the strategies, you can use a comprehension to simplify the output:

```python
strategies = [x[0] for x in strategy_runs]
```

Coming down to the best portfolio. Even if the strategy still has a reference to a `broker` if makes no longer sense, because it has been reused in each optimization pass. As such the best way is to keep the values you may be interested in (`get_value` for example) when the strategy comes to an end.

```python
class MyStrategy(backtrader.Strategy):

    def stop(self):
        self.portfolio_value = self.broker.get_value()
```

If you have multiple strategies in a run, this needs only be done in one of them, because all those strategies share the same active broker. You may of course do it in all of them.

Now you have the strategies and you can access the portfolio value over the `portfolio_value` member attribute of each strategy instance and you can even quickly sort it to have your best strategy at the top:

```python
strategies.sort(key=lambda x: x.portfolio.value, reverse=True)
```

**Comment by rgeos** [comment]
with just a small modification it works like a charm. Thank you!

> in the strategy class 

```python
class MyStrategy(backtrader.Strategy):
    def stop(self):
        self.params.portfolio_value = self.broker.getvalue()
```

> sorting the strategies

```python
strategies.sort(key=lambda x: x.params.portfolio_value, reverse=True)
```
