### ISSUE TITLE
Close order execution time

### ISSUE THREAD

**Issue by fanhi00** [mementum/backtrader#62]
Hi Mementum,
First I want to thank you for building such a great backtesting tool and sharing with us. I was testing some strategies and I have one question regarding the close order execution. In your example it seems that when you put a close buy/sell order, it will be executed the next day (using daily data) at the close price. But in my test it is always executed the day after the next day. I used your OrderExecution sample code and the only difference is that i used a pandas datafeed.
Also is it possible to execute a close order on the day the order was submitted? The idea is that i want to make an order right before the closing and to capture the overnight price change.

Thank you
Hui

**Comment by mementum** [comment]
Hi,

Since you provided no code, but this is an easy one: a test is worth a thousand words.

The dataset used is in the sources of `backtrader`

```python
import random

import backtrader as bt
import backtrader.feeds as btfeeds


class St(bt.Strategy):
    def __init__(self):
        self.order = None

    def notify_order(self, order):
        if order.status in [order.Completed]:
            dtstr = bt.num2date(order.executed.dt).isoformat()
            if order.isbuy():
                print('BUY EXECUTED, on:', dtstr)
            else:  # Sell
                print('SELL EXECUTED on:', dtstr)

    def next(self):
        if not random.randint(0, 5):  # roll a dice to decide entering/exit
            dtstr = self.data.datetime.datetime().isoformat()
            if self.position:
                print('SELL CREATED, on:', dtstr)
                self.close(exectype=bt.Order.Close)
            else:
                print('BUY CREATED, on:', dtstr)
                self.buy(exectype=bt.Order.Close)


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    data = btfeeds.BacktraderCSVData(dataname='2005-2006-day-001.txt')
    cerebro.adddata(data)
    cerebro.addstrategy(St)
    cerebro.run()
```

Output (not everything, it would be too long)

```
BUY CREATED, on: 2005-01-06T23:59:59
BUY CREATED, on: 2005-01-07T23:59:59
BUY EXECUTED, on: 2005-01-07T23:59:59
BUY EXECUTED, on: 2005-01-10T23:59:59
SELL CREATED, on: 2005-01-13T23:59:59
SELL EXECUTED on: 2005-01-14T23:59:59
BUY CREATED, on: 2005-01-19T23:59:59
BUY EXECUTED, on: 2005-01-20T23:59:59
SELL CREATED, on: 2005-02-22T23:59:59
SELL EXECUTED on: 2005-02-23T23:59:59
...
...
BUY CREATED, on: 2006-12-14T23:59:59
BUY CREATED, on: 2006-12-15T23:59:59
BUY EXECUTED, on: 2006-12-15T23:59:59
BUY EXECUTED, on: 2006-12-18T23:59:59
SELL CREATED, on: 2006-12-19T23:59:59
SELL EXECUTED on: 2006-12-20T23:59:59
```

Orders are getting created on day `d0` and being executed on day `d1`, which is not necessarily the next calendar day, because weekends play a role. The last lines contain an example: Dec 15th 2006 was a Friday and the order gets executed on the next trading day: Mon, Dec 18th 2006.

The overlapping trades is a side effect of the `Close` order type. You issue an order and will be executed at the end of next day. But you can go in next day and decide to buy again, before you actually have a position.

This is because the logic used to buy and sell is rolling a dice (random integer [0, 5] delivering a 0) and it can kick in during several consecutive days). With a *sentinel* in place (checking if an order is pending) that behavior can be avoided.

**Comment by mementum** [comment]
Your second question: 

> Also is it possible to execute a close order on the day the order was submitted? The idea is that i want to make an order right before the closing and to capture the overnight price change.

The answer is *No* if you are using daily data and and execute the orders on a daily basis. You can only evaluate a "daily" bar when the day is closed and by then you cannot issue a "Close" order, because the day is over. That's why the `broker` in `backtrader` executes the order the next day.

But the answer is "Yes" if you are using "intraday" data and issue a "Close" order for example at 13:00 (for whatever reason) and the market is closing at 17:30. The order would get executed at 17:30 (your system could still cancel the order at anytime during 13:00 and 17:30)

**Comment by mementum** [comment]
This example replays weeks from a dataset made up of days (the same concept applies when going from minutes to days when it comes to the `Close` order)

The logic issues a BUY order on Wed (or Thu/Fri if Wed happens to be a non-trading day) and sells on Mondays.

The BUY execution takes place on "Friday" (a couple of times on Thursday, when Fri was not a trading day) with the closing price, because Friday is the day the weekly bar is closed. But during the week, the strategy had the chance to issue an order.

The dataset is in the backtrader sources.

Code (adds a sentinel to avoid concurrent BUY orders)

```python
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind


class St(bt.Strategy):
    def __init__(self):
        self.order = None

    def notify_order(self, order):
        if order.status in [order.Completed]:
            dtstr = bt.num2date(order.executed.dt).strftime('%a %Y-%m-%d')
            if order.isbuy():
                print('BUY EXECUTED, on:', dtstr)
                self.order = None
            else:  # Sell
                print('SELL EXECUTED on:', dtstr)

    def next(self):
        dtstr = self.data.datetime.date(0).strftime('%a %Y-%m-%d')
        weekday = self.data.datetime.date(0).weekday()  # Mon 0 - Sun 6

        if self.position and weekday >= 0:  # sell at beginning of next week
            print('SELL CREATED, on:', dtstr)
            self.close(exectype=bt.Order.Close)

        elif self.order is None and weekday >= 2:  # order on Wed/Thu/Fri
            print('BUY CREATED, on:', dtstr)
            self.order = self.buy(exectype=bt.Order.Close)


if __name__ == '__main__':
    cerebro = bt.Cerebro(runonce=False, preload=False)  # both False for replay

    data = btfeeds.BacktraderCSVData(dataname='2005-2006-day-001.txt')
    cerebro.replaydata(data, timeframe=bt.TimeFrame.Weeks)
    cerebro.addstrategy(St)
    cerebro.run()
```

Output (reduced to avoid too much clutter)

```
BUY CREATED, on: Wed 2005-01-05
BUY EXECUTED, on: Fri 2005-01-07
SELL CREATED, on: Mon 2005-01-10
SELL EXECUTED on: Tue 2005-01-11
BUY CREATED, on: Wed 2005-01-12
BUY EXECUTED, on: Fri 2005-01-14
SELL CREATED, on: Mon 2005-01-17
SELL EXECUTED on: Tue 2005-01-18
...
...
BUY CREATED, on: Wed 2006-12-13
BUY EXECUTED, on: Fri 2006-12-15
SELL CREATED, on: Mon 2006-12-18
SELL EXECUTED on: Tue 2006-12-19
BUY CREATED, on: Wed 2006-12-20
BUY EXECUTED, on: Fri 2006-12-22
SELL CREATED, on: Wed 2006-12-27
SELL EXECUTED on: Thu 2006-12-28
BUY CREATED, on: Thu 2006-12-28
```

**Comment by mementum** [comment]
Since your original problem seems to have to do with the dataset. Do you have a sample you can share?

**Comment by fanhi00** [comment]
Hi mementum,
Sorry for the late reply, below is the code that I used (essentially copied from your order execution sample), also i used the same data (your 2006-day-001.txt). However i still get buy/sell 2 days after the order. I appreciate if you can help take a look.

Below is sample output results:
2006-01-26T23:59:59, BUY CREATE, exectype Close, price 3641.42
2006-01-26T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-01-26T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-01-30T23:59:59, BUY EXECUTED, Price: 3685.48, Cost: 3685.48, Comm 0.00
2006-03-02T23:59:59, SELL CREATE, 3763.73
2006-03-02T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-03-02T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-03-06T23:59:59, SELL EXECUTED, Price: 3733.95, Cost: 3685.48, Comm 0.00
2006-03-10T23:59:59, BUY CREATE, exectype Close, price 3798.46
2006-03-10T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-03-10T23:59:59, ORDER ACCEPTED/SUBMITTED
2006-03-14T23:59:59, BUY EXECUTED, Price: 3824.97, Cost: 3824.97, Comm 0.00

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime
import os.path
import time
import sys

import pandas as pd
import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind


class OrderExecutionStrategy(bt.Strategy):
    params = (
        ('smaperiod', 15),
        ('exectype', 'Market'),
        ('perc1', 3),
        ('perc2', 1),
        ('valid', 4),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.data.datetime[0]
        if isinstance(dt, float):
            dt = bt.num2date(dt)
        print('%s, %s' % (dt.isoformat(), txt))

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            self.log('ORDER ACCEPTED/SUBMITTED', dt=order.created.dt)
            self.order = order
            return

        if order.status in [order.Expired]:
            self.log('BUY EXPIRED')

        elif order.status in [order.Completed]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

            else:  # Sell
                self.log('SELL EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

        # Sentinel to None: new orders allowed
        self.order = None

    def __init__(self):
        # SimpleMovingAverage on main data
        # Equivalent to -> sma = btind.SMA(self.data, period=self.p.smaperiod)
        sma = btind.SMA(period=self.p.smaperiod)

        # CrossOver (1: up, -1: down) close / sma
        self.buysell = btind.CrossOver(self.data.close, sma, plot=True)

        # Sentinel to None: new ordersa allowed
        self.order = None

    def next(self):
        if self.order:
            # An order is pending ... nothing can be done
            return

        # Check if we are in the market
        if self.position:
            # In the maerket - check if it's the time to sell
            if self.buysell < 0:
                self.log('SELL CREATE, %.2f' % self.data.close[0])
                self.sell(exectype=bt.Order.Close)

        elif self.buysell > 0:
            if self.p.valid:
                valid = self.data.datetime.date(0) + \
                        datetime.timedelta(days=self.p.valid)
            else:
                valid = None

            # Not in the market and signal to buy
            if self.p.exectype == 'Market':
                self.buy(exectype=bt.Order.Market)  # default if not given

                self.log('BUY CREATE, exectype Market, price %.2f' %
                         self.data.close[0])

            elif self.p.exectype == 'Close':
                self.buy(exectype=bt.Order.Close)

                self.log('BUY CREATE, exectype Close, price %.2f' %
                         self.data.close[0])

            elif self.p.exectype == 'Limit':
                price = self.data.close * (1.0 - self.p.perc1 / 100.0)

                self.buy(exectype=bt.Order.Limit, price=price, valid=valid)

                if self.p.valid:
                    txt = 'BUY CREATE, exectype Limit, price %.2f, valid: %s'
                    self.log(txt % (price, valid.strftime('%Y-%m-%d')))
                else:
                    txt = 'BUY CREATE, exectype Limit, price %.2f'
                    self.log(txt % price)

            elif self.p.exectype == 'Stop':
                price = self.data.close * (1.0 + self.p.perc1 / 100.0)

                self.buy(exectype=bt.Order.Stop, price=price, valid=valid)

                if self.p.valid:
                    txt = 'BUY CREATE, exectype Stop, price %.2f, valid: %s'
                    self.log(txt % (price, valid.strftime('%Y-%m-%d')))
                else:
                    txt = 'BUY CREATE, exectype Stop, price %.2f'
                    self.log(txt % price)

            elif self.p.exectype == 'StopLimit':
                price = self.data.close * (1.0 + self.p.perc1 / 100.0)

                plimit = self.data.close * (1.0 + self.p.perc2 / 100.0)

                self.buy(exectype=bt.Order.StopLimit, price=price, valid=valid,
                         plimit=plimit)

                if self.p.valid:
                    txt = ('BUY CREATE, exectype StopLimit, price %.2f,'
                           ' valid: %s, pricelimit: %.2f')
                    self.log(txt % (price, valid.strftime('%Y-%m-%d'), plimit))
                else:
                    txt = ('BUY CREATE, exectype StopLimit, price %.2f,'
                           ' pricelimit: %.2f')
                    self.log(txt % (price, plimit))


def runstrat():
    args = parse_args()

    cerebro = bt.Cerebro()

    data = getdata(args)
    cerebro.adddata(data)

    cerebro.addstrategy(
        OrderExecutionStrategy,
        exectype=args.exectype,
        perc1=args.perc1,
        perc2=args.perc2,
        valid=args.valid,
        smaperiod=args.smaperiod
    )
    cerebro.run()

    if args.plot:
        cerebro.plot(numfigs=args.numfigs, style=args.plotstyle)


def getdata(args):

    dataformat = dict(
        bt=btfeeds.BacktraderCSVData,
        visualchart=btfeeds.VChartCSVData,
        sierrachart=btfeeds.SierraChartCSVData,
        yahoo=btfeeds.YahooFinanceCSVData,
        yahoo_unreversed=btfeeds.YahooFinanceCSVData
    )

    dfkwargs = dict()
    if args.csvformat == 'yahoo_unreversed':
        dfkwargs['reverse'] = True

    if args.fromdate:
        fromdate = datetime.datetime.strptime(args.fromdate, '%Y-%m-%d')
        dfkwargs['fromdate'] = fromdate

    if args.todate:
        fromdate = datetime.datetime.strptime(args.todate, '%Y-%m-%d')
        dfkwargs['todate'] = todate

    dfkwargs['dataname'] = args.infile

    dfcls = dataformat[args.csvformat]

    return dfcls(**dfkwargs)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Showcase for Order Execution Types')

    parser.add_argument('--infile', '-i', required=False,
                        default='../../2006-day-001.txt',
                        help='File to be read in')

    parser.add_argument('--csvformat', '-c', required=False, default='bt',
                        choices=['bt', 'visualchart', 'sierrachart',
                                 'yahoo', 'yahoo_unreversed'],
                        help='CSV Format')

    parser.add_argument('--fromdate', '-f', required=False, default=None,
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--todate', '-t', required=False, default=None,
                        help='Ending date in YYYY-MM-DD format')

    parser.add_argument('--plot', '-p', action='store_false', required=False,
                        help='Plot the read data')

    parser.add_argument('--plotstyle', '-ps', required=False, default='bar',
                        choices=['bar', 'line', 'candle'],
                        help='Plot the read data')

    parser.add_argument('--numfigs', '-n', required=False, default=1,
                        help='Plot using n figures')

    parser.add_argument('--smaperiod', '-s', required=False, default=15,
                        help='Simple Moving Average Period')

    parser.add_argument('--exectype', '-e', required=False, default='Close',
                        help=('Execution Type: Market (default), Close, Limit,'
                              ' Stop, StopLimit'))

    parser.add_argument('--valid', '-v', required=False, default=0, type=int,
                        help='Validity for Limit sample: default 0 days')

    parser.add_argument('--perc1', '-p1', required=False, default=0.0,
                        type=float,
                        help=('%% distance from close price at order creation'
                              ' time for the limit/trigger price in Limit/Stop'
                              ' orders'))

    parser.add_argument('--perc2', '-p2', required=False, default=0.0,
                        type=float,
                        help=('%% distance from close price at order creation'
                              ' time for the limit price in StopLimit orders'))

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()

**Comment by mementum** [comment]
Hi, the order is not getting executed 2 days after. The log is being printed then (because the order executed when the market was closed the previous day)

In my sample above:
```python
dtstr = bt.num2date(order.executed.dt).strftime('%a %Y-%m-%d')
```

In the generic sample the printed `datetime` is a reference of when the method is being executed:
```python
 def log(self, txt, dt=None):
     ''' Logging function fot this strategy'''
     dt = dt or self.data.datetime[0]
     if isinstance(dt, float):
         dt = bt.num2date(dt)
     print('%s, %s' % (dt.isoformat(), txt))
```

The `log` method is simply logging the information when it can. The printed *datetime* is not meant to imply *execution*. As you see above you can get that with `order.executed.dt` (which is still a `float` and you can convert to a python `datetime.datetime` object using `num2date`)

**Comment by fanhi00** [comment]
Thanks. That means the next() method in strategy happens before the close of each? Because when i called the self.position.size in next(), I don't get the latest position (assuming trade happen at Close).
What i want to do is to know the latest position at the end of each day in the next() method(i.e., if i bought 10 stocks at the close of today, i want to be able to know that i have 10 in my portfolio). Is it easy to do? Thanks a lot.

Hui

**Comment by mementum** [comment]
Hi,

I just went over the code and I understand where everything comes from.

Logic:
  - Move the dataset(s) 1 step forward
  - Execute any orders
  - If something got executed, notify it to the strategy
  - run the strategy's `next` method

Following this logic you should get your result. But I looked deeper and realized that the `Close` order has an execution logic which takes into account the "end of session" time. This is so to make sure that it supports intraday data feeds, in which several bars for the same day will be delivered and the order has to execute when the last bar of the day has been seen.

The default "end of session" time is 23:59:59 and therefore the broker (which is only a simulation) has to wait for the next days (because you are using "daily bars") to decide if the order was executed at `Close`.

Possible solutions

  - You put a "time" in your daily bars and declare an "end of session" before the time present in the daily bars

or/and

  - extend the execution logic for "Close" bars to look at the declared "timeframe" of the bars. In the case of daily bars the order will be executed during the bar currently being executed and your strategy will be promptly notified.

Declaring the "end of session" time for a data feed:

```python
data = MyDataFeed(dataname='mydatafile', sessionend=datetime.time(15, 0, 0))
```

**Comment by mementum** [comment]
Looking deeper into the broker, there is a side effect amongst the provisions for the `Close` execution and checking if the broker has cash enough to accept the submission of an order.

The existing code will give the *right* execution date whatever you do, but the notification will always come late even if you provide a `sessionend` and add a *time* component to the daily bars of the datafeed as reasoned above. Should the fix be easy (which I think it is, but I may be wrong) I will release a version later today increasing the revision number.

**Comment by mementum** [comment]
Corrections/Improvements added (and 2 new samples specifically for `Close` orders.

Output of the *daily* sample:

```
Tue 2006-04-04: BUY  EXECUTED, on: Tue 2006-04-04
Wed 2006-04-05 23:59:59: SELL CREATED
Thu 2006-04-06: SELL EXECUTED, on: Thu 2006-04-06
Thu 2006-04-13 23:59:59: BUY  CREATED
Tue 2006-04-18: BUY  EXECUTED, on: Tue 2006-04-18
Fri 2006-04-21 23:59:59: SELL CREATED
Mon 2006-04-24: SELL EXECUTED, on: Mon 2006-04-24
Tue 2006-05-16 23:59:59: BUY  CREATED
Wed 2006-05-17: BUY  EXECUTED, on: Wed 2006-05-17
Mon 2006-05-22 23:59:59: SELL CREATED
Tue 2006-05-23: SELL EXECUTED, on: Tue 2006-05-23
...
...
```

Now the notification takes place just before the strategy is given the chance to evaluate the `closed` bar. The broker is not only reporting the right execution moment: the notification is being delivered properly.

The daily sample contains also a sample implementation of a `SessionEndFiller` which can change the bar time to one specified. Not needed for the feeds directly integrated in `backtrader` but it can probably be handy for things (for example) coming directly from `pandas`.

In the case of the *intraday* sample there are two different outcomes:

```
$ ./close-minute.py --eosbar --tend 17:30
Tue 2006-01-03 09:05:00: BUY  CREATED
Tue 2006-01-03 17:30:00: BUY  EXECUTED, on: Tue 2006-01-03 17:30:00
Thu 2006-01-05 09:05:00: SELL CREATED
Thu 2006-01-05 17:30:00: SELL EXECUTED, on: Thu 2006-01-05 17:30:00
Mon 2006-01-09 09:05:00: BUY  CREATED
Mon 2006-01-09 17:30:00: BUY  EXECUTED, on: Mon 2006-01-09 17:30:00
Wed 2006-01-11 09:05:00: SELL CREATED
Wed 2006-01-11 17:30:00: SELL EXECUTED, on: Wed 2006-01-11 17:30:00
Fri 2006-01-13 09:05:00: BUY  CREATED
Fri 2006-01-13 17:30:00: BUY  EXECUTED, on: Fri 2006-01-13 17:30:00
Tue 2006-01-17 09:05:00: SELL CREATED
Tue 2006-01-17 17:30:00: SELL EXECUTED, on: Tue 2006-01-17 17:30:00
Thu 2006-01-19 09:05:00: BUY  CREATED
Thu 2006-01-19 17:30:00: BUY  EXECUTED, on: Thu 2006-01-19 17:30:00
Mon 2006-01-23 09:05:00: SELL CREATED
Mon 2006-01-23 17:30:00: SELL EXECUTED, on: Mon 2006-01-23 17:30:00
Wed 2006-01-25 09:05:00: BUY  CREATED
Wed 2006-01-25 17:30:00: BUY  EXECUTED, on: Wed 2006-01-25 17:30:00
Fri 2006-01-27 09:05:00: SELL CREATED
Fri 2006-01-27 17:30:00: SELL EXECUTED, on: Fri 2006-01-27 17:30:00
```

In this case we have told the broker what the session end time is and to consider any bar with that given time (and not only those wiith a time greater than) to be the end of the session.

As such an order placed at 09:05 is executed at 17:30 and notified with the 17.30 bar.

The second option:

```
$ ./close-minute.py --tend 17:30
Tue 2006-01-03 09:05:00: BUY  CREATED
Wed 2006-01-04 09:05:00: BUY  EXECUTED, on: Tue 2006-01-03 17:30:00
Thu 2006-01-05 09:05:00: SELL CREATED
Fri 2006-01-06 09:05:00: SELL EXECUTED, on: Thu 2006-01-05 17:30:00
Mon 2006-01-09 09:05:00: BUY  CREATED
Tue 2006-01-10 09:05:00: BUY  EXECUTED, on: Mon 2006-01-09 17:30:00
Wed 2006-01-11 09:05:00: SELL CREATED
Thu 2006-01-12 09:05:00: SELL EXECUTED, on: Wed 2006-01-11 17:30:00
Fri 2006-01-13 09:05:00: BUY  CREATED
Mon 2006-01-16 09:05:00: BUY  EXECUTED, on: Fri 2006-01-13 17:30:00
Tue 2006-01-17 09:05:00: SELL CREATED
Wed 2006-01-18 09:05:00: SELL EXECUTED, on: Tue 2006-01-17 17:30:00
Thu 2006-01-19 09:05:00: BUY  CREATED
Fri 2006-01-20 09:05:00: BUY  EXECUTED, on: Thu 2006-01-19 17:30:00
Mon 2006-01-23 09:05:00: SELL CREATED
Tue 2006-01-24 09:05:00: SELL EXECUTED, on: Mon 2006-01-23 17:30:00
Wed 2006-01-25 09:05:00: BUY  CREATED
Thu 2006-01-26 09:05:00: BUY  EXECUTED, on: Wed 2006-01-25 17:30:00
Fri 2006-01-27 09:05:00: SELL CREATED
Mon 2006-01-30 09:05:00: SELL EXECUTED, on: Fri 2006-01-27 17:30:00
```

Here the execution is the same but `eosbar` has not been indicated and as such the notification occurs when the system first sees a bar which is above the end of the session. Hence the notification on the next day at 09:05 rather than on the same day exactly at 17:30

`eosbar` has been added to the broker to support that.

```python
class BrokerBack(with_metaclass(MetaParams, object)):
    '''Broker Simulator
      Parameters:

        Note: use the setXXXX to set the value after instance creation

        - ``cash`` (default: 10000): starting cash

        - ``commission`` (default: CommInfoBase(percabs=True))
          base commission scheme which applies to all assets

        - ``checksubmit`` (default: True)
          check margin/cash before accepting an order into the system

        - ``eosbar`` (default: False):
          With intraday bars consider a bar with the same ``time`` as the end
          of session to be the end of the session. This is not usually the
          case, because some bars (final auction) are produced by many
          exchanges for many products for a couple of minutes after the end of
          the session
    '''
    params = (
        ('cash', 10000.0),
        ('commission', CommInfoBase(percabs=True)),
        ('checksubmit', True),
        ('eosbar', False),
    )
```

**Comment by fanhi00** [comment]
Thanks so much. I think my issue was solved.

Hui
