### ISSUE TITLE
1.2.2.88 - crashed when resampledata was used

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#64]
My old code used DataResampler - to take a daily bar stream and upsample into a Weekly Bar stream and a Monthly Bar stream and added those to the strategy.  A total of 4 streams (5min, Day, Week, Month), of which 5min and Day are real data, and Week and Month are upsampled.
The old code ran clean on 1.1.27.88 (the fix you issued for #61).

Old Code:
```python
        data  = bt.feeds.PandasData(dataname=df, timeframe=bt.TimeFrame.Minutes)
        data1 = bt.feeds.PandasData(dataname=df1, timeframe=bt.TimeFrame.Days)
        data2   = bt.DataResampler(dataname=data1, timeframe=bt.TimeFrame.Weeks, compression=1)
        # Now resample the Daily bars in data1 to Monthly in data3
        data3   = bt.DataResampler(dataname=data1, timeframe=bt.TimeFrame.Months, compression=1)
        # add the two real data streams
        cerebro.adddata(data)
        cerebro.adddata(data1)
        # now add two upsampled streams
        cerebro.adddata(data2)
        cerebro.adddata(data3)
```

New Code:

        # Pass it to the backtrader datafeed and add it to the cerebro
        data  = bt.feeds.PandasData(dataname=df, timeframe=bt.TimeFrame.Minutes)
        data1 = bt.feeds.PandasData(dataname=df1, timeframe=bt.TimeFrame.Days)

        # add the two real data streams
        cerebro.adddata(data)
        cerebro.adddata(data1)

        # Now resample the Daily bars in data1 to Weekly in data2 etc and add
        cerebro.resampledata(data1, timeframe=bt.TimeFrame.Weeks, compression=1)
        cerebro.resampledata(data1, timeframe=bt.TimeFrame.Months, compression=1)   

Produces a crash:

```
     Traceback (most recent call last):
  File "NLgen.py", line 220, in <module>
    runstrat()
  File "NLgen.py", line 180, in runstrat
    cerebro.run()
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 360, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 431, in runstrategies
    data.preload()
  File "C:\Python27\lib\site-packages\backtrader\feed.py", line 233, in preload
    while self.load():
  File "C:\Python27\lib\site-packages\backtrader\feed.py", line 288, in load
    retff = ff(self, *fargs, **fkwargs)
  File "C:\Python27\lib\site-packages\backtrader\resamplerfilter.py", line 291, in __call__
    self._checkbarover(data)
  File "C:\Python27\lib\site-packages\backtrader\resamplerfilter.py", line 53, in _checkbarover
    if not self._barover(data):
  File "C:\Python27\lib\site-packages\backtrader\resamplerfilter.py", line 114, in _barover
    return self._barover_weeks(data)
  File "C:\Python27\lib\site-packages\backtrader\resamplerfilter.py", line 126, in _barover_weeks
    year, week, _ = num2date(self.bar.datetime).isocalendar()
  File "C:\Python27\lib\site-packages\backtrader\utils\dateintern.py", line 69, in _num2date
    ix = int(x)
```

Thanks,
P.S - I opened a separate issue for this - hope thats ok ..

**Comment by mementum** [comment]
It is an issue, so it's appropriate to  open an issue.

My bad. As soon as I saw your code it was clear I hadn't properly documented/explained how to do it. Have a look at this small snippet:

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt
import backtrader.feeds as btfeeds


class MyStrategy(bt.Strategy):

    def next(self):
        txt = 'Len strat %04d' % len(self)
        txt += ' - Len data0 %04d' % len(self.data0)
        txt += ' - Len data1 %04d' % len(self.data1)
        txt += ' - Len data2 %04d' % len(self.data2)
        print(txt)

if __name__ == '__main__':
    cerebro = bt.Cerebro()

    data1 = btfeeds.BacktraderCSVData(dataname='2005-2006-day-001.txt')

    cerebro.adddata(data1)
    cerebro.resampledata(data1.clone(), timeframe=bt.TimeFrame.Weeks)
    cerebro.resampledata(data1.clone(), timeframe=bt.TimeFrame.Months)

    cerebro.addstrategy(MyStrategy)

    cerebro.run()
    cerebro.plot(style='ohlc')
```

Output

```
Len strat 0021 - Len data0 0021 - Len data1 0004 - Len data2 0001
Len strat 0022 - Len data0 0022 - Len data1 0004 - Len data2 0001
Len strat 0023 - Len data0 0023 - Len data1 0004 - Len data2 0001
Len strat 0024 - Len data0 0024 - Len data1 0004 - Len data2 0001
...
...
```

And the following plot:

![figure_0](https://cloud.githubusercontent.com/assets/5713511/13649489/400c76a4-e63e-11e5-88fd-d16cc9bbb166.png)

**Explanation**

  - Calling `cerebro.resampledata` adds a *resampling* filter to the data. The data will be processed through this filter before being delivered into the system.

  - The solution is to `clone` the data when passing it to `cerebro.resampledata`

I deprecated (and removed when increasing the minor revision to 2) the DataSampler and DataReplayer because they were not so clean as the current filters and after many tries I am pretty sure they were not covering some corner cases (it could still be that the new filter are also flaky, but I am a lot more happy with them)

In any case:

  - The **cloning** should be transparent to the user, i.e: `cerebro` should check if `data1` is already in the system when being passed to `resampledata` and automatically used `clone`

    I will look into it.

In the meantime let me know if `clone` solves your problem.

**Comment by mementum** [comment]
I have added the *auto-cloning* during the call to `cerebro.resampledata` (and run a test with it) to the development branch.

**Comment by parthasrinivasan** [comment]
the call to clone fixed the crash and resolved the issue.  We are now back to where we were on datasets.  This includes SessionFiller.  So the datastream integrity is complete.
I will now get back to the task of making sure my code makes sense with Session Filled data ... lol

**Comment by mementum** [comment]
Glad to know!
