### ISSUE TITLE
ATR calculation for price series (inlcuding negative price)

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#66]
Hi Daniel,

For the price series I uploaded earlier. Something is amiss in the calculation of a simple

```python
self.ATR = btind.AverageTrueRange(self.data1, period=5, movav=btind.MovAv.SMA)
```

Where as you already have - data0 is the 5min series and data1 is the daily bar series.
I think - if there is somewhere a max or min, whose initial price value is assumed to be zero (zero assumed to be minimum price), this would produce incorrect result on all negative price series.
Basically -its the edge - the very very first transition to valid data - is where the bug would hide.
I had such a bug where the initial min price as assumed to be a very large number and the inital max was assumed to be a very small number - except I used 0.0 as very small number lol ...which caused the max function to return 0.0 every time when fed a negative price series.
Thanks for your attention in this matter.
P.S.
I check manually on a regular price series and there is a discrepancy there too .
See price_daily sheet for TSLA for the most recent 5 days.  I get 8.57 using Wilder.
My printouts in my program show a value of 7.14.
[TSLA.xlsx](https://github.com/mementum/backtrader/files/187012/TSLA.xlsx)

**Comment by mementum** [comment]
The calculation for the `ATR` makes no assumption about the initial prices. The `AverageTrueRange` sets (automatically) an internal minimum period of 2 bars, because it needs a bar in the past. The formula in summary:

  - AverageTrueRange = MovingAverage(TrueRange)
  - TrueRange = TrueHigh - TrueLow
  - TrueHigh = Max(High, Previous Close)
  - TrueLow = Min(Low, Previous Close)

Because a `Previous Close` is needed the `ATR` needs at least 2 bars to start a calculation.

Because of the definition it is clear than: TrueHigh >= TrueLow`

With negative values: `TrueHigh - TrueLow` will be something like: `-0.2 - -0.3 = 0.1`. I.e.: The `TrueRange` is positive which is what's to be expected.

I don't know which values you are expecting, but a quick modification of the script in issue #61:

```python
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.filters as btfilters
import backtrader.indicators as btind


class St(bt.Strategy):
    def __init__(self):
        atrdata = self.data1 if len(self.datas) > 1 else self.data0
        self.atr = btind.ATR(atrdata, period=5, movav=btind.MovAv.SMA)

    def next(self):
        dt = self.data0.datetime.datetime().isoformat()
        print('%d: %s %.4f' % (len(self), dt, self.atr[0]))


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    cerebro.addstrategy(St)

    if False:  # change to add the intraday feed
        data0 = btfeeds.GenericCSVData(
            dataname='dump-5min.csv.orig',
            timeframe=bt.TimeFrame.Minutes,
            compression=5,
            sessionstart=datetime.datetime(1, 1, 1, 0, 0),  # only time is used
            sessionend=datetime.datetime(1, 1, 1, 23, 59),  # only time is used
        )

        data0.addfilter(btfilters.SessionFiller, fill_vol=0.0, fill_oi=0.0)
        cerebro.adddata(data0)

    data1 = btfeeds.GenericCSVData(dataname='dump-1day.csv',
                                   timeframe=bt.TimeFrame.Days)

    cerebro.adddata(data1)

    cerebro.run()
```

Yields the following (leaving the intraday data aside, which you can turn on by changing the `False` to `True`, but the daily results are the same)

```
6: 2015-01-09T00:00:00 0.0118
7: 2015-01-12T00:00:00 0.0098
8: 2015-01-13T00:00:00 0.0114
...
251: 2015-12-29T00:00:00 0.0218
252: 2015-12-30T00:00:00 0.0208
253: 2015-12-31T00:00:00 0.0216
```

The period set (by you in the sample) is 5, but the need to have a `Previous Close` automatically extends the internal period to `6` (that's why the 1st sample comes out after 6 price bars)

The 1st value is `0.0118` which seems in line for the `AverageTrueRange` with the values that one can see during the 1st two days:

```
2015-01-02 00:00:00,-0.006,0.011,-0.008,0.004,25109,0
2015-01-05 00:00:00,0.005,0.021,0.003,0.007,29754,0
```

  - TrueHigh = Max(High, Prev Close) = Max(0.021, 0.004) = 0.021
  - TrueLow = Min(Low, Prev Close) = Min(0.003, 0.004) = 0.003
  - TrueRange = 0.018

An average over 5 days of 0.0118 doesn't seem to be out of line.

**Comment by mementum** [comment]
I see you added  an excel sheet.

The 8.57 value you produce has nothing to do with "Wilder" (if you mean the Smoothed Moving Average he defines in his book) You are making a simple average of the last 5 TrueRanges. 

In your sample line above you also use `btind.MovAv.SMA` which is the `Simple Moving Average`. This also is not what Wilder defined for the `AverageTrueRange`

If you want to stick to the Wilder's definition, then don't provide the `movav` paremeter to the ATR. The parameter is there for anyone willing to experiment with other Moving Averages without having to tweak the code.

**Comment by parthasrinivasan** [comment]
Sorry - I think I can ask a more intelligent question now -  I dont think this is a bug anymore ..
I am trying to match the 8.57 number which I can do manually - by using TrueHigh and TrueLow (same formula from atr.py module) and and an average that uses the most recent 5 days.  So for today 3/23 for TSLA - its 8.57.  I really want to use the SMA - so thats fine.  I traced the root of the issue - the ATR uses the previous 5 days eg. so today after the close - its using 3/16 - 3/22 - yielding a 7.14.
If I used 3/17 - 3/23 (mm/dd format...) then I get 8.57 .  So how do I make the ATR use the most recent 5 days ?  
The excel sheet I uploaded (I cant upload csv's) shows the calculation and if you modify to use the date range I mentioned - you will see the values change.
Do I have to do my own custom indicator for this ( I am praying ... I dont ..)

**Comment by mementum** [comment]
The `AverageTrueRange` always uses the most recent `period` days (5 in your case).

Sample script for your data

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind


class St(bt.Strategy):
    params = (
        ('use_sma', False),
        ('period', 5),
    )

    def __init__(self):
        kwargs = dict()
        if self.p.use_sma:
            kwargs['movav'] = btind.MovAv.SMA

        self.atr = btind.ATR(self.data, period=self.p.period, **kwargs)

    def next(self):
        dt = self.data.datetime.date().isoformat()
        print('%d: %s %.4f' % (len(self), dt, self.atr[0]))


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    cerebro.addstrategy(St, use_sma=True, period=5)
    data = btfeeds.GenericCSVData(dataname='tsla.csv')
    cerebro.adddata(data)

    cerebro.run()
```

Output:

```
6: 2016-02-08 14.7292
7: 2016-02-09 15.1352
8: 2016-02-10 15.0292
9: 2016-02-11 17.1492
10: 2016-02-12 16.2940
11: 2016-02-16 15.3560
12: 2016-02-17 14.4420
13: 2016-02-18 13.4320
14: 2016-02-19 10.5120
15: 2016-02-22 10.3160
16: 2016-02-23 9.5440
17: 2016-02-24 9.0420
18: 2016-02-25 10.0698
19: 2016-02-26 10.4718
20: 2016-02-29 9.4314
21: 2016-03-01 10.4711
22: 2016-03-02 9.5431
23: 2016-03-03 9.5193
24: 2016-03-04 9.7773
25: 2016-03-07 10.8117
26: 2016-03-08 9.2220
27: 2016-03-09 9.1725
28: 2016-03-10 9.0563
29: 2016-03-11 8.2463
30: 2016-03-14 7.6303
31: 2016-03-15 8.0643
32: 2016-03-16 7.8218
33: 2016-03-17 6.9980
34: 2016-03-18 7.7700
35: 2016-03-21 7.3540
36: 2016-03-22 7.1464
37: 2016-03-23 8.5744
```

And the final value for 2016-03-23 is `8.5744` which is also the one displayed in your Excel Sheet.

The values with Wilder's Moving Average (change the arguments to the Strategy to use `use_sma=False`.

```
6: 2016-02-08 14.7292
7: 2016-02-09 15.5313
8: 2016-02-10 15.0711
9: 2016-02-11 15.9748
10: 2016-02-12 15.4419
11: 2016-02-16 14.7355
12: 2016-02-17 14.6224
13: 2016-02-18 13.3339
14: 2016-02-19 11.6651
15: 2016-02-22 11.7981
16: 2016-02-23 11.0485
17: 2016-02-24 11.1708
18: 2016-02-25 11.6005
19: 2016-02-26 10.6804
20: 2016-02-29 9.9699
21: 2016-03-01 10.6256
22: 2016-03-02 9.9045
23: 2016-03-03 10.5636
24: 2016-03-04 10.1089
25: 2016-03-07 10.5471
26: 2016-03-08 9.4977
27: 2016-03-09 8.9527
28: 2016-03-10 9.6859
29: 2016-03-11 8.5967
30: 2016-03-14 8.7214
31: 2016-03-15 8.4711
32: 2016-03-16 7.8889
33: 2016-03-17 8.0111
34: 2016-03-18 8.0289
35: 2016-03-21 7.8511
36: 2016-03-22 7.5673
37: 2016-03-23 8.5938
```

The 1st value is the same because the 1st average is kickstarted with the Simple Average of the 1st `period` values (not my invention, it's in Wilder's book). From there onwards and given the exponential nature of Wilder's Moving Average (also known as Smoothed Moving Average) the values diverge. But the final value of `8.59` is of course not miles away from the one achieved with the `Simple Moving Average`

**Comment by parthasrinivasan** [comment]
OK - thanks so much.  
I will go back and start digging - I must have introduced a bug somewhere

**Comment by parthasrinivasan** [comment]
Hi Daniel,
Please allow me to apologize for wasting your time ... chalk it up to memory issues and a fevered brain.
I had actually wrapped the atr function - and subtracted -1 to get around another problem in the early days of my using backtrader.
I subsequently changed my code to work differently - as my understanding improved - but I obviously forgot to go back and check some of the older stuff and there in plain sight was an index decrement before I accessed the ATR series.

The original issue however still remains - and this could be purely my understanding of it.  I thought when two series are run together (5min and daily in our example) - that on every bar of the lower timeframe series (5min) - the bar of the higher time frame series would be presented.  I found that on the Last day - at midnight - the last daily bar was presented ONCE and then the datetime field became a NaN.
I got around this - by caching what I needed from the Daily bar - once a day as soon as I got it - instead of expecting it to be there every time.  Its this edge condition on the last day -that caused me in the early days to subtract -1 - as it made my crash go away ... lol talk about bug masking.

Here is the sample strategy segment and the output - the ATR values should be familiar from your own experiments above.  I am hoping to get a better understanding - so I dont sweep any more issues under the rug in my ignorance.

Thanks,
Partha

class TEST_STRAT(bt.Strategy):

    def __init__(self):
        self.atrdata = self.data1 if len(self.datas) > 1 else self.data0
        self.atr = btind.ATR(self.atrdata, period=5, movav=btind.MovAv.SMA)

    def next(self):
        dt00 = self.data0.datetime.datetime().isoformat()
        dt10 = self.atrdata.datetime.datetime().isoformat()
        print('%d: Intraday: %s - Day %s %0.4f' % (len(self.datas), dt00, dt10, self.atr[0]))



Output:

Intraday: 2016-03-22T21:20:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:25:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:30:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:35:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:40:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:45:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:50:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T21:55:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:00:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:05:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:10:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:15:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:20:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:25:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:30:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:35:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:40:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:45:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:50:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T22:55:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-22T23:00:00 - Day 2016-03-22T00:00:00 7.1464
2: Intraday: 2016-03-23T00:00:00 - Day 2016-03-23T00:00:00 8.5744
Traceback (most recent call last):
  File "C:\Users\partha\GitHub\PyTrade\spreadind.py", line 258, in <module>
    runstrat()
  File "C:\Users\partha\GitHub\PyTrade\spreadind.py", line 216, in runstrat
    cerebro.run()
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 360, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 437, in runstrategies
    self._runonce(runstrats)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 535, in _runonce
    strat._oncepost()
  File "C:\Python27\lib\site-packages\backtrader\strategy.py", line 209, in _oncepost
    self.next()
  File "C:\Users\partha\GitHub\PyTrade\spreadind.py", line 64, in next
    dt10 = self.atrdata.datetime.datetime().isoformat()
  File "C:\Python27\lib\site-packages\backtrader\linebuffer.py", line 335, in datetime
    return num2date(self.array[self.idx + ago])
  File "C:\Python27\lib\site-packages\backtrader\utils\dateintern.py", line 69, in _num2date
    ix = int(x)
ValueError: cannot convert float NaN to integer

**Comment by mementum** [comment]
There is (for sure) a bug there, but your actual problem has to do with timing and I guess with expectations.

Your daily bars have the following time coded: `00:00:00`. Obviously, the daily bar can only be "done" once all the intraday bars have been seen. And your intraday bars have times which are greater than `00:00:00`.

`backtrader` has *human* limitations and believes that such a daily bar with a `00:00:00` time has already been closed and is therefore delivered with the intraday bar of the same time.

If you change the time of your daily bars to `23:59:59` the following output takes place:

```
1714: Minute 2016-02-09T00:00:00 Date 2016-02-08 14.7292
1715: Minute 2016-02-09T00:05:00 Date 2016-02-08 14.7292
1716: Minute 2016-02-09T00:10:00 Date 2016-02-08 14.7292
...
10528: Minute 2016-03-23T14:30:00 Date 2016-03-22 7.1464
10529: Minute 2016-03-23T14:35:00 Date 2016-03-22 7.1464
10530: Minute 2016-03-23T14:40:00 Date 2016-03-22 7.1464
```

With no error.

This is the only logical way to present the provided data. Looking at the last 3 lines

  - The intraday bars of 2016-03-23 are presented along with the last "closed" daily bar. Because 2016-03-23 is not yet over.

My educated guess is that what you are looking for is *data replay*. You want to see the intraday bars and how that's affecting the daily bar.

See the output produced by having `cerebro.replaydata(data0, timeframe=bt.TimeFrame.Days)`. (where `data0` is the 5 minute input) instead of adding the daily data directly.

```
6: Minute 2016-02-08T01:35:00 Date 2016-02-08 11.5532
6: Minute 2016-02-08T02:15:00 Date 2016-02-08 11.8232
6: Minute 2016-02-08T03:40:00 Date 2016-02-08 12.0072
...
37: Minute 2016-03-23T13:35:00 Date 2016-03-23 8.9084
37: Minute 2016-03-23T13:45:00 Date 2016-03-23 9.0544
37: Minute 2016-03-23T13:55:00 Date 2016-03-23 9.2384
37: Minute 2016-03-23T14:05:00 Date 2016-03-23 9.2384
37: Minute 2016-03-23T14:20:00 Date 2016-03-23 9.2384
37: Minute 2016-03-23T14:30:00 Date 2016-03-23 9.2384
37: Minute 2016-03-23T14:40:00 Date 2016-03-23 9.2384
```

Now the intraday bars on 2016-03-23 have a counterpart (daily bar) with the same date. And the `ATR` is being recalculated for each 5 minutes bar on the daily bar. Obviously the last 5 price changes are non-existent and that's why the `ATR` remains constant.

If you wonder why the value is `9.2384` at the end of 2016-03-23 instead of your expected `8.5744`. Options:

  - The set of 5 minute bars misses bars which would change the `close`, `high`, or `low` prices of some daily bars (or contains too many, like pre-market/after-market)

  - The platform may be calculating things wrongly.

If instead of *replaying* the 5 minute bars we *resample* them to see if they are like the daily bars:

(add only 1 data to cerebro with `cerebro.resampledata(data0, timeframe=bt.timeFrame.Days)`)

```
00: date,open,high,low,close
01: 2016-02-01,190.75,199.52,182.75,196.32
02: 2016-02-02,196.35,196.94,180.23,183.20
03: 2016-02-03,184.29,184.90,170.18,173.58
...
35: 2016-03-21,233.00,239.88,232.74,238.50
36: 2016-03-22,238.50,238.99,232.56,233.00
37: 2016-03-23,234.50,235.20,220.38,221.00
```

And we look at the same days in the original `tsla` input:

```
datetime,open,high,low,close,volume,openinterest
2016-02-01,188.76,199.52,182.75,196.94,5297639,0
2016-02-02,192.42,193.12,180.23,182.78,5773637,0
2016-02-03,183.59,183.94,170.18,173.48,7931362,0
...
2016-03-21,235.34,239.88,235,238.32,5288985,0
2016-03-22,237.21,238.99,232.558,234.24,4300628,0
2016-03-23,232.37,234.73,222.03,222.58,4921013,0
```

We can immediately see that the *resampled* bars and the *daily* bars are not equal and hence the difference in the final value of the `ATR` above.

I would gladly blame the *resampling* code in `backtrader` but the 5 minute input for 2016-02-01 contains a 1st bar with an open value of `190.75` at 01:15:00. The 1st 5 minute bar with an open value of `188.76` is at 06:35:00.

The same `06:35:00` time applies when looking for an opening time which matches the daily input for the 2nd daily bar and also for the 3rd. So it is obvious that the 5 minute input actually contains too many bars.

The question here is if you want to compare inputs which actually carry a different data payload.

**Comment by mementum** [comment]
Have a look at this *data replaying* sample for your 5 minute data. It filters all data happening before 06:35 and any data happening after 17:30.

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.filters as btfilters
import backtrader.indicators as btind


class St(bt.Strategy):
    def __init__(self):
        atrdata = self.data1 if len(self.datas) > 1 else self.data0
        self.atr = btind.ATR(atrdata, period=5, movav=btind.MovAv.SMA)

    def next(self):
        dt00 = self.data0.datetime.datetime().isoformat()
        dt10 = self.data1.datetime.date().isoformat()
        print('%d: Minute %s Date %s %.4f' %
              (len(self), dt00, dt10, self.atr[0]))


if __name__ == '__main__':
    cerebro = bt.Cerebro()
    cerebro.addstrategy(St)

    data0 = btfeeds.GenericCSVData(
        dataname='tsla-5min.csv',
        timeframe=bt.TimeFrame.Minutes,
        compression=5,
        sessionstart=datetime.time(6, 31),
        sessionend=datetime.time(17, 30),
    )

    data0.addfilter(btfilters.SessionFilter)
    cerebro.adddata(data0)

    cerebro.replaydata(data0, timeframe=bt.TimeFrame.Days)

    cerebro.run()
```

The output:

```
6: Minute 2016-02-08T06:35:00 Date 2016-02-08 13.3412
6: Minute 2016-02-08T06:45:00 Date 2016-02-08 13.3732
6: Minute 2016-02-08T06:55:00 Date 2016-02-08 13.3732
...
37: Minute 2016-03-23T14:10:00 Date 2016-03-23 8.6964
37: Minute 2016-03-23T14:25:00 Date 2016-03-23 8.6964
37: Minute 2016-03-23T14:40:00 Date 2016-03-23 8.6964
```

The final `ATR` value is `8.6964` much closer to the calculated value using daily bars: `8.5744`.

Why? Because noise added by extra bars (at least those before 06:35) has been filtered out. If the 5 minute input contained the necessary bars to fully reconstruct the `open`, `high`, `low` and `close` prices the output should be a 1 to 1 match.

**Comment by parthasrinivasan** [comment]
This is an issue of my understanding and my  assumption of the convention.
Yes - I do use 2 totally separate data streams - one is the 5min bar stream - downloaded as 5min data - from a exchange approved source.  The other is the daily bar data - again similarly downloaded.
I want to use the ATR from the daily Bars only - because there is enough variation between the Daily bar values and from a synthetically created daily bar from 5min bars .
Now that I know that you are using the Time field in the daily bar - I am glad I used 00:00:00.
I am not looking for replay function.  What I wanted to do was simple - I only process historical - every day - after close - at which point the daily bar is ready 5.00pm Eastern on all products.
So I wanted the ATR to be available with each 5 min bar - but using the most recent 5 days - including the just finished day's bar.  So the ATR value would not change during the entire day.
So for my presentation - I want the date fields in my streams to match exactly. - ie. and if I moved the time code of the daily bar from 00:00 to 23:59 - I would be off by one day (the same result I fudged by reaching back in time with a -1 on the ATR series).
Since I have two streams - both of which are downloaded form a data source as 2 independent streams, I just expected - that on any given day - from 00:00 to 23:59 on that day - the daily bar presented with the 5min bar - would have matching date stamps. - Since they were provided as 2 separate streams.
The notion of the daily bar being 'done" only when the intra-day bars are are seen - didnt occur to me - because look at 3-22 example - the 3-22 daily bar with 00:00 - was presented all day long - perfectly matched against Every bar in the 5min stream that had a 3-22 date-stampe, irrespective of their timestamp.
The only divergence from the behaviour was the last day.
My workaround - was to always keep my daily bar data cached - by saving it on the very first 5min bar of the day (whatever time that was) and then keep re-using till the 5min bar rolled over a date boundary.

**Comment by mementum** [comment]
> First I issued `1.2.4.88` earlier today, which corrects the wrong replay behavior seen above (the data was not being cloned with `cerebro.replaydata` as it was with `cerebro.resampledata`, an oversight from the last update).

Yes, the `2016-03-22 00:00:00` daily bar is presented with the 5 min bars with datetime `2016-03-22 hh:mm:ss` because `hh:mm:ss` in the 5 min bars is greater than `00:00:00`.

The design decisions made when developing `backtrader` try to follow a simple approach (not always achieved) In this case and when mixing datas with different timeframes (1 day and 5 minutes)

  - A daily bar is only presented when its datetime is *equal or greater* than the next incoming 5 min bar.

The reasoning behind being that a daily bar will only be produced by data providers once the flow of intraday bars, the ones that actually make up that bar, has first been produced.

This is because evaluating an intraday bar, during *backtesting*, like for example `2016-03-22 06:35:00` with the `ATR` value for `2016-03-22` would be like *cheating*. In a backtesting environment the daily value is already known because the data used for backtesting is historical data, but in a live environment no such evaluation is possible

  - The daily `ATR` value is only available when the day/session is over

*Replaying* alleviates the situation by providing the *developing* ATR value by means of the reconstruction of the daily bar.

I understand that you consider the 5 min bars and daily bars to be *1 day off*, but this is because the only ATR value available during the evaluation of the intraday bars is that of the previous day.

The following script tries to put all pieces in play.

> Note: the problem above with missing minutes was not the interaction of the *filters* (`SessionFilter` + internal filter for `Replayer`) but rather the mixing of intraday data and `replaydata`.  This doesn't happen with resampling and since both techniques share 98% of the code, it is a very subtle bug.

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import argparse
import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.filters as btfilters
import backtrader.indicators as btind


class St(bt.Strategy):
    def __init__(self):
        atrdata = self.data1 if len(self.datas) > 1 else self.data0
        self.atr = btind.ATR(atrdata, period=5, movav=btind.MovAv.SMA)
        if len(self.datas) > 2:
            self.atr2 = btind.ATR(self.data2, period=5, movav=btind.MovAv.SMA)

    def next(self):
        dt00 = self.data0.datetime.datetime().isoformat()
        if len(self.datas) < 2:
            print('%5d: Minute %s %.4f' %
                  (len(self), dt00, self.atr[0]))
        else:
            dt10 = self.data1.datetime.datetime().isoformat()
            if len(self.datas) < 3:
                print('%5d: Minute %s Date %s %.4f' %
                      (len(self), dt00, dt10, self.atr[0]))

            else:
                dt20 = self.data2.datetime.datetime().isoformat()
                print('%5d: Minute %s Date1 %s Date2 %s %.4f %.2f' %
                      (len(self), dt00, dt10, dt20,
                       self.atr[0], self.atr2[0]))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='')

    parser.add_argument('--sfilter', required=False, action='store_true',
                        help=('Use the SessionFilter'))

    pgroup = parser.add_mutually_exclusive_group(required=False)

    pgroup.add_argument('--daily', required=False, action='store_true',
                        help=('Add the daily data'))

    pgroup.add_argument('--dayresampled', required=False, action='store_true',
                        help=('Add the daily data but resampled'))

    parser.add_argument('--intraday', required=False, action='store_true',
                        help=('Add the intraday data'))

    pgroup = parser.add_mutually_exclusive_group(required=False)

    pgroup.add_argument('--replay', required=False, action='store_true',
                        help=('Replay the intraday data'))

    pgroup.add_argument('--resample', required=False, action='store_true',
                        help=('Resmaple the intraday data'))

    args = parser.parse_args()

    cerebro = bt.Cerebro()
    cerebro.addstrategy(St)

    data0 = btfeeds.GenericCSVData(
        dataname='tsla-5min.csv',
        timeframe=bt.TimeFrame.Minutes,
        compression=5,
        sessionstart=datetime.time(6, 31),
        sessionend=datetime.time(17, 30),
    )

    if args.sfilter:
        data0.addfilter(btfilters.SessionFilter)

    if args.intraday:
        cerebro.adddata(data0)

    # This effectively adds a 2nd data to cerebro
    if args.resample:
        cerebro.resampledata(data0, timeframe=bt.TimeFrame.Days)
    elif args.replay:
        cerebro.replaydata(data0, timeframe=bt.TimeFrame.Days)

    if args.daily:
        data1 = btfeeds.GenericCSVData(
            dataname='tsla-1day.csv',
            timeframe=bt.TimeFrame.Days)
        cerebro.adddata(data1)
    elif args.dayresampled:
        data1 = btfeeds.GenericCSVData(
            dataname='tsla-1day.csv',
            compression=1,
            timeframe=bt.TimeFrame.Days)
        cerebro.resampledata(data1, timeframe=bt.TimeFrame.Days)

    cerebro.run()
```

A run with the following options: `--sfilter --intraday --resample --daily`, produces the following output:

```
  594: Minute 2016-02-09T06:35:00 Date1 2016-02-08T17:00:00 Date2 2016-02-08T23:59:59 14.2432 14.73
  595: Minute 2016-02-09T06:40:00 Date1 2016-02-08T17:00:00 Date2 2016-02-08T23:59:59 14.2432 14.73
...
 3621: Minute 2016-03-23T14:30:00 Date1 2016-03-22T17:00:00 Date2 2016-03-22T23:59:59 6.9384 7.15
 3622: Minute 2016-03-23T14:40:00 Date1 2016-03-23T14:40:00 Date2 2016-03-22T23:59:59 8.6964 7.15
```

> **Note**: I have put a time of 23:59:59 on your daily bars

This shows the intraday time, the resampled time, and atr on it, and the daily time and *atr* on it.

The most important for the example here being the last line:

  - Notice how the resampled daily bar produces `2016-03-23 14:40:00`, because that's the last intraday bar and the system can understand that the day is over. But the real daily bar from the input cannot be produced because it has a time of `23:59:59` and additional intraday bars could still be produced.

And the *ATR* for the last day of the  resampled bar is produced (notice the change from 6.9834 to 8.6964)

This is obviously because the *daily* data source has no intelligence built-in whereas the *resampled* one does.

A 2nd run replaying the data instead of resampling: `--sfilter --intraday --replay --daily`, produces the following output:

```
...
...
 3619: Minute 2016-03-23T14:20:00 Date1 2016-03-23T14:20:00 Date2 2016-03-22T23:59:59 8.6964 7.15
 3620: Minute 2016-03-23T14:25:00 Date1 2016-03-23T14:25:00 Date2 2016-03-22T23:59:59 8.6964 7.15
 3621: Minute 2016-03-23T14:30:00 Date1 2016-03-23T14:30:00 Date2 2016-03-22T23:59:59 8.6964 7.15
 3622: Minute 2016-03-23T14:40:00 Date1 2016-03-23T14:40:00 Date2 2016-03-22T23:59:59 8.6964 7.15
```

And now the difference is that the `replayed` bar is already showing `8.6964` with the last four 5 min bars (none of them change the `truerange` and the `atr` remains constant)

The script allows you to pull an trick: *resample* your own daily data to *daily* to add a bit of intelligence to the data feed. The execution now: `--sfilter --intraday --resample --dayresample`. And the output:

```
...
...
 3621: Minute 2016-03-23T14:30:00 Date1 2016-03-23T14:30:00 Date2 2016-03-22T23:59:59 8.6964 7.15
 3622: Minute 2016-03-23T14:40:00 Date1 2016-03-23T14:40:00 Date2 2016-03-22T23:59:59 8.6964 7.15
 3622: Minute 2016-03-23T14:40:00 Date1 2016-03-23T14:40:00 Date2 2016-03-23T23:59:59 8.6964 8.57
```

Notice how the last value of the `ATR` of the daily *resampled* data changes to `8.57` with the last bar, when the feed has understood that the data has come to an end. But this is just the last bar and you are looking at synchronizing the entire intraday values, with a value which is produced afterwards and this trick cannot be pulled by the platform.

**Comment by parthasrinivasan** [comment]
Daniel,
I agree, the ATR needs to use the preivous 5 days -nothing else make sense and it works cleanly as things stand now, because the first 5min of the day - we can only use the previous 5 daily bars for example.  
I am a bit under the weather and so will not attempt to do stuff (learnt from past attempts to touch code when under the weather).  When I am better - I will 
Thanks for looking at this.  Lets close this issue.
