### ISSUE TITLE
Quick question for RSI indicator

### ISSUE THREAD

**Issue by fanhi00** [mementum/backtrader#68]
Hi Mementum,
When I tried to calculate a short period rsi: RSI(period=2), it gives an error message below. I thought it is because when there are consecutive up days (no down days), you need to add a condition that if no down days in the last (period) number of days, then RSI=100. Is that make sense? Thanks.
``` 
_  File "C:\Users\hui\Anaconda2\lib\site-packages\backtrader\linebuffer.py", line 656, in _once_op
    dst[i] = op(srca[i], srcb[i])
ZeroDivisionError: float division by zero_
```

**Comment by mementum** [comment]
It may well be because the `RSI` depends on what internally Wilder defined as `RS` which is the division of the *Moving Average* of the *UpDays* between the *Moving Average* of the *Down Days*.

The problem is that `100.0` is also not the only sensible default value. Because `UpDays` can also be `0` and you would have a `0 / 0` division. Most probably `50.0` would be the value in that case. The other case with `0 / x` automatically delivers a `0.0`. There are therefore (at least) 2 special cases.

Mathematically, the cases could show up with any period and not only with short periods. Being the usual `RSI` period `14` it seems even probable that a small period of market irrationality could deliver 14 consecutive days in which the close is always greater than that of the day before. It seems less probable (in real life) to have 14 consecutive days in which neither *UpDays* nor *DownDays* show delivering the `0 / 0` case.

`backtrader` already has a handy internal operation for *lines* called `DivByZero` which can be applied to the case (accepts a *default value* for the case in which a `0` denominator shows up)

**Comment by mementum** [comment]
My best bet is in doing something like this for the `RSI`

```python
    Notes:
      - ``safediv`` (default: ``False``) If this parameter is ``True`` the division
        rs = maup / madown will be checked for the special cases in which a
        ``0 / 0`` or ``x / 0`` division will happen

      - ``safehigh`` (default: ``100.0``) will be used for the ``x / 0`` case
      - ``safelow``  (default: ``50.0``) will be used for the ``0 / 0`` case
    '''
    alias = ('RSI', 'RSI_SMMA', 'RSI_Wilder',)

    lines = ('rsi',)
    params = (('period', 14),
              ('movav', MovAv.Smoothed),
              ('upperband', 70.0),
              ('lowerband', 30.0)
              ('safediv', False),
              ('safehigh', 100.0),
              ('safelow', 50.0),
    )
```

You can then call your `RSI` with:

```python
rsi = bt.indicators.RSI(self.data, period=2, safediv=True)
```

And you are free to specify which values have to be delivered for the `0 / 0` and `x / 0` cases with the extra `safehigh` and `safelow` values.

**Comment by mementum** [comment]
A couple of slight changes to better support the `DivZeroByZero` pseudo-indicator were needed. And the `safehigh` and `safelow` params need to be translated when passed to `DivZeroByZero` to make sense as return values.

But the modifications are working. If you are brave enough you can try the development branch which already contains the changes and testcase
