### ISSUE TITLE
Load data block by block

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#74]
when backtesting with a large amount of data, it takes up too much computer memory if loading the data all at once. I am thinking to load it block by block as backtesting goes on. Suppose I have a big data file (or database), and every time I want to load 10 days' data. Once the 10 days' data is used up, I load another 10 days data.  I think I can borrow some idea from your living data example. Before I study it myself, I wonder whether you have some hints or quick example on how to do it. Thank you.

**Comment by mementum** [comment]
Let me see if I understand:

  - _"it takes up too much computer memory if loading the data all at once"_

    This is what's known in `backtrader` as `preload` (parameter to `cerebro`). This is intended to speed up calculations by loading in advance all data.

If you really meant "loading all data in memory", this is by design. The reason:

  - Most often than not I wanted plotting and I therefore expect most people to also use plotting.

If you want to plot, you need to keep the data in memory.

But if you are not plotting then you have the chance to use:

  - `exactbars` when creating an instance of `Cerebro` with `cerebro = bt.Cerebro(exactbars=True)` (you can also use the same parameter later when calling `run` if you prefer to do it later)

When this parameter is `True` the platform will look automatically into the maximum needed size to work effectively. That means:

  - A `Strategy` with a `SimpleMovingAverage(period=50)` will only keep `50` bars in memory (even if your full data set has 2 million bars)

  - A `Strategy` with a `SimpleMovingAverage(period=10)` and `RSI(period=14)` will keep `14` bars in memory, because the `RSI` needs more.

You can have indicators on indicators on indicators: the platform goes as deep as possible to understand what the minimum number of needed lookback bars is needed to successfully perform calculations. 

Of course this has 2 drawbacks

  - At the end of the calculations only the needed amount of lookback bars are available and plotting will only plot those (if the data set has 500 bars if it is possible pointless to just plot 50)

  - If you manually try in the `Strategy` to access a past value larger than the calculated period with something like `if a > self.mysma[-51]` the code will break.

Concluding:

  - if you need plotting, data is going to be in memory

  - if you don't, use `exactbars=True` with `cerebro`
