### ISSUE TITLE
Multidata Strategy with different number of bars

### ISSUE THREAD

**Issue by simhe** [mementum/backtrader#76]
Hi, I am loading S&P500 (^GSPC) and DAX (^GDAXI) data from Yahoo (same date range for example two years) but because of different public holidays in each country there are different numbers of bars in the end.
Only logging the closing prices and dates in the next() function there is a shift. The next() function takes the next bar of each indice, but doesn't compare the dates for equality.
Plotting the data, I would except gaps in the graph, but there are no gaps. Do you have an idea to handle this?  Thanks a lot.

**Comment by mementum** [comment]
Hi. This may be or may not be a limitation of `backtrader`, depending on your expectations.

For having multiple datas, the platform needs that the datas are time aligned and obviously *instruments* with different trading calendars are not time aligned.

There is a good reason for it. See the following naive `next` implementation for a strategy with two such datas:

```python
def next(self):
    if self.data0.close[0] > self.data1.close[0]:
        self.buy()
```

And we have a trading day in which the `^GSPC` (*data0*) traded and the the `^GDAXI` (*data1*) didn't.

  - What should be the value of `self.data1.close[0]`?

The platform has the notion of a `data master` which is the 1st data added to the system. The other datas have to remain in sync with it and the design pattern was made to make it possible to support multiple timeframes (mixing for example *daily* and *weekly* bars)

Looking at the data for `^GSPC` and `^GDAXI` in 2012 the 1st thing:

  - `^GSPC` traded `250` days
  - `^GDAXI` traded `256` days

Let's see what happens if we check the dates for equality with `^GSPC` as *data0* and `^GDAXI` as *data1*:

```
0001: True: data0 2012-01-03T23:59:59 : 2012-01-03T23:59:59 data1
0002: True: data0 2012-01-04T23:59:59 : 2012-01-04T23:59:59 data1
0003: True: data0 2012-01-05T23:59:59 : 2012-01-05T23:59:59 data1
0004: True: data0 2012-01-06T23:59:59 : 2012-01-06T23:59:59 data1
0005: True: data0 2012-01-09T23:59:59 : 2012-01-09T23:59:59 data1
0006: True: data0 2012-01-10T23:59:59 : 2012-01-10T23:59:59 data1
0007: True: data0 2012-01-11T23:59:59 : 2012-01-11T23:59:59 data1
0008: True: data0 2012-01-12T23:59:59 : 2012-01-12T23:59:59 data1
0009: True: data0 2012-01-13T23:59:59 : 2012-01-13T23:59:59 data1
0010: False: data0 2012-01-17T23:59:59 : 2012-01-16T23:59:59 data1
...
...
0248: False: data0 2012-12-27T23:59:59 : 2012-12-18T23:59:59 data1
0249: False: data0 2012-12-28T23:59:59 : 2012-12-19T23:59:59 data1
0250: False: data0 2012-12-31T23:59:59 : 2012-12-20T23:59:59 data1
```

Already on 2012-01-17 (or 16 for `^GDAXI`) there is a discrepancy. But looking at the final result it is clear that `^GSPC` is the `datamaster` because its `250` bars have been delivered. The platform has made its best attempt to deliver the next best possible bar for `^GDAXI` but there are 6 more and cannot keep up.

If we reverse the roles and make `^GDAXI` to be *data0*

```
0001: True: data0 2012-01-03T23:59:59 : 2012-01-03T23:59:59 data1
0002: True: data0 2012-01-04T23:59:59 : 2012-01-04T23:59:59 data1
0003: True: data0 2012-01-05T23:59:59 : 2012-01-05T23:59:59 data1
0004: True: data0 2012-01-06T23:59:59 : 2012-01-06T23:59:59 data1
0005: True: data0 2012-01-09T23:59:59 : 2012-01-09T23:59:59 data1
0006: True: data0 2012-01-10T23:59:59 : 2012-01-10T23:59:59 data1
0007: True: data0 2012-01-11T23:59:59 : 2012-01-11T23:59:59 data1
0008: True: data0 2012-01-12T23:59:59 : 2012-01-12T23:59:59 data1
0009: True: data0 2012-01-13T23:59:59 : 2012-01-13T23:59:59 data1
0010: False: data0 2012-01-16T23:59:59 : 2012-01-13T23:59:59 data1
...
...
0254: True: data0 2012-12-27T23:59:59 : 2012-12-27T23:59:59 data1
0255: True: data0 2012-12-28T23:59:59 : 2012-12-28T23:59:59 data1
0256: True: data0 2012-12-31T23:59:59 : 2012-12-31T23:59:59 data1
```

The `256` trading bars of  `^GDAXI` have been delivered and the platform has tried to compensate the lack of bars in `^GSPC` by taking the next best bar. See how at indexes `0009` and `0010` the date `2015-01-13` repeats and this is because the `data slave` (`^GSPC`) cannot overtake the `datamaster` (`^GDAXI`)

The solution would be to add bars to make both of them have the same length and therefore be time aligned. But then a fundamental question shows up which has to be answered by the one looking for results and not by the platform:

  - What values (ohlc and volume for example) must this *gap* take?

And the answer is not trivial:

  - The bar may be empty (filled with `float('NaN')`) and then calculation of indicators would break with the `NaN` values.

    No, indicators cannot be looking at each individual bar to see if this is a *gap* bar or not, because they are meant to be simple mathematical formulas looking at the `x` past delivered values.

  - The bar may take the values of the last seen bar (or a valued based on those seen)

    The indicators remain active but deliver slightly different results than on the original trading days.

`backtrader` lets you add bars. See this post for how to do it:

  - http://www.backtrader.com/posts/2015-11-21-data-filters/data-filling-filtering/

A `CalendarDays` filter exists which adds bars (choosing how to) for the missing trading days and a sample in the sources:

  - https://github.com/mementum/backtrader/tree/master/samples/calendar-days

**Comment by simhe** [comment]
Thanks for your fast and detailed answer. I can understand your points. Best solution seems to 

> take the values of the last seen bar

But there is something else I want to point out. Lets have a look at your first example,` ^GSPC` as datamaster and `^GDAXI` as slave. Going through the output comparing the dates, the most, nearly all dates are different.
```
...
...
0009 : True : 2012-01-13 : C 1289.09 - 2012-01-13 : C 6143.08
0010 : False : 2012-01-17 : C 1293.67 - 2012-01-16 : C 6220.01
0011 : False : 2012-01-18 : C 1308.04 - 2012-01-17 : C 6332.93
0012 : False : 2012-01-19 : C 1314.5 - 2012-01-18 : C 6354.57
0013 : False : 2012-01-20 : C 1315.38 - 2012-01-19 : C 6416.26
0014 : False : 2012-01-23 : C 1316.0 - 2012-01-20 : C 6404.39
0015 : False : 2012-01-24 : C 1314.65 - 2012-01-23 : C 6436.62
0016 : False : 2012-01-25 : C 1326.06 - 2012-01-24 : C 6419.22
0017 : False : 2012-01-26 : C 1318.43 - 2012-01-25 : C 6421.85
0018 : False : 2012-01-27 : C 1316.33 - 2012-01-26 : C 6539.85
0019 : False : 2012-01-30 : C 1313.01 - 2012-01-27 : C 6511.98
0020 : False : 2012-01-31 : C 1312.41 - 2012-01-30 : C 6444.45
0021 : False : 2012-02-01 : C 1324.09 - 2012-01-31 : C 6458.91
0022 : False : 2012-02-02 : C 1325.54 - 2012-02-01 : C 6616.64
0023 : False : 2012-02-03 : C 1344.9 - 2012-02-02 : C 6655.63
0024 : False : 2012-02-06 : C 1344.33 - 2012-02-03 : C 6766.67
0025 : False : 2012-02-07 : C 1347.05 - 2012-02-06 : C 6764.83
0026 : False : 2012-02-08 : C 1349.96 - 2012-02-07 : C 6754.2
0027 : False : 2012-02-09 : C 1351.95 - 2012-02-08 : C 6748.76
...
...

```
Having a look at line 10
`0010 : False : 2012-01-17 : C 1293.67 - 2012-01-16 : C 6220.01`

The Question is, why is backtrader taking the close `2012-01-16` of `^GDAXI` for `2012-01-17`? We have the real close, looking at the next line 11
`0011 : False : 2012-01-18 : C 1308.04 - 2012-01-17 : C 6332.93`


So the line should or could be:
`0010 : True : 2012-01-17 : C 1293.67 - 2012-01-17 : C 6332.93`
And for all the next lines see above it should also be True. Because we can always deliver the real data/close. But bt is using the data of day before.

Next question, what we are doing with the `^GDAXI` data of `2012-01-16`:

- Ignoring/Removing `2012-01-16` (if you dont want to touch the datamaster)
- Or adding date `2012-01-16` to `^GSPC` and take the values of the last `^GSPC` bar (datamaster size increasing from 250 to 256)

Have a look at the last element:
`0250 : False : 2012-12-31 : C 1426.19 - 2012-12-20 : C 7672.1` (REAL Close 7612.39)
As you can see we take the `^GDAXI` data from `2012-12-20` instead the real data from `2012-12-31`. We have a shift of a few days. 

But what happens if we increase the date range. Starting from 2000-01-01?
`3269 : False : 2012-12-31 : C 1426.19 - 2012-10-24 : C 7192.85` (REAL Close 7612.39)

If I dont missed something: At `2012-12-31`, bt using the close from `2012-10-24`?

**Comment by simhe** [comment]
Just tried the same in _zipline_ to se what happens from `2012-01-01` to `2012-12-31
`

```
0001 : True : 2012-01-03 : close 1277.06 - 2012-01-03 :  close 6166.57
0002 : True : 2012-01-04 : close 1277.30 - 2012-01-04 :  close 6111.55
0003 : True : 2012-01-05 : close 1281.06 - 2012-01-05 :  close 6095.99
0004 : True : 2012-01-06 : close 1277.81 - 2012-01-06 :  close 6057.92
0005 : True : 2012-01-09 : close 1280.70 - 2012-01-09 :  close 6017.23
0006 : True : 2012-01-10 : close 1292.08 - 2012-01-10 :  close 6162.98
0007 : True : 2012-01-11 : close 1292.48 - 2012-01-11 :  close 6152.34
0008 : True : 2012-01-12 : close 1295.50 - 2012-01-12 :  close 6179.21
0009 : True : 2012-01-13 : close 1289.09 - 2012-01-13 :  close 6143.08
0010 : False : 2012-01-13 : close 1289.09 - 2012-01-16 :  close 6220.01
0011 : True : 2012-01-17 : close 1293.67 - 2012-01-17 :  close 6332.93
0012 : True : 2012-01-18 : close 1308.04 - 2012-01-18 :  close 6354.57
0013 : True : 2012-01-19 : close 1314.50 - 2012-01-19 :  close 6416.26
...
...
0254 : True : 2012-12-24 : close 1426.66 - 2012-12-24 :  close 7636.23
0255 : True : 2012-12-26 : close 1419.83 - 2012-12-26 :  close 7636.23
0256 : True : 2012-12-27 : close 1418.10 - 2012-12-27 :  close 7655.88
0257 : True : 2012-12-28 : close 1402.43 - 2012-12-28 :  close 7612.39
0258 : True : 2012-12-31 : close 1426.19 - 2012-12-31 :  close 7612.39
```

Dont know why the size is `258`, but 
```
0009 : True : 2012-01-13 : close 1289.09 - 2012-01-13 :  close 6143.08
0010 : False : 2012-01-13 : close 1289.09 - 2012-01-16 :  close 6220.01
0011 : True : 2012-01-17 : close 1293.67 - 2012-01-17 :  close 6332.93
```
shows _zipline_ adds data to `^GSPC`

**Comment by mementum** [comment]
This issue was in my backlog for a complete overview. An explanation about the behavior and a `WeekDaysFiller` filter to synchronize the data is presented in this blog post:

 - http://www.backtrader.com/posts/2016-04-19-sync-different-markets/sync-different-markets/

But as you have also seen with `zipline` there is no universal solution and I believe you would find many different opinions on synchronizing assets with different trading calendars

**Comment by mementum** [comment]
Synchronization has been reworked with release 1.9.0.99
