### ISSUE TITLE
Example Bidask-to-ohlc.py using a previous file 

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#79]
First of all, thanks a lot by the example bidask-to-ohlc.py. This library is amazing.
I have taken it and i would like to use two files.

  - bidask2.csv-> Day T (Today)
  - bidask3.csv-> Day T-1 (Yesterday)

I would like to load the file bidask3.csv before backtesting using file bidask2.csv, is it possible?

Example:
```python
class St(bt.Strategy) :
    def init(Self):
       # here file bidask3.csv is loaded and then analyse data of this
       # file (bidask3.csv), for example number of trades, order imbalance....
    def next(self):
         # I trade using the information of the previous file bidask3.csv
        print(','.join(str(x) for x in [
            self.data.datetime.datetime(),
            self.data.open[0], self.data.high[0],
            self.data.high[0], self.data.close[0],
            self.data.volume[0]]))
```
Rgds,

JJ

**Comment by mementum** [comment]
http://www.backtrader.com/posts/2016-04-14-bidask-data-to-ohlc/bidask-data-to-ohlc/

**Comment by mementum** [comment]
I believe this *use case* as described is beyond the capabilities of `backtrader`` as it was conceived.

A possible approach would be as follows during the execution of `next`:

  - Accumulate statistics for the day/session/period
  - Check if the `datetime` has rolled over to the new days/session/period
  - If yes, use index `-1` of the `list` in which the statistics are stored for the previous period to do trades during the current period (whilst still accumulating statistics for the current period)

`bidask2.csv` and `bidask3.csv` should be passed from a logical perspective as a single data feed to a `cerebro` instance.

**Comment by junajo10** [comment]
Thanks, i think i will read the file day t-1 before starting strategy and the accumulated statistics data will be an argument of the strategy. What is your opinion about this option?

**Comment by mementum** [comment]
That's an implementation detail. It can be an argument to the strategy, a global variable, read from a file. It can be a proxy object which can serve the statistics from another object, from a file, from a server.

The question is whether you want to do several independent runs or accumulate in real-time. With several runs, you start with data set 0, empty statistics and execute. You move on to data set1, statistics from data set 0 and execute.

In "real time" you make a cut when the "session" is over for data set 1 and the system carry on looking at the statistics generated internally. The `Analyzer` objects are meant for this scenario, because they have a `next` (and others like `notify_trade`) method that will be called on each iteration of the system, but are not expensive in terms of memory, because these objects hold no `lines`.  The `backtrader.analyzers.TradeAnalyzer` keeps the statistics of the executed trades in real time by overriding the `notify_trade` method.

The documentation is unfortunately not the best but it gives an insight:

-- http://backtrader.readthedocs.org/en/latest/analyzers/analyzers.html

The available methods meant to be overriden from `Analyzer` in `analyzer.py`:

```python
    def __init__(self):

    def start(self):

    def stop(self)

    def notify_cashvalue(self, cash, value):

    def notify_order(self, order):

    def notify_trade(self, trade):

    def next(self):

    def prenext(self):

    def nextstart(self):

    def start(self):

    def stop(self):

    def get_analysis(self):

    def print(self, *args, **kwargs):

    def pprint(self, *args, **kwargs):
```

**Comment by junajo10** [comment]
I have analyzed all options, and finally an Analyzer  is the best option.

Thanks a lot
