### ISSUE TITLE
Line objects with logic flags

### ISSUE THREAD

**Issue by kunalpawaskar** [mementum/backtrader#83]
Hi @mementum, 

I had a question on adding Line objects. The intent is to add Lines which capture trade status or logic status. 

I added the following code in the init section
```
  self.longshortpos=1
```
The intent was to have one line that the user can manipulate in next on a running basis and issue buy or sell commands accordingly, in conjunction with other logic. Essentially, longshortpos would be used like a Boolean status.

The starting value 1 is arbitrary. It will be changed in next block

In next block, I kept the following code:

`  self.log('longshortpos: %.2f' % (self.longshortpos[0]))`

The error received is:
```
  self.log('longshortpos: %.2f' % (self.longshortpos[0]))
TypeError: 'int' object is not subscriptable
```
Another attempt was to keep following in init block:

```
 if self.buysell_sig > 0 and not(self.position) and self.data.datetime.time(0) == dt.time(9, 30):
      self.longshortpos=1
```

This time the error is seen at this point itself:

```
  if self.buysell_sig > 0 and not(self.position) and self.data.datetime.time(0) == dt.time(9, 30):
TypeError: __bool__ should return bool, returned LineOwnOperation
```

At a broad level, what is the right approach, if you could guide me here? Thanks.

**Comment by mementum** [comment]
```
  self.longshortpos=1
```

This is an int. If you want to declare a line you have to declare them (in the `Strategy` or in an `Indicator`) See here

  - http://backtrader.readthedocs.io/en/latest/concepts.html#lines-declaration

```python
class SimpleMovingAverage(Indicator):
    lines = ('sma',)
```

`if` and `and`can not be overriden due to the nature of Python. See here:

  - http://backtrader.readthedocs.io/en/latest/concepts.html#some-non-overriden-operators-functions

You have to use `backtrader.If` and `backtrader.And`

During the `__init__` phase the operations do not return values, they return objects which will later in the background be evaluated (lazy evaluation). The user can then in each `next` invocation access the values.

But in this case this `if` logic has to be used in `next`. Accessing `position` (which is not a line but the actual position) only makes sense during `next` when `position` may have actually changed.

**Comment by kunalpawaskar** [comment]
Thanks. Should have understood this one on my own though.
