### ISSUE TITLE
Question: best way to use multiple indicators

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#84]
Hi,

I would like to know your opinion about if this way is the best one to develop these rules:
```
Stoch = Stochastic(10,3,3)
Last = Last Price
PivotPoints(S2, S1, P, R1, R2)
Opt1 = 10

OpenLong  = Stoch >Opt1                 AND Last crosses below S1
OpenShort = Stoch <(100-Opt1)         AND Last crosses above R1

CloseLong  = Last crosses above P
CloseShort = Last crosses below P
```

CODE:
```
self.stoch=indicator.Stochastic(self.data1,period=period,period_dfast=period_dfast,period_dslow=period_dslow)
self.constantValue=10
self.constantValue2=100-self.constantValue
 self.pp = indicator.PivotPoint(self.data1)
self.s1=self.pp.lines.s1
self.s2=self.pp.lines.s2
self.r1=self.pp.lines.r1
self.r2=self.pp.lines.r2
self.signal = indicator.CrossDown(self.data1.close, self.s1)
self.signal2=indicator.Cmp(self.stoch,self.value)
self.signal3=indicator.And(self.signal,self.signal2)
self.signal4=indicator.Cmp(self.stoch,self.value2)
self.signal5 = indicator.CrossOver(self.data1.close, self.r1)
self.signal6 = indicator.CrossOver(self.data1.close, self.pp)
self.signal7 = indicator.CrossDown(self.data1.close, self.pp)
self.signal8=indicator.And(self.signal5,self.signal4)
```
Rgds,
JJ

**Comment by junajo10** [comment]
Also, i would like to speak about using this indicator:
indicator.CrossDown(close, s1)

s1 is calculated with the Pivot Point indicator, and using resample method:
cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=240)--->data1

but from my point of view close should be self.data0.close instead of self.data1.close.
The problem is that length of both series are different so you get this error:
IndexError: array index out of range

In live trading you want to compare your real time close with your 240 min pivot point indicator, by this reason i think close should be self.data0.close.

What is your opinion about this topic? is there any way to use the indicator in the next method instead of init method, so i will use the values?

**Comment by mementum** [comment]
It's always a simple taste, but some things can be for sure simplified for the above rules

```python
params = (('opt1', 10),)
...

stoch = btind.Stochastic(self.data1, 10, 3, 3)
pp = btind.PivotPoint(self.data1)
openlong = bt.And(stoch > self.p.opt1, btind.CrossDown(self.data1, pp.s1))
# similar for openshort
closelong = btind.CrossUp(self.data, pp)  # takes 1st lines ... close and p
# similar for closeshort
```

The problem with `CrossDown` and any other indicator is that *indicators* **MUST** work with objects of same length. Because *indicators* can take anything which is a *lines* object as input, for example: other indicators.

As such and even if an indicator reference the incoming *lines* object as `self.data`, it may be dealing with *anything* and this *anything* must no longer have a reference to anything else.

The real problem here is that `backtrader` supports 2 methods of execution:

  - `runonce=True` indicators are precalculated in batch mode to accelerate things and then the `Strategy` is executed step-by-step (`next`) by moving indicators' pointers forward as needed. This also precludes the definition of indicators in a recursive manner.

  - `runonce=False`. In this case everything is run step-by-step.

You can always compare values from indicators of different lengths in the `next` method of the strategy.

The "different length" topic is always under consideration, but it may not have a full solution given the nature of the problem itself

**Comment by junajo10** [comment]
Thanks a lot, now i will work with the rule:indicators MUST work with objects of same length.

**Comment by junajo10** [comment]
Another question:
openlong = bt.And(stoch > self.p.opt1, btind.CrossDown(self.data1, pp.s1))
# similar for openshort
closelong = btind.CrossUp(self.data, pp)  # takes 1st lines ... close and p
# similar for closeshort

If i use 4 signals:openlong,openshort,closelong,closeshort, is it posible to manage orders in the method notify_order?
 I don´t know how to manage two entry points and two exit points using methods next() and notify_order.

**Comment by mementum** [comment]
It is now possible to mix timeframes by coupling and larger timeframe and then feeding it into an indicator.  See: http://www.backtrader.com/posts/2016-05-05-indicators-mixing-timeframes/indicators-mixing-timeframes/

**Comment by mementum** [comment]
`notify_order` (like the other notification methods) is meant to receive notifications, not actually for executing operations. Although nothing prevents it. In a single `next` cycle, several notifications may be sent to the strategy and that's why I would do everything in `next`.

The code you quote

```python
if self.order:
    return  # if an order is active, no new orders are allowed, in this case two orders could be active
```

is a simple sentinel for simple samples. If `order` is not `None` it is because it has been returned by either `buy` or `sell` and not yet set to `None` when a cancelation or completion is received in `notify_order`
