### ISSUE TITLE
DataResampler (deprecated?)

### ISSUE THREAD

**Issue by kunalpawaskar** [mementum/backtrader#87]
earlier bt.DataResampler was working fine. With refreshed code, it ceased to work. I noticed that you have mentioned in the changelog in 1.2.1.88:

Remove old DataReplayer/DataResampler and cerebro resampledata_old and
    replaydata_old which were using them
  - Adapt docs and test to remove DataReplayer/DataResampler and document the
    newer interfaces

I guess the docs still reflect the earlier code.  Is there an update on functionality now? Thanks.

**Comment by mementum** [comment]
Resampling is at: http://backtrader.readthedocs.io/en/latest/data-resampling/data-resampling.html

Excerpt:

------------------------------
Instead of using cerebro.adddata(data) to put a data into the system use
```
    cerebro.resampledata(data, **kwargs)
```

There are two main options that can be controlled

  - Change the timeframe
  - Compress bars

------------------------------

Further down the document part of the sample code is shown:

------------------------------

```python
    # Load the Data
    datapath = args.dataname or '../../datas/2006-day-001.txt'
    data = btfeeds.BacktraderCSVData(dataname=datapath)

    # Handy dictionary for the argument timeframe conversion
    tframes = dict(
        daily=bt.TimeFrame.Days,
        weekly=bt.TimeFrame.Weeks,
        monthly=bt.TimeFrame.Months)

    # Add the resample data instead of the original
    cerebro.resampledata(data,
                         timeframe=tframes[args.timeframe],
                         compression=args.compression)
```

------------------------------

(And further below, the entire script)

The source is available at:https://github.com/mementum/backtrader/blob/master/docs/data-resampling/resampling-example.py

Although the original sample is still in the samples directory and it would (and will) be better removed

**Comment by mementum** [comment]
I rechecked the sample and it already contains new code. It does also contain old code (to be activated with the parameter ``--oldrs`` for what it was the transition time)

Available at: https://github.com/mementum/backtrader/blob/master/samples/data-resample/data-resample.py

I will in any case add a couple of clarifying comments to it

**Comment by kunalpawaskar** [comment]
Thanks.
