### ISSUE TITLE
Zero Division error for Sharpe ratio

### ISSUE THREAD

**Issue by Ravi1729** [mementum/backtrader#88]
Hi mementum,

I am a newbie to this backtrader environment. When I try to run the  following code I am getting Zero Division error while calculating the sharpe ratio. I am using the .csv file downloaded from yahoo finance as Datafeed. Attached zip file has the datafeed.
[Apple.zip](https://github.com/mementum/backtrader/files/254857/Apple.zip)
[Apple.zip](https://github.com/mementum/backtrader/files/254858/Apple.zip)

```python
import backtrader as bt
import backtrader.analyzers as ANZ
import backtrader.strategies as strategy

data=bt.feeds.YahooFinanceCSVData(dataname='D:\Apple.csv')

X=bt.Cerebro()
X.adddata(data)
X.addstrategy(strategy.SMA_CrossOver)
X.addanalyzer(ANZ.SharpeRatio)
res=X.run()
```
What's the mistake I am doing here?

![ipython error](https://cloud.githubusercontent.com/assets/19264988/15111898/d3e88774-161c-11e6-8c6a-7ea6f0de9001.JPG)

**Comment by mementum** [comment]
The strategy has executed no trade at all. That's due to the fact that the file is in Yahoo order (newest above) rather than how the rest of the world takes it (oldest first)

Use `reverse=True` as a param to the YahooFinanceCSVData

Here: http://backtrader.readthedocs.io/en/latest/dataautoref.html

(You can there see that the default value is `False` for `reverse`

Or in the docstring:

```python
class YahooFinanceCSVData(feed.CSVDataBase):
    '''
    Parses pre-downloaded Yahoo CSV Data Feeds (or locally generated if they
    comply to the Yahoo format)

    Specific parameters:

      - ``dataname``: The filename to parse or a file-like object

      - ``reverse``

        It is assumed that locally stored files have already been reversed
        during the download process

      - ``adjclose``

        Whether to use the dividend/split adjusted close and adjust all
        values according to it.

    '''
```

The yahoo download tool that comes with `backtrader` automatically reverses the downloads.

**Comment by Ravi1729** [comment]
I got my mistake. Thank you very much. Now I am able to run the code without any error. I am going to close this issue.
