### ISSUE TITLE
Question: iterate main loop + return values

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#90]
Hi,

I have written this code:

```python
class X (bt.Strategy):

     def stop(self):  
        with open("test.txt", "a") as myfile:
            //write a summary of the  simulation
            myfile.writelines(.....)

numdays = 5
asset='XYZ'
path = ("test.txt")
a = datetime.datetime(2015,3,17)
for x in range (0, numdays):
           s = a + datetime.timedelta(days = x)
           sDay=str(s.year)+"-"+str(s.month)+"-"+str(s.day)
           datapath = ('./data/'+asset+'/'+sDay+"-"+asset+'.csv')
           data = bt.feeds.GenericCSVTradesQuote(dataname=datapath)
           cerebro = bt.Cerebro() 
            cerebro.addstrategy(X,....)
            cerebro.run() # -->store results some variable?

# HERE I WOULD LIKE TO TAKE DATA OF EACH SIMULATION AND SHOW RESULTS
stock = pd.read_csv(path,header=None)  
plt.hist(stock.values.ravel(), bins=10, color='c')
```

Is there any way to obtain results of a simulation without storing in a file and then read it?

Rgds,
JJ

**Comment by junajo10** [comment]
Also, if you can save plot as pdf, png instead of showing the plot, so i can save all plots and then analyze all of them

**Comment by mementum** [comment]
http://backtrader.readthedocs.io/en/latest/cerebro.html

Returning the results
*********************

``cerebro`` returns the instances of the strategies it created during
backtesting. This allows to analyze what they did, because all elements in the
strategies are accessible::

  result = cerebro.run(**kwargs)

The format of ``result`` returned by ``run`` will vary depending on whether *optimization*
is used (a *strategy* was added with ``optstrategy``):

  - All strategies added with ``addstrategy``

    ``result`` will be a ``list`` of the instances run during the backtesting

  - 1 or more strategies were added with ``optstrategy``

    ``result`` will be a ``list`` of ``list``. Each internal list will contain
    the strategies after each optimization run

========================================
If you only add 1 strategy per run and do it with `addstrategy`:

```python
result = cerebro.run()
print(result)
```

And the output should look like

```
[bt.Strategy object at 0x000000000]
```

And everything which has been collected is inside of the strategy.

Plotting and anything that has to do with it is 100% `matplotlib` related. Visual output for quick inspection is nice but not a must.
