### ISSUE TITLE
Get initial price in next() funtion 

### ISSUE THREAD

**Issue by muke5hy** [mementum/backtrader#92]
First sorry for asking as issue, this is not an issue but a query. I did not find any other way to get a quick reply. 

I have CSV file which I'm loading as DataFrame. The file consist of Intra day records of 1 minute. In my algo I want to compare first open price with close price of each minute data. I'm not able to keep a reference of Initial open price. 

```
    def next(self):  
        print self.dataopen[len(self.dataopen)-1], self.dataopen[0], 

```
non of the above print shows the first initial open price.

**Comment by mementum** [comment]
None of them should give you the `open` price of the 1st bar. When you are in the `next` method of the strategy (or for the sake of it ... of an indicator) the point at which things are evaluated is the most recent delivered price. There is nothing looking forward for the strategy (even if the end user of the platform) knows that backtesting is taking place and the data is known in advance. As such:

  - Index `0` points to the current data
  - Index `-1` points to the previous delivered data
  - Index `-2` points to the data delivered 2 iterations ago

To get the 1st minute:

```python
    self.data.open[-len(self.data) + 1]
```

The math for the 1st iteration

  - `len(self.data) -> 1`
  - `-1 + 1 = 0`

When there is only 1 iteration the index we are looking for is `0`.

Moving to the 2nd bar:

  - `len(self.data) -> 2`
  - `-2 + 1 = -1`

We go a look at the previous delivered data which is `-1`. And the number keeps growing negative, because the 1st delivered price is further away with each iteration.

**Comment by muke5hy** [comment]
Thank you for detailed explanation. This resolved my problem.
